#!/usr/bin/env node
// Mars pilot acceptance uses only the viewer's pointer/touch DOM path.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('/home/ubuntu/LOOM_SOLAR_INSPECTOR/node_modules/playwright');
const base=process.env.SOLAR_BASEMAP_URL||'http://127.0.0.1:8770',evidence=process.env.SOLAR_BASEMAP_EVIDENCE||'/tmp/solar-basemap-mars-acceptance';
fs.mkdirSync(evidence,{recursive:true});const wait=ms=>new Promise(r=>setTimeout(r,ms));
const state=page=>page.evaluate(()=>window.__solarBasemapPilotState());
async function marsPoint(page){const s=await state(page),c=s.mars.clip;assert(c,'Mars must be observable in the continuous Solar scene');return {x:(c[0]+1)*206,y:(1-c[1])*457.5,state:s}}
async function pinch(cdp,x,y,factor){const half=44,outer=half*factor;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-half,y,radiusX:3,radiusY:3,force:1,id:1},{x:x+half,y,radiusX:3,radiusY:3,force:1,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-outer,y,radiusX:3,radiusY:3,force:1,id:1},{x:x+outer,y,radiusX:3,radiusY:3,force:1,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})}
async function twist(cdp,x,y){const radius=42,a=.24;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-radius,y,radiusX:3,radiusY:3,force:1,id:3},{x:x+radius,y,radiusX:3,radiusY:3,force:1,id:4}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-radius*Math.cos(a),y:y-radius*Math.sin(a),radiusX:3,radiusY:3,force:1,id:3},{x:x+radius*Math.cos(a),y:y+radius*Math.sin(a),radiusX:3,radiusY:3,force:1,id:4}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})}
async function main(){
 const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:412,height:915},deviceScaleFactor:3,hasTouch:true}),page=await context.newPage(),cdp=await context.newCDPSession(page),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>requests.push(r.url()));
 try{
  await cdp.send('Network.enable');await page.goto(`${base}${base.includes('?')?'&':'?'}delivery=progressive`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__solarBasemapReady&&!window.__solarBasemapError,{timeout:120000});await page.waitForFunction(()=>window.__solarBasemapScene?.markers>0&&window.__solarBasemapScene?.lines.length>0,{timeout:30000});
  const initial=await state(page),initialFull=await page.evaluate(()=>window.__solarBasemapReport()),embedded=initialFull.root_embedded_budget.max_css_px;assert(initial.solar.draws.length>0,'coarse Solar geometry must populate the draw list');assert(initial.lines.some(x=>x.node_id==='solar'&&x.clip_vertices>0),'coarse Solar geometry must render');
  const initialTarget=initial.camera.target_km,initialRotation=initial.camera.rotation;
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:190,y:450,radiusX:3,radiusY:3,force:1,id:7}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:198,y:454,radiusX:3,radiusY:3,force:1,id:7}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait(80);
  const panned=await state(page);assert.notDeepEqual(panned.camera.target_km,initialTarget,'one-finger drag must pan');assert.deepEqual(panned.camera.rotation,initialRotation,'one-finger drag must not rotate');
  await page.evaluate(()=>{window.__marsPilotTrace=[];const observe=()=>{const s=window.__solarBasemapPilotState();window.__marsPilotTrace.push({time:performance.now(),level:s.solar.selected_level,drawLevels:s.solar.levels,errorCssPx:s.solar.error_css_px,status:s.solar.status,marsVisible:s.mars.visible,phobos:s.lines.some(x=>x.feature_id==='PHOBOS'&&x.clip_vertices>0),deimos:s.lines.some(x=>x.feature_id==='DEIMOS'&&x.clip_vertices>0)});requestAnimationFrame(observe)};requestAnimationFrame(observe)});
  const coarsePixels=await page.evaluate(()=>window.__solarBasemapReadPixels()),focalDrift=[];let finePixels=null,pinchDistanceStart=null,pinchDistanceEnd=null;
  for(let i=0;i<64;i++){
   const before=await marsPoint(page),center={x:Math.max(20,Math.min(392,before.x)),y:Math.max(50,Math.min(875,before.y))};pinchDistanceStart??=before.state.camera.distance_km;await pinch(cdp,center.x,center.y,1.32);await wait(45);const after=await marsPoint(page);pinchDistanceEnd=after.state.camera.distance_km;focalDrift.push(Math.hypot(after.x-center.x,after.y-center.y));const s=after.state;
   if(!finePixels&&s.solar.levels.some(level=>level>2)){const drawn=s.lines.filter(x=>x.node_id==='solar'&&x.level>2&&x.clip_vertices>0),amber=await page.evaluate(()=>window.__solarBasemapReadPixels().amber_line_pixels);if(drawn.length&&amber>0)finePixels={step:i,levels:s.solar.levels,drawn,draw_list:s.solar.draws.filter(x=>x.level>2),amber_line_pixels:amber};}
   if(s.lines.some(x=>x.feature_id==='PHOBOS'&&x.clip_vertices>0)&&s.lines.some(x=>x.feature_id==='DEIMOS'&&x.clip_vertices>0)&&s.presentation.labels.some(x=>x.body_id==='MARS'))break;
  }
  const finalTouch=await state(page);assert(finePixels,'finer Solar LOD must reach draw list and rendered pixels on the user gesture path');assert(finalTouch.lines.some(x=>x.feature_id==='PHOBOS'&&x.clip_vertices>0)&&finalTouch.lines.some(x=>x.feature_id==='DEIMOS'&&x.clip_vertices>0),'the same touch route must reach visible Phobos and Deimos context');
  const rotateBefore=await state(page);await twist(cdp,206,457);await wait(80);const rotateAfter=await state(page);assert.notDeepEqual(rotateAfter.camera.rotation,rotateBefore.camera.rotation,'two-finger twist must use the distinct rotation gesture');assert(Math.abs(rotateAfter.camera.distance_km/rotateBefore.camera.distance_km-1)<.05,'two-finger twist must not act as a zoom gesture');
  const end=rotateAfter,marsLabel=end.presentation.labels.find(x=>x.body_id==='MARS'),marsOrbit=end.lines.find(x=>x.feature_id==='MARS'&&x.node_id==='solar'&&x.clip_vertices>0),phobos=end.lines.find(x=>x.feature_id==='PHOBOS'&&x.clip_vertices>0),deimos=end.lines.find(x=>x.feature_id==='DEIMOS'&&x.clip_vertices>0),pixels=await page.evaluate(()=>window.__solarBasemapReadPixels());
  assert(marsLabel,'Mars identity label must remain visible in Mars-local context');assert(marsOrbit?.presentation_context==='MARS_HELIOCENTRIC_LOCAL_ARC'&&marsOrbit.context_radius_km===5_000_000,'Mars heliocentric curve must remain as a bounded parent-context arc');assert(phobos&&deimos,'both Mars-local curves must be rendered');assert(pixels.mint_line_pixels>0,'parent-relative geometry must contribute rendered pixels');assert(focalDrift.every(x=>x<22),'focal pinch must keep Mars near the gesture point');
  assert(pinchDistanceEnd<pinchDistanceStart,'pinch must zoom the continuous scene');assert.notDeepEqual(finalTouch.camera.target_km,panned.camera.target_km,'focal zoom must translate the target to preserve the selected world point');
  const sunSymbol=initial.symbols.find(x=>x.body_id==='SUN'),planetSymbol=initial.symbols.find(x=>x.body_id==='MARS'),minorSymbol=end.symbols.find(x=>x.kind==='minor');assert(sunSymbol&&planetSymbol&&minorSymbol,'Solar overview and Mars approach must expose the symbol hierarchy');assert(sunSymbol.size_css_px>planetSymbol.size_css_px&&planetSymbol.size_css_px>minorSymbol.size_css_px,'Sun, planet and minor-body symbols must use a clear size hierarchy');
  const pxPerKm=915/(2*Math.tan(Math.PI/8)*end.camera.distance_km),readScale=Number(end.presentation.scale.match(/≈ ([\d,]+(?:\.[\d]+)?(?:e[+-]?\d+)?) km/)[1].replaceAll(',','')),expectedPerPixel=1/pxPerKm;assert(Math.abs(readScale/expectedPerPixel-1)<.01,'scale readout must match the camera projection at the scene center');assert(Math.abs(end.presentation.scale_bar_width_css_px-end.presentation.scale_bar_km*pxPerKm)<2,'scale bar length must represent its labeled governed distance');assert(marsOrbit.opacity<phobos.opacity,`parent arc opacity ${marsOrbit.opacity}; moon opacity ${phobos.opacity}`);
  const trace=await page.evaluate(()=>window.__marsPilotTrace);assert(trace.some(x=>x.level>2&&x.drawLevels.includes(x.level)&&x.errorCssPx<=.75),'fine Solar geometry must render within the fixed 0.75 CSS px selection bound');assert(!trace.some(x=>x.errorCssPx>.75&&!x.drawLevels.some(l=>l>2)),'coarse Solar geometry must not exceed the bound before fine geometry is drawn');assert.equal(requests.filter(x=>/authority|resolver|ephemeris|state-api/i.test(x)).length,0,'viewer must not call authority/resolver/state APIs');assert.equal(errors.length,0,'browser must have no uncaught errors');
  const result={schema:'loom.solar-basemap.mars-real-user-acceptance/0.1',method:'DOM pointer/touch events only; no camera/target mutation, flight hook, or system switch',viewport:{width:412,height:915,dpr:3,rendererDpr:2},product_build_id:end.build_id,initial:{distance_km:initial.camera.distance_km,solar_levels:initial.solar.levels,coarse_pixels:coarsePixels},one_finger_pan:{target_before:initialTarget,target_after:panned.camera.target_km,rotation_unchanged:true},focal_pinch:{steps:focalDrift.length,distance_before_km:pinchDistanceStart,distance_after_km:pinchDistanceEnd,max_mars_anchor_drift_css_px:Math.max(...focalDrift)},two_finger_twist:{rotation_before:rotateBefore.camera.rotation,rotation_after:end.camera.rotation,distance_unchanged:true},fine_solar_lod:{embedded_max_error_css_px:embedded,...finePixels,frame_samples:trace.length,max_coarse_error_css_px:Math.max(0,...trace.filter(x=>!x.drawLevels.some(l=>l>2)).map(x=>x.errorCssPx))},mars_context:{distance_km:end.camera.distance_km,heliocentric_label:marsLabel,heliocentric_orbit:marsOrbit,phobos,deimos,context:end.presentation.context,scale:end.presentation.scale,scale_bar_km:end.presentation.scale_bar_km,mint_line_pixels:pixels.mint_line_pixels},authority_calls:0,page_errors:errors};
  const out=path.join(evidence,'solar-basemap-mars-real-user-acceptance.json');fs.writeFileSync(out,JSON.stringify(result,null,2));await page.screenshot({path:path.join(evidence,'solar-basemap-mars-real-user-acceptance.png')});console.log(JSON.stringify({evidence:out,distance_km:end.camera.distance_km,fine_levels:finePixels.levels,frames:trace.length,mars_context:result.mars_context}));
 }finally{await context.close();await browser.close()}
}
main().catch(e=>{console.error(e);process.exitCode=1});
