#!/usr/bin/env node
// Qualifying evidence uses only touch input on the published viewer and read-only inspection.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('/home/ubuntu/LOOM_SOLAR_INSPECTOR/node_modules/playwright');
const base=process.env.SOLAR_BASEMAP_URL||'http://127.0.0.1:8770';
const evidence=process.env.SOLAR_BASEMAP_EVIDENCE||'/tmp/solar-basemap-mars-acceptance';
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const read=page=>page.evaluate(()=>window.__solarBasemapPilotState());
const point=(symbol)=>({x:(symbol.clip[0]+1)*206,y:(1-symbol.clip[1])*457.5});
async function touch(cdp,type,points){await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(([x,y,id])=>({x,y,id,radiusX:3,radiusY:3,force:1}))});}
async function tap(cdp,x,y,id=1){await touch(cdp,'touchStart',[[x,y,id]]);await touch(cdp,'touchEnd',[]);}
async function pinch(cdp,x,y,spanRatio){const start=40,end=start*spanRatio;await touch(cdp,'touchStart',[[x-start,y,1],[x+start,y,2]]);await touch(cdp,'touchMove',[[x-end,y,1],[x+end,y,2]]);await touch(cdp,'touchEnd',[]);}
async function open(browser,errors,requests){const page=await browser.newPage({viewport:{width:412,height:915},deviceScaleFactor:3,hasTouch:true}),cdp=await page.context().newCDPSession(page);page.on('pageerror',error=>errors.push(String(error)));page.on('request',request=>requests.push(request.url()));await page.goto(`${base}${base.includes('?')?'&':'?'}delivery=progressive`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__solarBasemapReady&&!window.__solarBasemapError&&window.__solarBasemapScene?.markers>0,{timeout:120000});return {page,cdp};}
async function focusQualification(browser,id,errors,requests){const {page,cdp}=await open(browser,errors,requests);try{const before=await read(page),body=before.symbols.find(x=>x.body_id===id);assert(body?.clip&&body.kind!=='minor',`${id} must have a visible governed marker`);const hit=point(body);await tap(cdp,hit.x,hit.y);await page.waitForFunction(name=>window.__solarBasemapPilotState().selected_body_id===name,id,{timeout:15000});const selected=await read(page);assert(selected.presentation.selection_visible,`${id} must have a visible selection ring`);assert.equal(selected.camera.distance_km,before.camera.distance_km,'selection must not teleport the camera distance');
    if(id!=='SUN'){const world=await page.evaluate(name=>window.__solarBasemap.catalog().find(f=>f.body_id===name).position_km,id);await page.waitForFunction(({name,world})=>{const s=window.__solarBasemapPilotState();return s.selected_body_id===name&&Math.hypot(...s.camera.target_km.map((v,i)=>v-world[i]))<1;},{name:id,world},{timeout:30000});}
    const after=await read(page);return {body_id:id,tap_css_px:hit,selected:after.selected_body_id,selection_visible:after.presentation.selection_visible,camera_distance_unchanged:after.camera.distance_km===before.camera.distance_km,focus_target_km:after.camera.target_km};
  }finally{await page.close();}}
async function main(){fs.mkdirSync(evidence,{recursive:true});const browser=await chromium.launch({headless:true}),errors=[],requests=[];try{
  const {page,cdp}=await open(browser,errors,requests),overview=await read(page);await page.screenshot({path:path.join(evidence,'solar-basemap-pixel-repair-overview.png')});
  const symbolKinds=Object.fromEntries(['SUN','EARTH','MARS'].map(id=>[id,overview.symbols.find(x=>x.body_id===id)]));assert(symbolKinds.SUN&&symbolKinds.EARTH&&symbolKinds.MARS,'the overview must expose governed Sun/Earth/Mars symbols');assert(symbolKinds.SUN.size_css_px>symbolKinds.EARTH.size_css_px&&symbolKinds.EARTH.size_css_px>overview.symbols.find(x=>x.kind==='minor').size_css_px,'Sun/planet/minor symbol sizes must form a hierarchy');
  assert.deepEqual(overview.product_local_nodes,['system:EARTH','system:MARS','system:PLUTO'],'qualified product has exactly three local-system nodes');
  const focus=[];for(const id of ['SUN','EARTH','MARS','JUPITER','SATURN'])focus.push(await focusQualification(browser,id,errors,requests));
  const initial=await read(page),initialTarget=initial.camera.target_km,initialRotation=initial.camera.rotation;await touch(cdp,'touchStart',[[150,550,11]]);await touch(cdp,'touchMove',[[162,557,11]]);await touch(cdp,'touchEnd',[]);await wait(120);const panned=await read(page);assert.notDeepEqual(panned.camera.target_km,initialTarget,'one finger must pan');assert.deepEqual(panned.camera.rotation,initialRotation,'one finger must not rotate');
  const mars=panned.symbols.find(x=>x.body_id==='MARS'),marsHit=point(mars);await tap(cdp,marsHit.x,marsHit.y,12);await page.waitForFunction(()=>window.__solarBasemapPilotState().selected_body_id==='MARS',{timeout:15000});const marsWorld=await page.evaluate(()=>window.__solarBasemap.catalog().find(f=>f.body_id==='MARS').position_km);await page.waitForFunction(world=>Math.hypot(...window.__solarBasemapPilotState().camera.target_km.map((v,i)=>v-world[i]))<1,marsWorld,{timeout:30000});
  await page.evaluate(()=>{window.__marsPilotTrace=[];const observe=()=>{const s=window.__solarBasemapPilotState();window.__marsPilotTrace.push({level:s.solar.selected_level,drawLevels:s.solar.levels,errorCssPx:s.solar.error_css_px,solarLines:s.lines.filter(x=>x.node_id==='solar'&&x.clip_vertices>0).map(x=>({id:x.feature_id,level:x.level})),localLines:s.lines.filter(x=>x.node_id==='system:MARS'&&x.clip_vertices>0).map(x=>x.feature_id)});requestAnimationFrame(observe)};requestAnimationFrame(observe)});
  const centered=await read(page),center=point(centered.symbols.find(x=>x.body_id==='MARS'));await pinch(cdp,center.x,center.y,1.04);await wait(120);const noise=await read(page);assert(Math.abs(noise.camera.distance_km/centered.camera.distance_km-1)<1e-10,'sub-deadband pinch noise must not zoom');assert.deepEqual(noise.camera.target_km,centered.camera.target_km,'sub-deadband noise must not pan the map');
  const steps=[];let fine=null,complete=null;for(let i=0;i<24;i++){const before=await read(page),body=before.symbols.find(x=>x.body_id==='MARS');assert(body?.clip,'selected Mars must stay visible during approach');const at=point(body);await pinch(cdp,at.x,at.y,2.4);await wait(95);const after=await read(page),next=after.symbols.find(x=>x.body_id==='MARS'),drift=Math.hypot(point(next).x-at.x,point(next).y-at.y),ratio=after.camera.distance_km/before.camera.distance_km;assert(ratio>=1/3-.001&&ratio<1,'each pinch must zoom in by no more than the per-gesture bound');assert(drift<16,`selected Mars focal drift ${drift} CSS px`);steps.push({distance_km:after.camera.distance_km,ratio,mars_anchor_drift_css_px:drift});
    if(i===0){const expected=Math.exp(-.82*(Math.log(2.4)-Math.log(1+6/80)));assert(Math.abs(ratio-expected)<.02,'alternating pointer events must apply the absolute damped pinch ratio only once');}
    if(!fine&&after.solar.levels.some(level=>level>2)&&after.lines.some(x=>x.node_id==='solar'&&x.level>2&&x.clip_vertices>0)){const pixels=await page.evaluate(()=>window.__solarBasemapReadPixels());fine={step:i,levels:after.solar.levels,draw_list:after.solar.draws.filter(x=>x.level>2),projected_lines:after.lines.filter(x=>x.node_id==='solar'&&x.level>2&&x.clip_vertices>0),lit_pixels:pixels.lit_pixels};}
    const parent=after.lines.find(x=>x.feature_id==='MARS'&&x.node_id==='solar'&&x.clip_vertices>0&&x.presentation_context==='LOCAL_PARENT_ARC'),phobos=after.lines.find(x=>x.feature_id==='PHOBOS'&&x.clip_vertices>0),deimos=after.lines.find(x=>x.feature_id==='DEIMOS'&&x.clip_vertices>0),labels=new Set(after.presentation.labels.map(x=>x.body_id)),symbols=new Set(after.symbols.map(x=>x.body_id));if(parent&&phobos&&deimos&&['MARS','PHOBOS','DEIMOS'].every(id=>labels.has(id)&&symbols.has(id))){complete={state:after,parent,phobos,deimos};break;}}
  assert(fine?.draw_list.length&&fine.projected_lines.length&&fine.lit_pixels>0,'fine Solar LOD must reach draw list, projected geometry and rendered pixels');assert(complete,'ordinary touch path must reach Mars parent context and both moon curves');const settled=complete.state;assert.equal(settled.selected_body_id,'MARS');assert(settled.presentation.selection_visible,'Mars remains visibly selected');assert(complete.parent.opacity<complete.phobos.opacity&&complete.parent.opacity<complete.deimos.opacity,'parent orbit must be subordinate to local orbits');
  const pixels=await page.evaluate(()=>window.__solarBasemapReadPixels());assert(pixels.lit_pixels>0,'local geometry must contribute rendered pixels');const trace=await page.evaluate(()=>window.__marsPilotTrace);assert(trace.some(x=>x.level>2&&x.drawLevels.includes(x.level)&&x.errorCssPx<=.75),'fine Solar level must draw within the fixed refinement bound');assert(!trace.some(x=>x.errorCssPx>.75&&!x.drawLevels.some(l=>l>2)),'coarse Solar representation must not exceed the bound before fine draw');
  const projection=915/(2*Math.tan(Math.PI/8)*settled.camera.distance_km),shown=Number(settled.presentation.scale.match(/≈ ([\d,]+(?:\.[\d]+)?) km/)[1].replaceAll(',',''));assert(Math.abs(shown*projection-1)<.01,'scale readout must match the center camera projection');assert(Math.abs(settled.presentation.scale_bar_width_css_px-settled.presentation.scale_bar_km*projection)<2,'scale bar must match its labeled distance');
  const orientationBefore=await read(page),orientationPoint=point(orientationBefore.symbols.find(x=>x.body_id==='MARS'));await touch(cdp,'touchStart',[[orientationPoint.x-48,orientationPoint.y,21],[orientationPoint.x+48,orientationPoint.y,22]]);await touch(cdp,'touchMove',[[orientationPoint.x-18,orientationPoint.y+70,21],[orientationPoint.x+78,orientationPoint.y+70,22]]);await touch(cdp,'touchEnd',[]);await wait(180);const oriented=await read(page);assert(Math.abs(oriented.camera.rotation[0]-orientationBefore.camera.rotation[0])>.05,'two-finger orientation must change yaw');assert(Math.abs(oriented.camera.rotation[1]-orientationBefore.camera.rotation[1])>.05,'two-finger orientation must change pitch');assert.equal(oriented.camera.distance_km,orientationBefore.camera.distance_km,'orientation must not trigger pinch zoom');await page.screenshot({path:path.join(evidence,'solar-basemap-pixel-repair-mars-oblique.png')});
  const report=await page.evaluate(()=>window.__solarBasemapReport());assert.equal(report.catalog,110,'every governed catalog identity must remain inspectable');assert(!report.curves.some(x=>x.anchor_id==='JUPITER'&&x.semantic==='PARENT_RELATIVE_REFERENCE_ORBIT'),'product has no Jupiter moon reference curves');assert(!oriented.product_local_nodes.includes('system:JUPITER'),'product has no Jupiter local node');for(const id of ['IO','EUROPA','GANYMEDE','CALLISTO']){const f=report.features.find(x=>x.body_id===id);assert(f?.geometry_status==='NOT_REQUESTED'&&f.renderer?.presentation_reason==='LOCAL_GEOMETRY_NOT_REQUESTED',`${id} must retain a truthful product-content reason`);}assert.equal(requests.filter(url=>/authority|resolver|ephemeris|state-api/i.test(url)).length,0,'viewer must make no authority API calls');assert.deepEqual(errors,[],'browser must have no page errors');
  const result={schema:'loom.solar-basemap.pixel-repair-acceptance/0.1',method:'CDP touch events on public viewer canvas; read-only diagnostics only',viewport:{width:412,height:915,dpr:3},product_build_id:oriented.build_id,product_local_nodes:oriented.product_local_nodes,jupiter_product_limitation:{system_node:false,local_reference_curves:false},focus,one_finger_pan:{target_before:initialTarget,target_after:panned.camera.target_km,rotation_unchanged:true},pinch:{deadband_distance_unchanged:true,steps,max_focal_drift_css_px:Math.max(...steps.map(x=>x.mars_anchor_drift_css_px)),distance_before_km:centered.camera.distance_km,distance_after_km:settled.camera.distance_km},orientation:{before:orientationBefore.camera.rotation,after:oriented.camera.rotation,distance_unchanged:true},fine_solar_lod:{...fine,max_coarse_error_css_px:Math.max(0,...trace.filter(x=>!x.drawLevels.some(l=>l>2)).map(x=>x.errorCssPx)),frame_samples:trace.length},mars_context:{selected_body_id:settled.selected_body_id,parent:complete.parent,phobos:complete.phobos,deimos:complete.deimos,label:settled.presentation.labels.find(x=>x.body_id==='MARS'),scale:settled.presentation.scale,scale_bar_km:settled.presentation.scale_bar_km,lit_pixels:pixels.lit_pixels},presentation:{sun_symbol:symbolKinds.SUN,planet_symbol:symbolKinds.EARTH,minor_symbol:overview.symbols.find(x=>x.kind==='minor'),heliocentric_orbit_color:overview.lines.find(x=>x.node_id==='solar')?.color,local_orbit_color:complete.phobos.color,details_collapsed_by_default:await page.locator('#details').evaluate(el=>!el.open)},authority_calls:0,page_errors:errors};const out=path.join(evidence,'solar-basemap-pixel-repair-acceptance.json');fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify({evidence:out,selected_bodies:focus.map(x=>x.body_id),pinches:steps.length,distance_km:settled.camera.distance_km,yaw_pitch:oriented.camera.rotation,local_context:[complete.parent.feature_id,complete.phobos.feature_id,complete.deimos.feature_id],authority_calls:0}));await page.close();
 }finally{await browser.close();}}
main().catch(error=>{console.error(error);process.exitCode=1});
