#!/usr/bin/env node
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('/home/ubuntu/LOOM_SOLAR_INSPECTOR/node_modules/playwright');
const args=process.argv.slice(2);function option(name,def){const i=args.indexOf(name);return i>=0?args[i+1]:def;}
const profile=option('--profile','pixel'),delivery=option('--delivery','progressive'),trialIndex=option('--trial-index',null),marsOnly=args.includes('--mars-only'),base=process.env.SOLAR_BASEMAP_URL||'http://127.0.0.1:8770';
if(!['pixel','desktop'].includes(profile)||!['progressive','monolithic'].includes(delivery))throw Error('invalid profile/delivery');
const trialIds=trialIndex===null?[0,1,2,3,4]:[Number(trialIndex)];if(trialIds.some(x=>!Number.isInteger(x)||x<0||x>4))throw Error('trial index must be 0..4');
const evidence=process.env.SOLAR_BASEMAP_EVIDENCE||'/tmp/solar-basemap-browser';fs.mkdirSync(evidence,{recursive:true});
const width=profile==='pixel'?412:1280,height=profile==='pixel'?915:800,dpr=profile==='pixel'?3:1,AU=149597870.7;
function compactScene(s){return s?{...s,lines:(s.lines||[]).map(({float32Input,cameraRelativeKm,...line})=>line)}:null;}
function compactReconcile(r){return {...r,renderer_lines:(r.renderer_lines||[]).map(({float32Input,cameraRelativeKm,...line})=>line)};}
async function main(){
 const browser=await chromium.launch({headless:true});const trials=[];
 try{
  for(const throttled of (marsOnly?[false]:[false,true]))for(const n of trialIds){
   const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:dpr,hasTouch:profile==='pixel'});const page=await context.newPage();const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');
   if(throttled)await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:80,downloadThroughput:10*1024*1024/8,uploadThroughput:2*1024*1024/8,connectionType:'cellular3g'});
   if(throttled)await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});
   const productRequests=[],allRequests=[];page.on('request',r=>{allRequests.push(r.url());if(r.url().includes('/product/'))productRequests.push({url:r.url(),time:Date.now()})});
   const consoleErrors=[];page.on('pageerror',e=>consoleErrors.push(String(e)));
   const t0=Date.now();await page.goto(`${base}${base.includes('?')?'&':'?'}delivery=${delivery}`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__solarBasemapReady||window.__solarBasemapError,{timeout:120000});
   if(await page.evaluate(()=>!!window.__solarBasemapError))throw Error(await page.evaluate(()=>window.__solarBasemapError));
   await page.waitForFunction(()=>window.__solarBasemapScene&&window.__solarBasemapScene.markers>0&&window.__solarBasemapScene.lines.length>0,{timeout:30000});
   const usefulMs=Date.now()-t0;const initial=await page.evaluate(()=>({scene:(()=>{const s=window.__solarBasemapScene;return s?{...s,lines:s.lines.map(({float32Input,cameraRelativeKm,...line})=>line)}:null})(),heap:performance.memory?{used_js_heap_bytes:performance.memory.usedJSHeapSize,total_js_heap_bytes:performance.memory.totalJSHeapSize,heap_limit_bytes:performance.memory.jsHeapSizeLimit}:null,report:window.__solarBasemapReport(),root_uri:window.__solarBasemap.manifest.root.uri,selection:window.__solarBasemap.selection(),product:performance.getEntriesByType('resource').filter(x=>x.name.includes('/product/')).map(x=>({name:x.name,transfer:x.transferSize,encoded:x.encodedBodySize,decoded:x.decodedBodySize,duration:x.duration})),shell:performance.getEntriesByType('resource').filter(x=>!x.name.includes('/product/')&&x.name.startsWith(location.origin)).map(x=>({name:x.name.replace(location.origin,''),transfer:x.transferSize,encoded:x.encodedBodySize,decoded:x.decodedBodySize,duration:x.duration}))}));
   if(delivery==='progressive'){
     const currentUrl=`${base}/product/current.json?delivery=${delivery}`,rootUrl=`${base}/product/${initial.root_uri}`;
     const requestedUrls=productRequests.map(x=>x.url);
     assert(requestedUrls.includes(currentUrl),'progressive path must fetch the current manifest pointer');assert(requestedUrls.includes(rootUrl),'progressive path must fetch the immutable root');
     const allowedResources=new Set(initial.selection.flatMap(x=>[x.resource?.uri,x.prefetch?.resource?.uri]).filter(Boolean).map(uri=>`${base}/product/${uri}`));
     const additional=requestedUrls.filter(url=>url!==currentUrl&&url!==rootUrl);assert(additional.every(url=>allowedResources.has(url)),'startup may fetch only selected or policy-prefetched immutable levels');
     const bootstrapBytes=initial.product.filter(x=>x.name===currentUrl||x.name===rootUrl).reduce((s,x)=>s+x.encoded,0);
     assert(bootstrapBytes<=49920,`progressive manifest+root gzip bytes ${bootstrapBytes} must meet the 49,920-byte coarse-context budget`);
     assert(initial.report.root_embedded_budget.max_css_px<=.75,'per-curve Solar root LOD must meet its fixed 0.75 CSS px error bound');
   }else assert.equal(productRequests.length,1,'monolithic control must be one product response');
   const rasterCheck=n===0&&!throttled;
   const overviewPaths=marsOnly?[]:await page.evaluate(async collect=>{const ids=window.__solarBasemapReport().curves.filter(x=>x.semantic==='HELIOCENTRIC_REFERENCE_ORBIT'&&window.__solarBasemap.inspect(x.feature_id).body_class==='PLANET').map(x=>x.feature_id),out=[];for(const id of ids){if(collect){LoomRenderer.isolate(id);await new Promise(requestAnimationFrame);}const report=window.__solarBasemapReport();out.push({feature_id:id,pixels:collect?window.__solarBasemapReadPixels():null,drawn:report.scene?.lines?.filter(x=>x.feature_id===id).map(x=>({status:x.status,clip_vertices:x.clip_vertices,vertices:x.vertices}))||[]});}if(collect)LoomRenderer.isolate(null);return out;},rasterCheck);
   for(const path of overviewPaths){assert(path.drawn.length>0,`Sun anchored ${path.feature_id} must be submitted in Solar overview`);const projected=path.drawn.reduce((sum,line)=>sum+(line.clip_vertices||0),0);if(rasterCheck&&projected>0)assert(path.pixels.steel_line_pixels>0,`projected Sun anchored ${path.feature_id} vertices must contribute subdued Navigator orbital pixels: ${JSON.stringify(path)}`);}
   const cold={index:n,throttled,useful_ms:usefulMs,requests:productRequests.length,product_resources:initial.product,shell_requests:initial.shell,shell_request_count:initial.shell.length,scene:initial.scene,overview_paths:overviewPaths,cache:initial.report.cache,heap:initial.heap,gpu_buffer_bytes_estimate:initial.scene.gpu_buffer_bytes_estimate,transfer_bytes:initial.product.reduce((s,x)=>s+x.transfer,0)};
   async function cameraSequence(tag){
    const route=[],frame_intervals=[];let earth={report:null,isolatedPixels:null,lines:[]},earthReadyMs=null;
    if(!marsOnly){await page.evaluate(()=>LoomRenderer.state.raf.length=0);const tEarth=Date.now();route.push(await page.evaluate(()=>window.LoomRenderer.replayApproach('EARTH',50*149597870.7,1000000,60)));assert(route.at(-1).draw_frames>=route.at(-1).steps,'Earth camera approach must render every animation step');
    await page.waitForFunction(()=>window.__solarBasemapScene&&window.__solarBasemapScene.lines.some(x=>x.feature_id==='MOON'),{timeout:120000});earthReadyMs=Date.now()-tEarth;const earthFrames=await page.evaluate(()=>LoomRenderer.state.raf.splice(0));frame_intervals.push(...earthFrames);
    if(rasterCheck)await page.screenshot({path:path.join(evidence,`${profile}-${delivery}-${throttled?'throttled':'plain'}-${n}-${tag}-earth.png`)});
    earth=await page.evaluate(async collect=>{const lines=window.__solarBasemapScene?.lines?.filter(x=>x.feature_id==='MOON')||[];let isolatedPixels=null;if(collect){window.LoomRenderer.isolate('MOON');await new Promise(requestAnimationFrame);isolatedPixels=window.__solarBasemapReadPixels();window.LoomRenderer.isolate(null);await new Promise(requestAnimationFrame);}return {report:window.__solarBasemapReport(),isolatedPixels,lines};},rasterCheck);
    if(rasterCheck)assert(earth.isolatedPixels.steel_line_pixels>0,'Moon parent-relative reference curve must contribute subdued Navigator orbital pixels in Earth local context');}
    await page.evaluate(()=>LoomRenderer.state.raf.length=0);const tMars=Date.now();route.push(await page.evaluate(()=>window.LoomRenderer.replayApproach('MARS',50*149597870.7,100000,60)));assert(route.at(-1).draw_frames>=route.at(-1).steps,'Mars camera approach must render every animation step');
    await page.waitForFunction(()=>window.__solarBasemapScene&&window.__solarBasemapScene.lines.some(x=>x.feature_id==='PHOBOS'),{timeout:120000});const marsReadyMs=Date.now()-tMars;const marsFrames=await page.evaluate(()=>LoomRenderer.state.raf.splice(0));frame_intervals.push(...marsFrames);
    if(rasterCheck)await page.screenshot({path:path.join(evidence,`${profile}-${delivery}-${throttled?'throttled':'plain'}-${n}-${tag}-mars.png`)});
    const mars=await page.evaluate(async collect=>{const inspect=async id=>{const lines=window.__solarBasemapScene?.lines?.filter(x=>x.feature_id===id)||[];if(!collect)return {pixels:null,lines};window.LoomRenderer.isolate(id);await new Promise(requestAnimationFrame);const pixels=window.__solarBasemapReadPixels();return {pixels,lines:window.__solarBasemapScene?.lines?.filter(x=>x.feature_id===id)||[]};};const phobos=await inspect('PHOBOS'),deimos=await inspect('DEIMOS');if(collect){window.LoomRenderer.isolate(null);await new Promise(requestAnimationFrame);}return {report:window.__solarBasemapReport(),pixels:collect?window.__solarBasemapReadPixels():null,isolatedPixels:phobos.pixels,deimosPixels:deimos.pixels,isolatedLines:phobos.lines,deimosLines:deimos.lines,reconcile:window.__solarBasemapReconcile()};},rasterCheck);
    if(rasterCheck){assert(mars.isolatedPixels.steel_line_pixels>0,'Phobos reference curve must contribute subdued Navigator orbital pixels when isolated');assert(mars.deimosPixels.steel_line_pixels>0,'Deimos reference curve must contribute subdued Navigator orbital pixels when isolated');}assert.equal(mars.reconcile.features.length,110,'every governed catalog identity must reconcile');assert(mars.report.error_budget.max_gpu_conversion_css_px<.25,'Float32 camera-relative conversion must stay below 0.25 CSS px');assert(mars.report.error_budget.total_css_px<=1,`settled Mars view geometry debt must stay within 1 CSS px: ${JSON.stringify(mars.report.error_budget)}`);
    if(marsOnly){const localNodes=[...new Set(mars.report.draw_list.map(x=>x.node_id).filter(x=>x.startsWith('system:')))].sort(),expectedMarsNode=await page.evaluate(()=>window.__solarBasemap.catalog().find(x=>x.body_id==='PHOBOS').node_id),plutoNode=await page.evaluate(()=>window.__solarBasemap.catalog().find(x=>x.body_id==='CHARON').node_id);assert(localNodes.includes(expectedMarsNode),'Mars pilot must select the governed parent node for Mars-local detail');assert(!localNodes.includes(plutoNode),'Mars pilot must not select deferred Pluto/Charon detail');}
    if(marsOnly)return {route,frame_intervals,earthReadyMs,earth:{selected:[],scene:null,isolated:earth.isolatedPixels,lines:earth.lines},marsReadyMs,plutoReadyMs:null,mars:{selected:mars.report.draw_list.filter(x=>['PHOBOS','DEIMOS'].includes(x.feature_id)),scene:compactScene(mars.report.scene),pixels:mars.pixels,isolated:mars.isolatedPixels,deimosPixels:mars.deimosPixels,reconcile:compactReconcile(mars.reconcile)},pluto:null,cache:mars.report.cache};
    await page.evaluate(()=>LoomRenderer.state.raf.length=0);const tPluto=Date.now();route.push(await page.evaluate(()=>{LoomRenderer.fit();return new Promise(resolve=>requestAnimationFrame(()=>resolve(LoomRenderer.replayApproach('PLUTO',50*149597870.7,250000,60))))}));assert(route.at(-1).draw_frames>=route.at(-1).steps,'Pluto camera approach must render every animation step');
    await page.waitForFunction(()=>window.__solarBasemapScene&&window.__solarBasemapScene.lines.some(x=>x.feature_id==='CHARON'),{timeout:120000});const plutoReadyMs=Date.now()-tPluto;const plutoFrames=await page.evaluate(()=>LoomRenderer.state.raf.splice(0));frame_intervals.push(...plutoFrames);
    if(rasterCheck)await page.screenshot({path:path.join(evidence,`${profile}-${delivery}-${throttled?'throttled':'plain'}-${n}-${tag}-pluto.png`)});
    const end=await page.evaluate(async collect=>{let isolatedPixels=null;if(collect){window.LoomRenderer.isolate('CHARON');await new Promise(requestAnimationFrame);isolatedPixels=window.__solarBasemapReadPixels();window.LoomRenderer.isolate(null);await new Promise(requestAnimationFrame);}return {report:window.__solarBasemapReport(),pixels:collect?window.__solarBasemapReadPixels():null,isolatedPixels,reconcile:window.__solarBasemapReconcile()};},rasterCheck);
    if(rasterCheck)assert(end.isolatedPixels.steel_line_pixels>0,'Charon reference curve must contribute subdued Navigator orbital pixels when isolated');assert.equal(end.reconcile.features.length,110,'every governed catalog identity must reconcile');assert(end.report.error_budget.max_gpu_conversion_css_px<.25,'Float32 camera-relative conversion must stay below 0.25 CSS px');assert(end.report.error_budget.total_css_px<=1,`settled Pluto view geometry debt must stay within 1 CSS px: ${JSON.stringify(end.report.error_budget)}`);
    return {route,frame_intervals,earthReadyMs,earth:{selected:earth.report.draw_list.filter(x=>x.feature_id==='MOON'),scene:compactScene(earth.report.scene),isolated:earth.isolatedPixels,lines:earth.lines},marsReadyMs,plutoReadyMs,mars:{selected:mars.report.draw_list.filter(x=>['PHOBOS','DEIMOS'].includes(x.feature_id)),scene:compactScene(mars.report.scene),pixels:mars.pixels,isolated:mars.isolatedPixels,deimosPixels:mars.deimosPixels,reconcile:compactReconcile(mars.reconcile)},
      pluto:{selected:end.report.draw_list.filter(x=>x.feature_id==='CHARON'),scene:compactScene(end.report.scene),pixels:end.pixels,isolated:end.isolatedPixels,reconcile:compactReconcile(end.reconcile)},cache:end.report.cache};
   }
   const coldPath=await cameraSequence('cold');
   // A same-context revisit after the selected route exercises retained HTTP/browser caches.
   await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__solarBasemapReady,{timeout:120000});await page.waitForTimeout(50);
   const before=productRequests.length;const warmPath=await cameraSequence('warm');
   let revisit=null;if(!marsOnly&&profile==='pixel'&&n===0&&!throttled){for(let i=0;i<10;i++){await page.evaluate(()=>LoomRenderer.replayApproach('MARS',50*149597870.7,100000,30));await page.waitForFunction(()=>window.__solarBasemapScene?.lines.some(x=>x.feature_id==='PHOBOS'),{timeout:30000});await page.evaluate(()=>LoomRenderer.fit());await page.evaluate(()=>LoomRenderer.replayApproach('PLUTO',50*149597870.7,250000,30));await page.waitForFunction(()=>window.__solarBasemapScene?.lines.some(x=>x.feature_id==='CHARON'),{timeout:30000});}revisit=await page.evaluate(()=>({cache:window.__solarBasemap.cacheStats(),frame:window.__solarBasemapScene.max_frame_interval_ms}));assert.equal(revisit.cache.memory_limit,false,'ten back/forth visits must stay within measured cache budget');}
   let interaction=null;if(n===0&&!throttled){
    await page.evaluate(()=>LoomRenderer.fit());await page.waitForTimeout(50);
    const before=await page.evaluate(()=>({distance:LoomRenderer.state.distance,target:[...LoomRenderer.state.target],rotation:[...LoomRenderer.state.rotation]}));
    await page.mouse.move(width/2,height/2);await page.mouse.wheel(0,-80);await page.waitForTimeout(80);
    const wheeled=await page.evaluate(()=>LoomRenderer.state.distance);assert(wheeled<before.distance,'wheel zoom must continuously change camera distance');
    await page.mouse.move(width/2,height/2);await page.mouse.down({button:'right'});await page.mouse.move(width/2+24,height/2+18,{steps:2});await page.mouse.up({button:'right'});
    const panned=await page.evaluate(()=>[...LoomRenderer.state.target]);assert.notDeepEqual(panned,before.target,'pan must continuously move the scene target');
    await page.mouse.move(width/2,height/2);await page.mouse.down({button:'left'});await page.mouse.move(width/2,height/2-100,{steps:3});await page.mouse.up({button:'left'});
    const rotated=await page.evaluate(()=>[...LoomRenderer.state.rotation]);assert.notDeepEqual(rotated,before.rotation,'drag rotation must continuously change camera orientation');
    let pinch=null;if(profile==='pixel'){
      const d0=await page.evaluate(()=>LoomRenderer.state.distance);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:width/2-50,y:height/2,radiusX:2,radiusY:2,force:1,id:1},{x:width/2+50,y:height/2,radiusX:2,radiusY:2,force:1,id:2}]});
      await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:width/2-90,y:height/2,radiusX:2,radiusY:2,force:1,id:1},{x:width/2+90,y:height/2,radiusX:2,radiusY:2,force:1,id:2}]});
      await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(80);pinch=await page.evaluate(()=>LoomRenderer.state.distance);assert(pinch<d0,'two-finger pinch must continuously change camera distance');
    }
    const final=await page.evaluate(()=>({scene:window.__solarBasemapScene,overflow:document.documentElement.scrollWidth>innerWidth,report:window.__solarBasemapReport()}));assert.equal(final.overflow,false,'viewport must not overflow horizontally');assert(final.scene.markers>0,'camera gestures must not create an empty-frame transition');interaction={before,wheeled,panned,rotated,pinch,overflow:final.overflow,visible_markers:final.scene.markers,edge_on_error:final.report.error_budget};
   }
   const memory=await page.evaluate(()=>({heap:performance.memory?{used_js_heap_bytes:performance.memory.usedJSHeapSize,total_js_heap_bytes:performance.memory.totalJSHeapSize,heap_limit_bytes:performance.memory.jsHeapSizeLimit}:null,scene:window.__solarBasemapScene?{gpu_geometry_count:window.__solarBasemapScene.gpu_geometry_count,gpu_buffer_bytes_estimate:window.__solarBasemapScene.gpu_buffer_bytes_estimate}:null,cache:window.__solarBasemap.cacheStats()}));
   const warmResources=await page.evaluate(()=>performance.getEntriesByType('resource').filter(x=>x.name.includes('/product/')).map(x=>({name:x.name,transfer:x.transferSize,encoded:x.encodedBodySize,decoded:x.decodedBodySize,duration:x.duration})));
   assert.equal(allRequests.filter(x=>/authority|resolver|ephemeris|state-api/i.test(x)).length,0,'browser must never call authority/resolver/state APIs');
   const warm={index:n,throttled,cold_path:coldPath,warm_path:warmPath,interaction,memory,additional_requests:productRequests.length-before,resources:warmResources,
     immutable_chunk_transfer_bytes:warmResources.filter(x=>/\/objects\//.test(x.name)).reduce((s,x)=>s+x.transfer,0),revisit,
     diagnostics:{catalog:warmPath.catalog,authority_calls:allRequests.filter(x=>/authority|resolver|ephemeris|state-api/i.test(x)).length,console_errors:consoleErrors}};assert.equal(warm.immutable_chunk_transfer_bytes,0,'warm visit must not redownload immutable product chunks');
   trials.push({profile,delivery,cold,warm});
   await context.close();
   fs.writeFileSync(path.join(evidence,`${profile}-${delivery}-partial.json`),JSON.stringify({profile,delivery,trials},null,2));
  }
 } finally {await browser.close();}
 const series=(key)=>trials.map(t=>key(t)).filter(Number.isFinite).sort((a,b)=>a-b);const stats=a=>a.length?({n:a.length,median:a[(a.length-1)>>1],p95:a[Math.ceil(a.length*.95)-1],max:a[a.length-1],values:a}):({n:0,values:[]});
 const result={schema:'loom.solar-basemap.browser-evidence/0.1',profile,delivery,pilot_scope:marsOnly?'MARS_ONLY':'FULL_SOLAR',product_build_id:trials[0]?.warm?.warm_path?.mars?.reconcile?.build_id||null,viewport:{width,height,dpr,render_dpr_cap:2},network_profiles:marsOnly?['unthrottled']:['unthrottled','10Mbps_80ms_cpu4'],trials,
   summary:{cold_useful_ms_plain:stats(series(t=>t.cold.throttled?NaN:t.cold.useful_ms)),cold_useful_ms_throttled:stats(series(t=>t.cold.throttled?t.cold.useful_ms:NaN)),
   warm_product_requests:stats(series(t=>t.warm.additional_requests)),frame_samples_plain:stats(trials.filter(t=>!t.cold.throttled).flatMap(t=>t.warm.warm_path.frame_intervals||[]).sort((a,b)=>a-b)),
   frame_samples_throttled:stats(trials.filter(t=>t.cold.throttled).flatMap(t=>t.warm.warm_path.frame_intervals||[]).sort((a,b)=>a-b)),trial_max_frame_interval_plain:stats(series(t=>t.cold.throttled?NaN:Math.max(0,...(t.warm.warm_path.frame_intervals||[])))),trial_max_frame_interval_throttled:stats(series(t=>t.cold.throttled?Math.max(0,...(t.warm.warm_path.frame_intervals||[])):NaN))}};
 const target=path.join(evidence,`${profile}-${delivery}${trialIndex===null?'':`-trial-${trialIndex}`}.json`);fs.writeFileSync(target,JSON.stringify(result,null,2));console.log(JSON.stringify({evidence:target,trials:trials.length,summary:result.summary}));
}
main().catch(e=>{console.error(e);process.exitCode=1});
