-- Solar ET authority: generated by tools/build_solar_et_coverage.py.
-- Source: pinned SPK target windows; historical UTC labels only narrow prior qualifications.
-- Overlay SHA256: ace8df81c7ddbb3657e43bd3d3ad7b5eed07ccbb3a3714df3902be7a06da7820
BEGIN;
ALTER TABLE loom_solar.ephemeris_coverage
    ADD COLUMN coverage_start_et double precision,
    ADD COLUMN coverage_end_et double precision;

DO $migration$
DECLARE updated_count integer;
BEGIN
    IF (SELECT count(*) FROM loom_solar.ephemeris_coverage) <> 123 OR
       (SELECT count(*) FROM loom_solar.ephemeris_coverage WHERE status='QUALIFIED') <> 121 THEN
        RAISE EXCEPTION 'Solar ET migration ledger preimage differs';
    END IF;
    WITH evidence(ephemeris_source_id,body_id,valid_from,valid_until,status,et_start,et_end) AS (
      VALUES
    ('CERES_SPK_2025_2227', 'CERES', '2024-12-31T23:58:50.816+00:00'::timestamptz, '2226-12-31T23:58:50.816+00:00'::timestamptz, 'RETIRED', 788961600.0::double precision, 7163380800.0::double precision),
    ('CERES_SPK_PHASE4B_2251', 'CERES', '2024-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-02T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 788961600.0::double precision, 7920936000.0::double precision),
    ('DE440', 'EARTH', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('DE440', 'EARTH_MOON_BARYCENTER', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('DE440', 'JUPITER_SYSTEM_BARYCENTER', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('DE440', 'MARS_SYSTEM_BARYCENTER', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('DE440', 'MERCURY', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('DE440', 'MERCURY_SYSTEM_BARYCENTER', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('DE440', 'MOON', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('DE440', 'NEPTUNE_SYSTEM_BARYCENTER', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('DE440', 'PLUTO_SYSTEM_BARYCENTER', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('DE440', 'SATURN_SYSTEM_BARYCENTER', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('DE440', 'SUN', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('DE440', 'URANUS_SYSTEM_BARYCENTER', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('DE440', 'VENUS', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('DE440', 'VENUS_SYSTEM_BARYCENTER', '1549-12-30T23:59:18.815889+00:00'::timestamptz, '2650-01-24T23:58:50.815708+00:00'::timestamptz, 'QUALIFIED', -14200747200.0::double precision, 20514081600.0::double precision),
    ('HORIZONS_4E_APOPHIS', 'APOPHIS', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_ARROKOTH', 'ARROKOTH', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_ATLAS3I', 'ATLAS3I', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_BORISOV', 'BORISOV', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_BORRELLY', 'BORRELLY', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_BRAILLE', 'BRAILLE', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_DAVIDA', 'DAVIDA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_DINKINESH', 'DINKINESH', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_DONALDJOHANSON', 'DONALDJOHANSON', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_GASPRA', 'GASPRA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_GONGGONG', 'GONGGONG', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_HARTLEY2', 'HARTLEY2', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_IDA', 'IDA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_INTERAMNIA', 'INTERAMNIA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_IXION', 'IXION', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_JUNO', 'JUNO', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_LEUCUS', 'LEUCUS', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_LUTETIA', 'LUTETIA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_MATHILDE', 'MATHILDE', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_MS4', 'MS4', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_ORCUS', 'ORCUS', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_ORUS', 'ORUS', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_OUMUAMUA', 'OUMUAMUA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_POLYMELE', 'POLYMELE', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_QUAOAR', 'QUAOAR', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_SALACIA', 'SALACIA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_SEDNA', 'SEDNA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_STEINS', 'STEINS', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_SWIFTTUTTLE', 'SWIFTTUTTLE', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_TEMPEL1', 'TEMPEL1', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_THEMIS', 'THEMIS', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_TOUTATIS', 'TOUTATIS', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_VARUNA', 'VARUNA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('HORIZONS_4E_WILD2', 'WILD2', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_BENNU_SB441', 'BENNU', '1899-12-31T23:59:18.816+00:00'::timestamptz, '2135-09-30T23:58:50.818+00:00'::timestamptz, 'QUALIFIED', -3155716800.0::double precision, 4283755200.0::double precision),
    ('JPL_HORIZONS_6178', 'ASTEROID_6178', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_67P', 'COMET_67P', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_AMU', 'AMUN', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_CHI', 'CHIRON', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_DID', 'DIDYMOS', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_ERIS', 'ERIS', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_EROS', 'EROS', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_EUR', 'EURYBATES', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_HALLEY', 'COMET_HALLEY', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_HAU', 'HAUMEA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_HYG', 'HYGIEA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_ITO', 'ITOKAWA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_KLE', 'KLEOPATRA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_MAK', 'MAKEMAKE', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_PAL', 'PALLAS', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_PAT', 'PATROCLUS', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_PSY', 'PSYCHE', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_RYU', 'RYUGU', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_HORIZONS_VES', 'VESTA', '2025-12-31T23:58:50.816+00:00'::timestamptz, '2251-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', 820497600.0::double precision, 7920849600.0::double precision),
    ('JPL_JUP365_PRE2250', 'CALLISTO', '1600-01-09T23:59:18.816+00:00'::timestamptz, '2200-01-09T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -12622046400.0::double precision, 6312168000.0::double precision),
    ('JPL_JUP365_PRE2250', 'EUROPA', '1600-01-09T23:59:18.816+00:00'::timestamptz, '2200-01-09T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -12622046400.0::double precision, 6312168000.0::double precision),
    ('JPL_JUP365_PRE2250', 'GANYMEDE', '1600-01-09T23:59:18.816+00:00'::timestamptz, '2200-01-09T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -12622046400.0::double precision, 6312168000.0::double precision),
    ('JPL_JUP365_PRE2250', 'IO', '1600-01-09T23:59:18.816+00:00'::timestamptz, '2200-01-09T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -12622046400.0::double precision, 6312168000.0::double precision),
    ('JPL_JUP365_PRE2250', 'JUPITER', '1600-01-09T23:59:18.816+00:00'::timestamptz, '2200-01-09T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -12622046400.0::double precision, 6312168000.0::double precision),
    ('JPL_MAR099', 'DEIMOS', '1599-12-31T23:59:18.816+00:00'::timestamptz, '2600-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -12622824000.0::double precision, 18934257600.0::double precision),
    ('JPL_MAR099', 'MARS', '1599-12-31T23:59:18.815889+00:00'::timestamptz, '2600-01-01T23:58:50.816341+00:00'::timestamptz, 'QUALIFIED', -12622824000.0::double precision, 18934257600.0::double precision),
    ('JPL_MAR099', 'PHOBOS', '1599-12-31T23:59:18.816+00:00'::timestamptz, '2600-01-01T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -12622824000.0::double precision, 18934257600.0::double precision),
    ('JPL_NEP097', 'NEPTUNE', '1600-01-09T23:59:18.81563+00:00'::timestamptz, '2399-12-30T23:58:50.816313+00:00'::timestamptz, 'QUALIFIED', -12622046400.0::double precision, 12622651200.0::double precision),
    ('JPL_NEP097', 'TRITON', '1600-01-09T23:59:18.816+00:00'::timestamptz, '2399-12-30T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -12622046400.0::double precision, 12622651200.0::double precision),
    ('JPL_PLU060_PRE2250', 'CHARON', '1800-01-01T23:59:18.816+00:00'::timestamptz, '2199-12-29T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -6311304000.0::double precision, 6311217600.0::double precision),
    ('JPL_PLU060_PRE2250', 'PLUTO', '1800-01-01T23:59:18.816+00:00'::timestamptz, '2199-12-29T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -6311304000.0::double precision, 6311217600.0::double precision),
    ('JPL_SAT441', 'SATURN', '1749-12-29T23:59:18.816003+00:00'::timestamptz, '2250-01-05T23:58:50.816055+00:00'::timestamptz, 'RETIRED', -7889400000.0::double precision, 7889659200.0::double precision),
    ('JPL_SAT441XL_PART2', 'DIONE', '2014-09-27T23:58:52.818+00:00'::timestamptz, '4500-01-17T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', 465134400.0::double precision, 78893870400.0::double precision),
    ('JPL_SAT441XL_PART2', 'ENCELADUS', '2014-09-27T23:58:52.818+00:00'::timestamptz, '4500-01-17T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', 465134400.0::double precision, 78893870400.0::double precision),
    ('JPL_SAT441XL_PART2', 'HYPERION', '2014-09-27T23:58:52.818+00:00'::timestamptz, '4500-01-17T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', 465134400.0::double precision, 78893870400.0::double precision),
    ('JPL_SAT441XL_PART2', 'IAPETUS', '2014-09-27T23:58:52.818+00:00'::timestamptz, '4500-01-17T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', 465134400.0::double precision, 78893870400.0::double precision),
    ('JPL_SAT441XL_PART2', 'MIMAS', '2014-09-27T23:58:52.818+00:00'::timestamptz, '4500-01-17T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', 465134400.0::double precision, 78893870400.0::double precision),
    ('JPL_SAT441XL_PART2', 'PHOEBE', '2014-09-27T23:58:52.818+00:00'::timestamptz, '4500-01-17T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', 465134400.0::double precision, 78893870400.0::double precision),
    ('JPL_SAT441XL_PART2', 'RHEA', '2014-09-27T23:58:52.818+00:00'::timestamptz, '4500-01-17T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', 465134400.0::double precision, 78893870400.0::double precision),
    ('JPL_SAT441XL_PART2', 'SATURN', '2014-09-27T23:58:52.818+00:00'::timestamptz, '4500-01-17T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', 465134400.0::double precision, 78893870400.0::double precision),
    ('JPL_SAT441XL_PART2', 'TETHYS', '2014-09-27T23:58:52.818+00:00'::timestamptz, '4500-01-17T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', 465134400.0::double precision, 78893870400.0::double precision),
    ('JPL_SAT441XL_PART2', 'TITAN', '2014-09-27T23:58:52.818+00:00'::timestamptz, '4500-01-17T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', 465134400.0::double precision, 78893870400.0::double precision),
    ('JPL_URA184_PART_3', 'ARIEL', '1600-01-03T23:59:18.816+00:00'::timestamptz, '2399-12-16T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', -12622564800.0::double precision, 12621441600.0::double precision),
    ('JPL_URA184_PART_3', 'MIRANDA', '1600-01-03T23:59:18.816+00:00'::timestamptz, '2399-12-16T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', -12622564800.0::double precision, 12621441600.0::double precision),
    ('JPL_URA184_PART_3', 'OBERON', '1600-01-03T23:59:18.816+00:00'::timestamptz, '2399-12-16T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', -12622564800.0::double precision, 12621441600.0::double precision),
    ('JPL_URA184_PART_3', 'TITANIA', '1600-01-03T23:59:18.816+00:00'::timestamptz, '2399-12-16T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', -12622564800.0::double precision, 12621441600.0::double precision),
    ('JPL_URA184_PART_3', 'UMBRIEL', '1600-01-03T23:59:18.816+00:00'::timestamptz, '2399-12-16T23:58:50.817+00:00'::timestamptz, 'QUALIFIED', -12622564800.0::double precision, 12621441600.0::double precision),
    ('JPL_URA184_PART_3', 'URANUS', '1600-01-03T23:59:18.815802+00:00'::timestamptz, '2399-12-16T23:58:50.816698+00:00'::timestamptz, 'QUALIFIED', -12622564800.0::double precision, 12621441600.0::double precision),
    ('NAIF_NEP098_808', 'PROTEUS', '1799-12-31T23:59:18.816+00:00'::timestamptz, '2199-12-30T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -6311390400.0::double precision, 6311304000.0::double precision),
    ('NAIF_NEP101XL_802', 'NEREID', '2026-01-01T00:00:00+00:00'::timestamptz, '2251-01-01T00:00:00+00:00'::timestamptz, 'QUALIFIED', 820497669.18392::double precision, 7920763269.183792::double precision),
    ('NAIF_NH_OD164', 'NEWHORIZONS', '2019-01-01T05:34:32+00:00'::timestamptz, '2033-01-01T11:58:51+00:00'::timestamptz, 'QUALIFIED', 599592941.1839215::double precision, 1041465600.0::double precision),
    ('NAIF_PIONEER10_SPK', 'PIONEER10', '1972-03-03T02:04:00+00:00'::timestamptz, '1990-01-02T00:00:00+00:00'::timestamptz, 'QUALIFIED', -878291717.8145751::double precision, -315489542.816041::double precision),
    ('NAIF_PIONEER11_SPK', 'PIONEER11', '1973-04-06T02:25:00+00:00'::timestamptz, '1990-01-02T00:00:00+00:00'::timestamptz, 'QUALIFIED', -843816855.8143449::double precision, -315489542.816041::double precision),
    ('NAIF_PLU060_4E', 'HYDRA', '1800-01-01T23:59:18.816+00:00'::timestamptz, '2199-12-29T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -6311304000.0::double precision, 6311217600.0::double precision),
    ('NAIF_PLU060_4E', 'KERBEROS', '1800-01-01T23:59:18.816+00:00'::timestamptz, '2199-12-29T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -6311304000.0::double precision, 6311217600.0::double precision),
    ('NAIF_PLU060_4E', 'NIX', '1800-01-01T23:59:18.816+00:00'::timestamptz, '2199-12-29T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -6311304000.0::double precision, 6311217600.0::double precision),
    ('NAIF_PLU060_4E', 'STYX', '1800-01-01T23:59:18.816+00:00'::timestamptz, '2199-12-29T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -6311304000.0::double precision, 6311217600.0::double precision),
    ('NAIF_VOYAGER1_SPK', 'VOYAGER1', '1980-12-31T23:59:08.816+00:00'::timestamptz, '2099-12-31T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -599572800.0::double precision, 3155716800.0::double precision),
    ('NAIF_VOYAGER2_SPK', 'VOYAGER2', '1989-08-29T07:59:03.817+00:00'::timestamptz, '2099-12-31T23:58:50.816+00:00'::timestamptz, 'QUALIFIED', -326347200.0::double precision, 3155716800.0::double precision),
    ('PROP_4E_NEWHORIZONS', 'NEWHORIZONS', '2033-01-01T00:00:00+00:00'::timestamptz, '2251-01-01T00:00:00+00:00'::timestamptz, 'QUALIFIED', 1041422469.1839253::double precision, 7920763269.183792::double precision),
    ('PROP_4E_PIONEER10', 'PIONEER10', '2026-01-01T00:00:00+00:00'::timestamptz, '2251-01-01T00:00:00+00:00'::timestamptz, 'QUALIFIED', 820497669.18392::double precision, 7920763269.183792::double precision),
    ('PROP_4E_PIONEER11', 'PIONEER11', '2026-01-01T00:00:00+00:00'::timestamptz, '2251-01-01T00:00:00+00:00'::timestamptz, 'QUALIFIED', 820497669.18392::double precision, 7920763269.183792::double precision),
    ('PROP_4E_VOYAGER1', 'VOYAGER1', '2026-01-01T00:00:00+00:00'::timestamptz, '2251-01-01T00:00:00+00:00'::timestamptz, 'QUALIFIED', 3155713269.1838837::double precision, 7920763269.183792::double precision),
    ('PROP_4E_VOYAGER2', 'VOYAGER2', '2026-01-01T00:00:00+00:00'::timestamptz, '2251-01-01T00:00:00+00:00'::timestamptz, 'QUALIFIED', 3155713269.1838837::double precision, 7920763269.183792::double precision),
    ('PROP_BENNU_2101955_PHASE4D', 'BENNU', '2026-01-01T00:00:00+00:00'::timestamptz, '2251-01-01T00:01:00+00:00'::timestamptz, 'QUALIFIED', 820497669.18392::double precision, 7920763329.183792::double precision),
    ('PROP_CALLISTO_504_PHASE4B', 'CALLISTO', '2200-01-09T23:58:50.816+00:00'::timestamptz, '2251-01-01T00:00:00.816+00:00'::timestamptz, 'QUALIFIED', 6312168000.0::double precision, 7920763270.0::double precision),
    ('PROP_CHARON_901_PHASE4B', 'CHARON', '2199-12-29T23:58:50.816+00:00'::timestamptz, '2251-01-01T00:00:00.816+00:00'::timestamptz, 'QUALIFIED', 6311217600.0::double precision, 7920763270.0::double precision),
    ('PROP_EUROPA_502_PHASE4B', 'EUROPA', '2200-01-09T23:58:50.816+00:00'::timestamptz, '2251-01-01T00:00:00.816+00:00'::timestamptz, 'QUALIFIED', 6312168000.0::double precision, 7920763270.0::double precision),
    ('PROP_GANYMEDE_503_PHASE4B', 'GANYMEDE', '2200-01-09T23:58:50.816+00:00'::timestamptz, '2251-01-01T00:00:00.816+00:00'::timestamptz, 'QUALIFIED', 6312168000.0::double precision, 7920763270.0::double precision),
    ('PROP_IO_501_PHASE4B', 'IO', '2200-01-09T23:58:50.816+00:00'::timestamptz, '2251-01-01T00:00:00.816+00:00'::timestamptz, 'QUALIFIED', 6312168000.0::double precision, 7920763270.0::double precision),
    ('PROP_JUPITER_599_PHASE4B', 'JUPITER', '2200-01-09T23:58:50.816+00:00'::timestamptz, '2251-01-01T00:00:00.816+00:00'::timestamptz, 'QUALIFIED', 6312168000.0::double precision, 7920763270.0::double precision),
    ('PROP_PLUTO_999_PHASE4B', 'PLUTO', '2199-12-29T23:58:50.816+00:00'::timestamptz, '2251-01-01T00:00:00.816+00:00'::timestamptz, 'QUALIFIED', 6311217600.0::double precision, 7920763270.0::double precision)
    )
    UPDATE loom_solar.ephemeris_coverage c
       SET coverage_start_et=e.et_start, coverage_end_et=e.et_end
      FROM evidence e
     WHERE c.ephemeris_source_id=e.ephemeris_source_id
       AND c.body_id IS NOT DISTINCT FROM e.body_id
       AND c.valid_from=e.valid_from AND c.valid_until=e.valid_until AND c.status=e.status;
    GET DIAGNOSTICS updated_count = ROW_COUNT;
    IF updated_count <> 123 THEN
        RAISE EXCEPTION 'Solar ET migration matched % of 123 rows', updated_count;
    END IF;
END $migration$;
ALTER TABLE loom_solar.ephemeris_coverage
    ALTER COLUMN coverage_start_et SET NOT NULL,
    ALTER COLUMN coverage_end_et SET NOT NULL,
    ADD CONSTRAINT solar_et_coverage_order CHECK (
      coverage_start_et > '-Infinity'::double precision
      AND coverage_end_et < 'Infinity'::double precision
      AND coverage_start_et < coverage_end_et);
CREATE INDEX ephemeris_coverage_body_et_idx
    ON loom_solar.ephemeris_coverage(body_id, coverage_start_et, coverage_end_et);
COMMIT;
