"""Generic cross-body ownership and promotion integrity checks."""
import json,sqlite3

def violations(db):
 c=sqlite3.connect(db);c.row_factory=sqlite3.Row;out=[]
 def add(code,rows):
  for r in rows:out.append({'code':code,'row':dict(r)})
 add('CAMPAIGN_BODY_MISMATCH',c.execute("SELECT assertion_id,body_id,campaign_id FROM promotion_assertion WHERE campaign_id='ARP-QUAL-02-EUROPA' AND body_id<>'EUROPA'"))
 add('EUROPA_IDENTITY_DUPLICATE',c.execute("SELECT body_id,count(*) n FROM body_authority WHERE authority_system='loom_solar.body' AND authority_identifier='EUROPA' GROUP BY body_id HAVING count(*)<>1"))
 add('EUROPA_IDENTITY_MISSING',c.execute("SELECT 'EUROPA' body_id WHERE (SELECT count(*) FROM body WHERE body_id='EUROPA')<>1 OR (SELECT count(*) FROM body_authority WHERE body_id='EUROPA' AND authority_system='loom_solar.body' AND authority_identifier='EUROPA')<>1"))
 add('FACT_REGION_CROSS_BODY',c.execute('SELECT f.fact_id,f.body_id,r.body_id region_body FROM fact f JOIN body_region r USING(region_id) WHERE f.body_id<>r.body_id'))
 add('OBSERVATION_REGION_CROSS_BODY',c.execute('SELECT o.observation_id,o.body_id,r.body_id region_body FROM observation o JOIN body_region r USING(region_id) WHERE o.body_id<>r.body_id'))
 add('MATERIAL_OBSERVATION_CROSS_BODY',c.execute('SELECT m.material_evidence_id,m.body_id,o.body_id observation_body FROM material_evidence m JOIN observation o USING(observation_id) WHERE m.body_id<>o.body_id'))
 add('MATERIAL_REGION_CROSS_BODY',c.execute('SELECT m.material_evidence_id,m.body_id,r.body_id region_body FROM material_evidence m JOIN body_region r USING(region_id) WHERE m.body_id<>r.body_id'))
 add('REGIONAL_MATERIAL_SCOPE_LOSS',c.execute("""SELECT m.material_evidence_id,m.body_id,p.assertion_id,p.scope_type FROM material_evidence m JOIN promotion_assertion p ON p.body_id=m.body_id AND p.source_id=m.source_id AND p.campaign_id='ARP-QUAL-02-EUROPA' JOIN promotion_review r USING(promotion_assertion_id) WHERE r.disposition='PROMOTE' AND p.scope_type='REGIONAL' AND m.region_id IS NULL"""))
 add('ACTIVITY_OBSERVATION_CROSS_BODY',c.execute('SELECT a.activity_id,a.body_id,o.body_id observation_body FROM activity_fact a JOIN observation o USING(observation_id) WHERE a.body_id<>o.body_id'))
 add('ACTIVITY_REGION_CROSS_BODY',c.execute('SELECT a.activity_id,a.body_id,r.body_id region_body FROM activity_fact a JOIN body_region r USING(region_id) WHERE a.body_id<>r.body_id'))
 add('MODEL_REGION_CROSS_BODY',c.execute('SELECT m.model_product_id,m.body_id,r.body_id region_body FROM body_model_product m JOIN body_region r USING(region_id) WHERE m.body_id<>r.body_id'))
 add('REGION_MODEL_CROSS_BODY',c.execute('SELECT x.region_id,r.body_id region_body,m.body_id model_body FROM region_model_product x JOIN body_region r USING(region_id) JOIN body_model_product m USING(model_product_id) WHERE r.body_id<>m.body_id'))
 add('FRONTIER_CAMPAIGN_LEAK',c.execute("SELECT frontier_id,campaign_id,variable FROM epistemic_frontier WHERE campaign_id='ARP-QUAL-02-EUROPA' AND variable LIKE '%CERES%' OR campaign_id='ARP-QUAL-02-EUROPA' AND variable LIKE '%67P%'"))
 add('EUROPA_UNKNOWN_VALUE',c.execute("SELECT fact_id,property_code,value_numeric,value_text FROM fact WHERE body_id='EUROPA' AND confidence_class='UNKNOWN' AND value_numeric=0"))
 add('PREFERRED_FACT_LEAK',c.execute('SELECT body_id,property_code,fact_id FROM preferred_fact'))
 add('CROSS_BODY_DERIVATION_LINEAGE',c.execute("""SELECT p.assertion_id,p.body_id,l.input_assertion_ids_json FROM promotion_lineage l JOIN promotion_assertion p USING(promotion_assertion_id) WHERE p.campaign_id='ARP-QUAL-02-EUROPA' AND EXISTS (SELECT 1 FROM promotion_assertion other WHERE other.assertion_id IN (SELECT value FROM json_each(l.input_assertion_ids_json)) AND other.body_id<>p.body_id)"""))
 # Campaign source IDs are provenance-isolated. A Europa source may not be attached to an existing-body fact.
 add('SOURCE_REUSE_EVIDENCE_LEAK',c.execute("""SELECT x.fact_id,f.body_id,x.source_id FROM source_assertion x JOIN fact f USING(fact_id) WHERE f.body_id IN ('CERES','COMET_67P') AND x.source_id IN (SELECT source_id FROM promotion_assertion WHERE campaign_id='ARP-QUAL-02-EUROPA')"""))
 add('SOURCE_BODY_LEAK',c.execute("""SELECT 'observation' object_table,observation_id object_id,body_id,source_id FROM observation WHERE body_id<>'EUROPA' AND source_id IN (SELECT source_id FROM promotion_assertion WHERE campaign_id='ARP-QUAL-02-EUROPA') UNION ALL SELECT 'material_evidence',material_evidence_id,body_id,source_id FROM material_evidence WHERE body_id<>'EUROPA' AND source_id IN (SELECT source_id FROM promotion_assertion WHERE campaign_id='ARP-QUAL-02-EUROPA') UNION ALL SELECT 'activity_fact',activity_id,body_id,source_id FROM activity_fact WHERE body_id<>'EUROPA' AND source_id IN (SELECT source_id FROM promotion_assertion WHERE campaign_id='ARP-QUAL-02-EUROPA') UNION ALL SELECT 'body_model_product',model_product_id,body_id,source_id FROM body_model_product WHERE body_id<>'EUROPA' AND source_id IN (SELECT source_id FROM promotion_assertion WHERE campaign_id='ARP-QUAL-02-EUROPA') UNION ALL SELECT 'orientation_model',orientation_model_id,body_id,source_id FROM orientation_model WHERE body_id<>'EUROPA' AND source_id IN (SELECT source_id FROM promotion_assertion WHERE campaign_id='ARP-QUAL-02-EUROPA') UNION ALL SELECT 'body_region',region_id,body_id,source_id FROM body_region WHERE body_id<>'EUROPA' AND source_id IN (SELECT source_id FROM promotion_assertion WHERE campaign_id='ARP-QUAL-02-EUROPA')"""))
 add('EUROPA_TYPED_SOURCE_OUTSIDE_CAMPAIGN',c.execute("""WITH campaign_sources AS (SELECT source_id FROM promotion_assertion WHERE campaign_id='ARP-QUAL-02-EUROPA'), typed(object_table,object_id,body_id,source_id) AS (SELECT 'observation',observation_id,body_id,source_id FROM observation WHERE body_id='EUROPA' UNION ALL SELECT 'material_evidence',material_evidence_id,body_id,source_id FROM material_evidence WHERE body_id='EUROPA' UNION ALL SELECT 'activity_fact',activity_id,body_id,source_id FROM activity_fact WHERE body_id='EUROPA' UNION ALL SELECT 'body_model_product',model_product_id,body_id,source_id FROM body_model_product WHERE body_id='EUROPA' UNION ALL SELECT 'orientation_model',orientation_model_id,body_id,source_id FROM orientation_model WHERE body_id='EUROPA' UNION ALL SELECT 'body_region',region_id,body_id,source_id FROM body_region WHERE body_id='EUROPA' UNION ALL SELECT 'fact_source_assertion',fact_id,f.body_id,sa.source_id FROM fact f JOIN source_assertion sa USING(fact_id) WHERE f.body_id='EUROPA') SELECT t.* FROM typed t WHERE t.source_id NOT IN campaign_sources"""))
 add('TEMPORAL_CUTOFF_LEAK',c.execute("""SELECT s.source_id,s.publication_date FROM source s JOIN promotion_assertion p USING(source_id) WHERE p.campaign_id='ARP-QUAL-02-EUROPA' AND s.publication_date>'2025-12-31T23:59:59Z'"""))
 add('CANDIDATE_PREFERRED_STATUS_LEAK',c.execute("SELECT promotion_assertion_id,assertion_id,status FROM promotion_assertion WHERE campaign_id='ARP-QUAL-02-EUROPA' AND status<>'CANDIDATE'"))
 add('UNREVIEWED_ASSERTION',c.execute("SELECT p.promotion_assertion_id,p.assertion_id FROM promotion_assertion p LEFT JOIN promotion_review r USING(promotion_assertion_id) WHERE p.campaign_id='ARP-QUAL-02-EUROPA' AND r.promotion_assertion_id IS NULL"))
 add('MISSING_SOURCE_ARTIFACT',c.execute("SELECT p.assertion_id,p.artifact_id FROM promotion_assertion p LEFT JOIN source_artifact a USING(artifact_id) WHERE p.campaign_id='ARP-QUAL-02-EUROPA' AND a.artifact_id IS NULL"))
 add('PROMOTION_SOURCE_NOT_CAMPAIGN',c.execute("""SELECT p.assertion_id,p.source_id FROM promotion_assertion p WHERE p.campaign_id='ARP-QUAL-02-EUROPA' AND p.source_id NOT IN (SELECT value FROM json_each((SELECT value FROM promotion_manifest WHERE key='campaign_source_ids')))"""))
 add('PROMOTION_SOURCE_ARTIFACT_MISMATCH',c.execute("SELECT p.assertion_id,p.source_id,a.source_id artifact_source FROM promotion_assertion p JOIN source_artifact a USING(artifact_id) WHERE p.campaign_id='ARP-QUAL-02-EUROPA' AND p.source_id<>a.source_id"))
 add('PROMOTION_ARTIFACT_NOT_CAMPAIGN',c.execute("""SELECT p.assertion_id,p.artifact_id FROM promotion_assertion p WHERE p.campaign_id='ARP-QUAL-02-EUROPA' AND p.artifact_id NOT IN (SELECT value FROM json_each((SELECT value FROM promotion_manifest WHERE key='campaign_artifact_ids')))"""))
 c.close();return out

def require_valid(db):
 errors=violations(db)
 if errors:raise ValueError(json.dumps(errors,indent=2))
 return True
