PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS geometry_parameters (
    key TEXT PRIMARY KEY,
    value_real REAL,
    value_text TEXT,
    unit TEXT,
    status TEXT NOT NULL,
    source TEXT NOT NULL,
    source_version TEXT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS mass_elements (
    id TEXT PRIMARY KEY,
    mass_t REAL NOT NULL,
    x_m REAL NOT NULL,
    y_m REAL NOT NULL DEFAULT 0,
    z_m REAL NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    notes TEXT
);

INSERT OR REPLACE INTO geometry_parameters VALUES
('ship.length_m',57.0,NULL,'m','CANON','CANON_II','v2.4','Overall permanent mothership length'),
('ship.main_body_diameter_m',9.0,NULL,'m','CANON','CANON_II','v2.4','Nominal main-body diameter'),
('ship.launch_side',NULL,'+Z',NULL,'DESIGN_BASELINE','Phase_2J','v0.1','Launch-bay side convention'),
('ship.docking_side',NULL,'-Z',NULL,'DESIGN_BASELINE','Phase_2J','v0.1','Docking side convention'),
('pressure_hull.x_start_m',0.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Forward pressure hull start'),
('pressure_hull.x_end_m',14.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Forward pressure hull end'),
('pressure_hull.diameter_m',8.6,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Trial diameter; allowed range 8.4-8.8 m'),
('technical_core.diameter_m',1.4,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Tank-region technical core'),
('tank.count',4.0,NULL,'count','CANON','CANON_II','v2.4','Four major working-fluid/remass tanks'),
('tank.x_start_m',18.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Major tank region start'),
('tank.x_end_m',32.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Major tank region end'),
('tank.external_diameter_m',3.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Nominal major tank external diameter'),
('tank.center_radius_m',2.7,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Tank-center radius from thrust axis'),
('tank.normal_inventory_each_t',62.5,NULL,'t','DERIVED','Phase_2E','v0.1','250 t normal remass-capable inventory divided equally among four major tanks'),
('longeron.count',4.0,NULL,'count','CANON','CANON_II','v2.4','Four axial longerons'),
('longeron.center_radius_m',2.45,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Nominal radial station'),
('longeron.x_start_m',14.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Principal visible run start'),
('longeron.x_end_m',50.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Principal visible run end'),
('launch_bay.x_start_m',16.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Integrated launch-bay start'),
('launch_bay.x_end_m',27.5,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Integrated launch-bay end'),
('launch_bay.clear_width_m',4.4,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Nominal clear transverse width'),
('launch_bay.radial_depth_m',3.5,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Nominal radial bay depth'),
('launch_bay.inner_floor_radius_m',3.6,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Distance from thrust axis to bay floor'),
('launch.length_m',10.5,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Planetary launch working envelope'),
('launch.width_m',3.9,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Planetary launch working envelope'),
('launch.height_m',3.1,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Planetary launch working envelope'),
('launch.mass_t',33.0,NULL,'t','DESIGN_BASELINE','Phase_2F','v0.1','Working configured launch mass; range 30-35 t'),
('docking.x_center_m',16.0,NULL,'m','DESIGN_BASELINE','Phase_2I','v0.1','Standard docking collar working station'),
('relational.x_start_m',18.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Principal relational plant envelope start'),
('relational.x_end_m',34.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Principal relational plant envelope end'),
('relational.mass_t',88.0,NULL,'t','CANON','CANON_II','v2.4','Unified relational plant mass'),
('relational.node_count',208.0,NULL,'count','CANON','CANON_II','v2.4','Distributed relational nodes'),
('radiator.count',4.0,NULL,'count','CANON','CANON_II','v2.4','Four major deployable radiator assemblies'),
('radiator.root_x_start_m',33.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Radiator root region start'),
('radiator.root_x_end_m',38.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Radiator root region end'),
('radiator.metric_hard_equiv_area_900k_m2',719.0,NULL,'m2','CANON','CANON_II','v2.4','HARD metric equivalent area; not total physical panel area'),
('shield.x_start_m',38.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Directional shadow-shield region start'),
('shield.x_end_m',43.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Directional shadow-shield region end'),
('shield.diameter_m',5.5,NULL,'m','DESIGN_BASELINE','Phase_2H','v0.1','Working shield transverse envelope'),
('reactor.x_start_m',43.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Reactor/torch machinery start'),
('reactor.x_end_m',50.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Reactor/torch machinery end'),
('reactor.diameter_m',4.25,NULL,'m','DESIGN_BASELINE','Phase_2H','v0.1','Working reactor/torch envelope'),
('nozzle.x_start_m',50.0,NULL,'m','DESIGN_BASELINE','Phase_2J','v0.1','Magnetic-nozzle start'),
('nozzle.x_end_m',57.0,NULL,'m','CANON','Phase_2J','v0.1','Nozzle terminates within canonical ship length'),
('nozzle.aperture_diameter_m',6.0,NULL,'m','DESIGN_BASELINE','Phase_2H','v0.1','Working magnetic-nozzle aperture/support diameter'),
('mass.dry_reference_t',858.5,NULL,'t','CANON','CANON_II','v2.4','Dry mass excluding working fluid/water'),
('mass.wet_reference_t',1158.5,NULL,'t','CANON','CANON_II','v2.4','Reference wet mass'),
('mass.working_fluid_water_t',300.0,NULL,'t','CANON','CANON_II','v2.4','Total working fluid/water inventory'),
('mass.normal_remass_t',250.0,NULL,'t','CANON','CANON_II','v2.4','Normal remass contained within 300 t inventory'),
('mass.protected_water_t',50.0,NULL,'t','CANON','Technical_Paper_Series','v1.0','Protected water reserve'),
('loom.normal_boundary_target_m2',1900.0,NULL,'m2','CANON','Technical_Paper_Series','v1.0','Normal controlled Loom boundary calibration'),
('loom.extended_boundary_target_m2',2430.0,NULL,'m2','CANON','Technical_Paper_Series','v1.0','Extended mature-route Loom boundary calibration'),
('loom.effective_patch_target',971.0,NULL,'count','CANON','Technical_Paper_Series','v1.0','Normal effective patch calibration'),
('loom.boundary_authority',670.0,NULL,'arb','CANON','Technical_Paper_Series','v1.0','Reference boundary authority'),
('validation.normal_boundary_tolerance_fraction',0.10,NULL,'fraction','DESIGN_BASELINE','Phase_3','v0.1','Regression tolerance for surrogate boundary check');

INSERT OR REPLACE INTO mass_elements VALUES
('structure',150.0,28.0,0.0,0.0,'DESIGN_BASELINE','Primary structure, pressure hull, tank shells and frames'),
('armor_fixed_shield',105.0,9.5,0.0,0.0,'DESIGN_BASELINE','Forward armor, MMOD and fixed shielding; excludes protected water'),
('habitation_life_support',45.0,8.0,0.0,0.0,'DESIGN_BASELINE','Habitation, life support, medical and interiors'),
('relational_plant',88.0,26.0,0.0,0.0,'CANON_MASS_DESIGN_POSITION','Canon mass with design-baseline centroid'),
('thermal_radiators',90.0,35.0,0.0,0.0,'DESIGN_BASELINE','Thermal machinery and four radiator assemblies'),
('propulsion',160.0,46.5,0.0,0.0,'DESIGN_BASELINE','Reactor, torch, nozzle, propulsion shielding and thrust machinery'),
('electrical',55.0,31.0,0.0,0.0,'DESIGN_BASELINE','Generation, conversion, storage and distribution'),
('planetary_launch',33.0,21.8,0.0,5.2,'DESIGN_BASELINE','Docked launch; lateral offset is intentionally conservative for trim test'),
('avionics_sensors_comms',20.0,12.0,0.0,0.0,'DESIGN_BASELINE','Avionics, navigation, sensors and comms'),
('rcs_docking_service',25.0,28.0,0.0,0.0,'DESIGN_BASELINE','RCS, docking and service/capture hardware'),
('mission_courier_systems',20.0,17.0,0.0,0.0,'DESIGN_BASELINE','Mission and courier handling systems'),
('engineering_reserve',67.5,28.0,0.0,0.0,'DESIGN_BASELINE','Explicit unresolved engineering reserve');
