(()=>{'use strict';
const BUILD='hud-v0.12-intercept';
const stage=document.getElementById('stage'),canvas=document.getElementById('world'),readout=document.getElementById('readout'),badge=document.getElementById('badge'),trajkey=document.getElementById('trajkey'),modeSel=document.getElementById('mode'),cameraSel=document.getElementById('camera'),burn=document.getElementById('burn'),reset=document.getElementById('reset'),previewBtn=document.getElementById('preview'),solveBtn=document.getElementById('solve'),previewMeta=document.getElementById('previewMeta'),burnS=document.getElementById('burnS'),coastS=document.getElementById('coastS');
let renderer,scene,camera,moonTopo,moonOptical,earth,ship,state,shipGeometryLoaded=false,moonAsset='LOADING',moonModelRadiusKm=null,moonTextureCount=0,pollBusy=false,lastError='',trajectoryGroup=null,previewData=null;
function fmt(n,d=2){return Number.isFinite(Number(n))?Number(n).toFixed(d):'—'} function mag(v){return Math.hypot(...v)} function v3(a){return new THREE.Vector3(Number(a[0]),Number(a[1]),Number(a[2]))}
function material(hex){return new THREE.MeshStandardMaterial({color:hex,roughness:.72,metalness:.12})} function marker(radius,color){return new THREE.Mesh(new THREE.SphereGeometry(radius,24,12),new THREE.MeshBasicMaterial({color}))}
function init3D(){if(!window.THREE)throw new Error('Three.js unavailable');renderer=new THREE.WebGLRenderer({canvas,antialias:true,logarithmicDepthBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputEncoding=THREE.sRGBEncoding;scene=new THREE.Scene();scene.background=new THREE.Color(0x000002);camera=new THREE.PerspectiveCamera(60,1,.001,5000000);scene.add(new THREE.HemisphereLight(0x8899aa,0x111116,.85));const sun=new THREE.DirectionalLight(0xffffff,1.5);sun.position.set(1,1,1);scene.add(sun);earth=new THREE.Mesh(new THREE.SphereGeometry(6378.137,64,32),material(0x27496d));scene.add(earth);loadMoon();loadWayfarer();resize();requestAnimationFrame(render)}
function loadMoon(){if(!THREE.GLTFLoader){moonAsset='GLTFLOADER MISSING';return}new THREE.GLTFLoader().load('/qualification-assets/Moon_NASA_LRO_8k_Topo_Small.glb',g=>{const asset=g.scene,box=new THREE.Box3().setFromObject(asset),center=new THREE.Vector3(),sphere=new THREE.Sphere();box.getCenter(center);box.getBoundingSphere(sphere);if(!(sphere.radius>0))throw new Error('NASA Moon GLB invalid bounds');const scale=1737.4/sphere.radius;asset.scale.setScalar(scale);asset.position.copy(center).multiplyScalar(-scale);moonTopo=new THREE.Group();moonTopo.add(asset);scene.add(moonTopo);const checkBox=new THREE.Box3().setFromObject(moonTopo),checkSphere=new THREE.Sphere();checkBox.getBoundingSphere(checkSphere);moonModelRadiusKm=checkSphere.radius;let tex=null,meshes=0;asset.traverse(o=>{if(o.isMesh){meshes++;o.frustumCulled=false;if(o.material){const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){if(m.map&&!tex)tex=m.map;}}}});if(tex){tex.encoding=THREE.sRGBEncoding;tex.needsUpdate=true;moonTextureCount=1;}const mat=new THREE.MeshBasicMaterial({map:tex||null,color:tex?0xffffff:0x9a9a9a,side:THREE.DoubleSide,toneMapped:false});moonOptical=new THREE.Mesh(new THREE.SphereGeometry(1737.4,128,64),mat);moonOptical.frustumCulled=false;scene.add(moonOptical);moonAsset=`NASA LRO OPTICAL ${tex?'TEX':'GRAY'} + TOPO ${meshes}`;},undefined,e=>{moonAsset='NASA GLB UNAVAILABLE';lastError='NASA Moon: '+(e&&e.message?e.message:e);moonOptical=new THREE.Mesh(new THREE.SphereGeometry(1737.4,96,48),new THREE.MeshBasicMaterial({color:0x999999}));moonModelRadiusKm=1737.4;scene.add(moonOptical)});}
function addComponent(group,c,mats){const d=c.dimensions||{},p=(c.center_m||[0,0,0]).map(x=>Number(x)/1000);let geo=null;if(c.kind==='box')geo=new THREE.BoxGeometry(Number(d.x_m||1)/1000,Number(d.y_m||1)/1000,Number(d.z_m||1)/1000);else if(c.kind==='cylinder_x'||c.kind==='nozzle_x'){const l=Number(d.length_m||1)/1000,di=Number(d.diameter_m||d.aperture_diameter_m||1)/1000;geo=new THREE.CylinderGeometry(di/2,di/2,l,18);geo.rotateZ(-Math.PI/2)}else if(c.kind==='collar_z')geo=new THREE.CylinderGeometry(Number(d.diameter_m||1)/2000,Number(d.diameter_m||1)/2000,Number(d.depth_m||.7)/1000,18);else if(c.kind==='radiator_placeholder')geo=new THREE.BoxGeometry(Number(d.root_length_m||1)/1000,Number(d.panel_chord_m||1)/1000,.00008);if(!geo)return;const mesh=new THREE.Mesh(geo,mats[c.group]||mats.default);mesh.position.set(...p);group.add(mesh)}
async function loadWayfarer(){try{const r=await fetch('/wayfarer-geometry.json',{cache:'no-store'}),g=await r.json();if(!r.ok)throw new Error(g.reason||'geometry unavailable');ship=new THREE.Group();const mats={default:material(0x7d8a8d),habitat:material(0xaab5b4),tanks:material(0x59676b),structure:material(0x718082),launch_bay:material(0x6e6254),launch:material(0x86725b),radiators:material(0x4f5f61),propulsion:material(0x806f66),docking:material(0x849093)};(g.components||[]).forEach(c=>addComponent(ship,c,mats));scene.add(ship);shipGeometryLoaded=true}catch(e){lastError='Wayfarer geometry: '+e.message}}
function resize(){if(!renderer)return;const r=stage.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=Math.max(1,r.width)/Math.max(1,r.height);camera.updateProjectionMatrix()}
function moonPresentation(){if(!state)return null;const rel=v3(state.moon.relative_to_wayfarer_km),nose=v3(state.wayfarer.fixed_nose_direction_inertial).normalize(),range=rel.length(),dir=rel.clone().normalize(),up0=new THREE.Vector3(0,0,1);if(Math.abs(nose.dot(up0))>.97)up0.set(0,1,0);const right=new THREE.Vector3().crossVectors(nose,up0).normalize(),up=new THREE.Vector3().crossVectors(right,nose).normalize(),f=Math.max(-1,Math.min(1,dir.dot(nose))),bearing=Math.atan2(dir.dot(right),f)*180/Math.PI,elevation=Math.asin(Math.max(-1,Math.min(1,dir.dot(up))))*180/Math.PI,diam=2*Math.atan2(1737.4,range)*180/Math.PI;return{range,bearing,elevation,diam}}
function setLiveObjects(){const moonRel=v3(state.moon.relative_to_wayfarer_km),earthRel=v3(state.earth.relative_to_wayfarer_km),nose=v3(state.wayfarer.fixed_nose_direction_inertial).normalize();if(moonTopo){moonTopo.position.copy(moonRel);moonTopo.visible=false}if(moonOptical){moonOptical.position.copy(moonRel);moonOptical.visible=true}earth.visible=true;earth.position.copy(earthRel);if(ship){ship.visible=true;ship.position.set(0,0,0);ship.quaternion.setFromUnitVectors(new THREE.Vector3(-1,0,0),nose)}return nose}
function updateObjects(){if(!state||!scene)return;trajkey.style.display=cameraSel.value==='TRAJECTORY'?'block':'none';if(trajectoryGroup)trajectoryGroup.visible=cameraSel.value==='TRAJECTORY';if(cameraSel.value==='TRAJECTORY'&&previewData){setTrajectoryScene();return}const nose=setLiveObjects(),up=new THREE.Vector3(0,0,1);if(Math.abs(nose.dot(up))>.97)up.set(0,1,0);camera.near=.001;camera.far=5000000;camera.updateProjectionMatrix();if(cameraSel.value==='SHIP'){if(ship)ship.visible=false;camera.position.set(0,0,0);camera.up.copy(up);camera.lookAt(nose.clone().multiplyScalar(100000));}else{const right=new THREE.Vector3().crossVectors(nose,up).normalize(),trueUp=new THREE.Vector3().crossVectors(right,nose).normalize();camera.position.copy(nose.clone().multiplyScalar(-.16)).add(trueUp.multiplyScalar(.065));camera.up.copy(trueUp);camera.lookAt(0,0,0)}}
function allTrajectoryPoints(){if(!previewData)return[];const start=v3(previewData.start_position_earth_centered_km),out=[new THREE.Vector3(0,0,0),start.clone().multiplyScalar(-1)];for(const p of previewData.points){out.push(v3(p.wayfarer_position_earth_centered_km).sub(start));out.push(v3(p.moon_position_earth_centered_km).sub(start))}return out}
function setTrajectoryScene(){const start=v3(previewData.start_position_earth_centered_km),last=previewData.points[previewData.points.length-1];if(ship){ship.visible=true;ship.position.copy(v3(last.wayfarer_position_earth_centered_km).sub(start))}earth.visible=true;earth.position.copy(start).multiplyScalar(-1);const mp=v3(last.moon_position_earth_centered_km).sub(start);if(moonOptical){moonOptical.visible=true;moonOptical.position.copy(mp)}if(moonTopo)moonTopo.visible=false;const pts=allTrajectoryPoints(),box=new THREE.Box3().setFromPoints(pts),center=new THREE.Vector3(),size=new THREE.Vector3();box.getCenter(center);box.getSize(size);const extent=Math.max(size.x,size.y,size.z,50000);camera.position.copy(center).add(new THREE.Vector3(0,0,extent*1.65));camera.up.set(0,1,0);camera.lookAt(center);camera.near=Math.max(.001,extent/1000000);camera.far=Math.max(5000000,extent*20);camera.updateProjectionMatrix()}
function addEndMarker(group,p,r,c){const m=marker(r,c);m.position.copy(p);group.add(m)}
function drawTrajectory(d){previewData=d;if(trajectoryGroup)scene.remove(trajectoryGroup);trajectoryGroup=new THREE.Group();const start=v3(d.start_position_earth_centered_km),burnPts=[new THREE.Vector3(0,0,0)],coastPts=[],moonPts=[];for(const p of d.points){const wp=v3(p.wayfarer_position_earth_centered_km).sub(start),mp=v3(p.moon_position_earth_centered_km).sub(start);if(p.phase==='BURN')burnPts.push(wp);else coastPts.push(wp);moonPts.push(mp)}function line(points,color){if(points.length<2)return;trajectoryGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color})))}line(burnPts,0xf0c36a);if(burnPts.length&&coastPts.length)coastPts.unshift(burnPts[burnPts.length-1]);line(coastPts,0x7fd7d0);line(moonPts,0x8ea2aa);addEndMarker(trajectoryGroup,new THREE.Vector3(0,0,0),1800,0xffffff);if(d.points.length)addEndMarker(trajectoryGroup,v3(d.points[d.points.length-1].wayfarer_position_earth_centered_km).sub(start),2200,0x7fd7d0);scene.add(trajectoryGroup);const f=d.final||{};previewMeta.textContent=`${d.solver||'PROPAGATE'} • ${d.mode} • burn ${fmt(d.burn_s,0)}s • final v ${fmt(f.speed_km_s,2)} km/s • miss ${fmt(f.moon_range_km,0)} km • rel v ${fmt(f.relative_speed_km_s,2)} km/s • remass ${fmt(f.remass_t,1)} t`;cameraSel.value='TRAJECTORY';updateObjects()}
async function calculatePreview(){previewMeta.textContent='CALCULATING…';try{const u=`/qualification-flight/trajectory-preview.json?burn_s=${encodeURIComponent(burnS.value)}&coast_s=${encodeURIComponent(coastS.value)}&mode=${encodeURIComponent(modeSel.value)}&sample_s=60`,r=await fetch(u,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.reason||'preview unavailable');drawTrajectory(j)}catch(e){previewMeta.textContent='UNAVAILABLE: '+e.message}}
async function solveIntercept(){previewMeta.textContent='SOLVING INTERCEPT…';try{const u=`/qualification-flight/intercept-preview.json?max_time_s=${encodeURIComponent(Number(burnS.value)+Number(coastS.value))}&mode=${encodeURIComponent(modeSel.value)}&sample_s=60`,r=await fetch(u,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.reason||'intercept unavailable');drawTrajectory(j)}catch(e){previewMeta.textContent='UNAVAILABLE: '+e.message}}
function render(){if(renderer){updateObjects();renderer.render(scene,camera)}requestAnimationFrame(render)}
async function post(payload){const r=await fetch('/qualification-flight/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw new Error(j.reason||'control rejected');state=j;updateHUD();return j}
function updateHUD(){if(!state)return;const mp=moonPresentation(),sv=mag(state.wayfarer.velocity_earth_centered_km_s),t=state.torch;readout.innerHTML=`<b>WAYFARER / ${state.status}</b><br>SIM ${state.sim_epoch_utc}<br>RATE ${state.time_scale}× • v ${fmt(sv,3)} km/s<br>MOON RANGE ${fmt(mp&&mp.range,0)} km<br>MOON BRG ${fmt(mp&&mp.bearing,3)}° • EL ${fmt(mp&&mp.elevation,3)}°<br>MOON DIAM ${fmt(mp&&mp.diam,3)}°<br>WET ${fmt(state.wayfarer.wet_mass_t,2)} t • REMASS ${fmt(state.wayfarer.remass_t,2)} t<br>TORCH ${t.active?'ACTIVE':'OFF'} ${t.mode} ${fmt(t.acceleration_g,2)} g`;badge.innerHTML=`JPL + HERMITE<br>${moonAsset}<br>GLB R ${fmt(moonModelRadiusKm,1)} km<br>${shipGeometryLoaded?'WAYFARER 3D':'WAYFARER LOADING'}<br><span class="warn">ATTITUDE FIXED / NO ROTATION</span>${lastError?'<br><span class="bad">'+lastError+'</span>':''}`;burn.textContent=t.active?'TORCH ACTIVE':'TORCH OFF';burn.classList.toggle('active',t.active);modeSel.value=t.mode;document.querySelectorAll('[data-rate]').forEach(b=>b.classList.toggle('active',Number(b.dataset.rate)===Number(state.time_scale)))}
async function poll(){if(pollBusy)return;pollBusy=true;try{const r=await fetch('/qualification-flight.json',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.reason||'state unavailable');state=j;lastError='';updateHUD()}catch(e){lastError=e.message;readout.textContent='UNAVAILABLE: '+e.message}finally{pollBusy=false}}
document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>post({action:'TIME_SCALE',value:Number(b.dataset.rate)}));burn.onclick=()=>post({action:'TORCH',active:!(state&&state.torch.active),mode:modeSel.value});modeSel.onchange=()=>post({action:'TORCH',active:!!(state&&state.torch.active),mode:modeSel.value});reset.onclick=()=>post({action:'RESET_REALTIME'});previewBtn.onclick=calculatePreview;solveBtn.onclick=solveIntercept;cameraSel.onchange=updateObjects;window.addEventListener('resize',resize);window.addEventListener('orientationchange',()=>setTimeout(resize,100));try{init3D();poll();setInterval(poll,100)}catch(e){readout.textContent='UNAVAILABLE: '+e.message}
})();
