# Mercury/Venus scientific population. Executed after common six-body research rows exist.
S=MV_SOURCE_IDS
def R(b,k,n,t): return db.execute('insert into region(body_id,region_key,region_name,region_type) values(?,?,?,?)',(b,k,n,t)).lastrowid
mr=R('MERCURY','MERCURY_N_POLAR','Mercury north polar region','REGION'); ml=R('MERCURY','MERCURY_LRM','Mercury low-reflectance material terrains','REGION')
va=R('VENUS','VENUS_ATMOS','Venus atmosphere','MODEL_DOMAIN'); v13=R('VENUS','VENERA13','Venera 13 landing site','LOCAL_SITE'); v14=R('VENUS','VENERA14','Venera 14 landing site','LOCAL_SITE'); vg2=R('VENUS','VEGA2','Vega 2 landing site','LOCAL_SITE'); vs=R('VENUS','SIFMONS','Sif Mons western flank','REGION'); vn=R('VENUS','NIOBE_W','Western Niobe Planitia','REGION')
def P(b,r,k,t,title,src,res=None,u=None,scope='BODY'):
 return db.execute('insert into spatial_product(body_id,region_id,product_key,product_type,title,source_id,horizontal_resolution_value,horizontal_resolution_unit,scope,status) values(?,?,?,?,?,?,?,?,?,?)',(b,r,k,t,title,S[src],res,u,scope,'CANDIDATE')).lastrowid
mt=P('MERCURY',None,'MERCURY_TOPO','TOPOGRAPHY','MESSENGER/USGS global Mercury topography','MERCURY_TOPO',665,'m')
mg=P('MERCURY',None,'MERCURY_GEOLOGY','GEOLOGIC_MAP','USGS global geologic map of Mercury','MERCURY_GEOLOGY')
mp=P('MERCURY',mr,'MERCURY_POLAR_ICE','POLAR_VOLATILE_MAP','MESSENGER shadow/radar/neutron polar volatile support','MERCURY_POLAR',scope='REGION')
vr=P('VENUS',None,'VENUS_MAGELLAN_RADAR','RADAR_MOSAIC','Magellan near-global SAR imaging','VENUS_MAGELLAN_PDS',75,'m')
vt=P('VENUS',None,'VENUS_MAGELLAN_TOPO','TOPOGRAPHY','Magellan altimetry/topography products','VENUS_MAGELLAN_PDS')
vg=P('VENUS',vs,'VENUS_GEOLOGIC_PROGRAM','GEOLOGIC_MAP','USGS Magellan regional geologic mapping','VENUS_GEOLOGY',5000,'m','REGION')
def Q(key,b,prop,ont,scope,src,kind='TEXT',num=None,text=None,unit=None,unc=None,vmin=None,vmax=None,rep='UNKNOWN',region=None,product=None,method=None,notes=None,vc=None,zmin=None,zmax=None,zu=None,zdatum=None):
 db.execute('''insert into scientific_assertion(assertion_key,body_id,property_code,ontology,scope,region_id,spatial_product_id,value_kind,value_numeric,value_text,unit,uncertainty_text,value_min,value_max,vertical_coordinate_type,vertical_min,vertical_max,vertical_unit,vertical_datum,epistemic_class,measurement_method,representativeness,source_id,admission_status,preferred,origin,notes) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''',(key,b,prop,ont,scope,region,product,kind,num,text,unit,unc,vmin,vmax,vc,zmin,zmax,zu,zdatum,'MEASURED' if ont=='REAL_EVIDENCE' else 'MODEL_INFERENCE',method,rep,S[src],'CANDIDATE',0,'NEW_CHATGPT_RESEARCH',notes))
Q('R_MERC_TOPO','MERCURY','GLOBAL_TOPOGRAPHY','REAL_EVIDENCE','BODY','MERCURY_TOPO','SPATIAL_PRODUCT',text='global MESSENGER MDIS/MLA-derived topographic framework',rep='BODY_REPRESENTATIVE',product=mt)
Q('R_MERC_GEO','MERCURY','GLOBAL_GEOLOGIC_UNITS','REAL_EVIDENCE','BODY','MERCURY_GEOLOGY','SPATIAL_PRODUCT',text='global mapped plains, basins, craters, tectonic and volcanic units',rep='BODY_REPRESENTATIVE',product=mg)
Q('R_MERC_LRM_C','MERCURY','LOW_REFLECTANCE_CARBON_ENRICHMENT','REAL_EVIDENCE','REGION','MERCURY_CARBON','RANGE',unit='wt%',vmin=1,vmax=3,rep='REGION_REPRESENTATIVE',region=ml,method='neutron spectroscopy plus spectral/geologic correlation',notes='enrichment relative to surrounding material, not global carbon abundance')
Q('R_MERC_GRAPHITE','MERCURY','MICROCRYSTALLINE_GRAPHITE_MODEL','MODEL_INFERENCE','REGION','MERCURY_GRAPHITE_2024','BOUND',unit='wt%',vmax=1,rep='REGION_REPRESENTATIVE',region=ml,notes='spectral-model bound for graphite phase; other carbon forms remain possible')
Q('R_MERC_MINERAL','MERCURY','SILICATE_MINERAL_ASSEMBLAGE_MODEL','MODEL_INFERENCE','MODEL_DOMAIN','MERCURY_MINERAL','MODEL',text='experimental crystallization supports olivine, plagioclase, pyroxenes and tridymite under Mercury-like reducing conditions',rep='MODEL_DOMAIN_ONLY',notes='MESSENGER spectra do not support a global mineralogical map')
Q('R_MERC_SHADOW','MERCURY','POLAR_PERMANENT_SHADOW','REAL_EVIDENCE','REGION','MERCURY_POLAR','SPATIAL_PRODUCT',text='radar-bright deposits collocate with persistent/permanent shadow',rep='REGION_REPRESENTATIVE',region=mr,product=mp)
Q('R_MERC_H','MERCURY','POLAR_HYDROGEN_ENHANCEMENT','REAL_EVIDENCE','REGION','MERCURY_POLAR','DETECTION',text='enhanced hydrogen measured by MESSENGER Neutron Spectrometer',rep='REGION_REPRESENTATIVE',region=mr,method='neutron spectroscopy')
Q('R_MERC_ICE','MERCURY','POLAR_WATER_ICE_INTERPRETATION','MODEL_INFERENCE','REGION','MERCURY_POLAR','MODEL',text='combined radar, shadow, thermal and neutron evidence is quantitatively consistent with radar-bright deposits dominated by water ice',rep='REGION_REPRESENTATIVE',region=mr,notes='regional interpretation; not global abundance or accessible inventory')
Q('R_MERC_XRS','MERCURY','ELEMENTAL_MAP_PRODUCTS','REAL_EVIDENCE','FOOTPRINT','MERCURY_PDS','TEXT',text='XRS derived footprint/map products constrain spatial elemental heterogeneity',rep='FOOTPRINT_ONLY',region=ml,notes='individual elemental ratios remain product/footprint scoped')
Q('R_VENUS_P','VENUS','SURFACE_ATMOSPHERIC_PRESSURE','REAL_EVIDENCE','BODY','VENUS_FACT','NUMERIC',92,unit='bar',rep='BODY_REPRESENTATIVE',notes='reference mean surface condition')
Q('R_VENUS_T','VENUS','MEAN_SURFACE_TEMPERATURE','REAL_EVIDENCE','BODY','VENUS_FACT','NUMERIC',737,unit='K',rep='BODY_REPRESENTATIVE')
Q('R_VENUS_CO2','VENUS','NEAR_SURFACE_CO2_VOLUME_FRACTION','REAL_EVIDENCE','MODEL_DOMAIN','VENUS_FACT','NUMERIC',96.5,unit='%',rep='MODEL_DOMAIN_ONLY',region=va)
Q('R_VENUS_N2','VENUS','NEAR_SURFACE_N2_VOLUME_FRACTION','REAL_EVIDENCE','MODEL_DOMAIN','VENUS_FACT','NUMERIC',3.5,unit='%',rep='MODEL_DOMAIN_ONLY',region=va)
Q('R_VENUS_H2O','VENUS','NEAR_SURFACE_H2O_MIXING_RATIO','REAL_EVIDENCE','MODEL_DOMAIN','VENUS_FACT','NUMERIC',20,unit='ppm',rep='MODEL_DOMAIN_ONLY',region=va)
Q('R_VENUS_CLOUD_ALT','VENUS','SULFURIC_ACID_CLOUD_VERTICAL_DOMAIN','REAL_EVIDENCE','MODEL_DOMAIN','VENUS_ATMOS','TEXT',text='sulfuric acid present through main cloud domain above lower evaporation boundary',rep='MODEL_DOMAIN_ONLY',region=va,vc='ALTITUDE',zmin=48,zmax=75,zu='km',zdatum='VENUS_MEAN_SURFACE')
Q('R_VENUS_HAZE_ALT','VENUS','UPPER_HAZE_VERTICAL_DOMAIN','REAL_EVIDENCE','MODEL_DOMAIN','VENUS_ATMOS','TEXT',text='upper haze observational/model domain',rep='MODEL_DOMAIN_ONLY',region=va,vc='ALTITUDE',zmin=70,zmax=110,zu='km',zdatum='VENUS_MEAN_SURFACE')
Q('R_VENUS_CLOUD_COMP','VENUS','CLOUD_COMPOSITION','REAL_EVIDENCE','MODEL_DOMAIN','VENUS_ATMOS','DETECTION',text='main clouds composed predominantly of concentrated sulfuric-acid droplets',rep='MODEL_DOMAIN_ONLY',region=va)
Q('R_VENUS_RADAR','VENUS','GLOBAL_RADAR_MORPHOLOGY','REAL_EVIDENCE','BODY','VENUS_MAGELLAN_PDS','SPATIAL_PRODUCT',text='near-global Magellan SAR morphology/backscatter framework',rep='BODY_REPRESENTATIVE',product=vr)
Q('R_VENUS_TOPO','VENUS','GLOBAL_TOPOGRAPHY','REAL_EVIDENCE','BODY','VENUS_MAGELLAN_PDS','SPATIAL_PRODUCT',text='Magellan altimetry/topography framework',rep='BODY_REPRESENTATIVE',product=vt)
Q('R_VENUS_GEO','VENUS','REGIONAL_GEOLOGIC_UNITS','REAL_EVIDENCE','REGION','VENUS_GEOLOGY','SPATIAL_PRODUCT',text='Magellan geologic mapping resolves plains, flows, tessera/upland, volcanic and impact units',rep='REGION_REPRESENTATIVE',region=vs,product=vg)
Q('R_V13_BASALT','VENUS','LANDER_ROCK_COMPOSITION','MODEL_INFERENCE','LOCAL_SITE','VENUS_MINERAL','MODEL',text='Venera 13 geochemistry consistent with silica-undersaturated/alkali basalt under normative assumptions',rep='SITE_ONLY',region=v13,notes='mineralogy not directly measured')
Q('R_V14_BASALT','VENUS','LANDER_ROCK_COMPOSITION','MODEL_INFERENCE','LOCAL_SITE','VENUS_MINERAL','MODEL',text='Venera 14 major-element chemistry consistent with olivine-tholeiitic basalt under normative assumptions',rep='SITE_ONLY',region=v14)
Q('R_VEGA2_BASALT','VENUS','LANDER_ROCK_COMPOSITION','MODEL_INFERENCE','LOCAL_SITE','VENUS_MINERAL','MODEL',text='Vega 2 chemistry broadly basaltic/tholeiitic but weathered and sulfate-rich',rep='SITE_ONLY',region=vg2)
Q('R_VENUS_WEATHER','VENUS','SURFACE_ATMOSPHERE_WEATHERING','MODEL_INFERENCE','LOCAL_SITE','VENUS_MINERAL','MODEL',text='lander sulfur, density and spectral constraints are consistent with weathered basaltic clastic material containing hematite and sulfate',rep='SITE_ONLY',region=v14)
Q('R_VENUS_CHANGE_SIF','VENUS','RADAR_BACKSCATTER_CHANGE','REAL_EVIDENCE','REGION','VENUS_VOLC_2024','DETECTION',text='cycle-to-cycle radar backscatter differences reported at volcanic-related flow features',rep='REGION_REPRESENTATIVE',region=vs,method='Magellan SAR change comparison')
Q('R_VENUS_CHANGE_NIOBE','VENUS','RADAR_BACKSCATTER_CHANGE','REAL_EVIDENCE','REGION','VENUS_VOLC_2024','DETECTION',text='cycle-to-cycle radar backscatter differences reported at volcanic-related flow features',rep='REGION_REPRESENTATIVE',region=vn,method='Magellan SAR change comparison')
Q('R_VENUS_ACTIVE_MODEL','VENUS','ACTIVE_VOLCANISM_INTERPRETATION','MODEL_INFERENCE','REGION','VENUS_VOLC_2024','MODEL',text='2024 interpretation: backscatter changes represent new lava flows during Magellan mapping',rep='REGION_REPRESENTATIVE',region=vs)
Q('R_VENUS_ACTIVE_CHALLENGE','VENUS','ACTIVE_VOLCANISM_INTERPRETATION','MODEL_INFERENCE','REGION','VENUS_VOLC_2026','MODEL',text='2026 challenge: reported backscatter differences can be explained by viewing geometry and do not robustly establish new flows',rep='REGION_REPRESENTATIVE',region=vs,notes='scientific conflict intentionally preserved')
# explicit conflict
aa=db.execute("select assertion_id from scientific_assertion where assertion_key='R_VENUS_ACTIVE_MODEL'").fetchone()[0]; ab=db.execute("select assertion_id from scientific_assertion where assertion_key='R_VENUS_ACTIVE_CHALLENGE'").fetchone()[0]
db.execute("insert into reconciliation(body_id,property_code,assertion_a,assertion_b,classification,reason,status) values('VENUS','ACTIVE_VOLCANISM_INTERPRETATION',?,?, 'CONFLICT','2024 new-flow interpretation challenged by 2026 viewing-geometry analysis','OPEN')",(aa,ab))
# domain coverage for added bodies
grades={'MERCURY':['STRONG','STRONG','STRONG','STRONG','STRONG','STRONG','STRONG','WEAK','NOT_APPLICABLE','MODERATE'],'VENUS':['STRONG','STRONG','STRONG','MODERATE','WEAK','STRONG','STRONG','MODERATE','STRONG','WEAK']}
for b in ['MERCURY','VENUS']:
 for dom,st in zip(domains,grades[b]):
  state='SUPPORTED' if st not in ('UNKNOWN','NOT_APPLICABLE') else st
  db.execute('insert or ignore into coverage(body_id,domain,property_or_class,state,origin,reason) values(?,?,?,?,?,?)',(b,dom,'DOMAIN_COVERAGE',state,'NEW_CHATGPT_RESEARCH','Strength='+st))
# atmosphere coverage dimension
for b,st in [('MOON','NOT_APPLICABLE'),('MARS','MODERATE'),('CERES','NOT_APPLICABLE'),('BENNU','NOT_APPLICABLE'),('JUNO','NOT_APPLICABLE'),('VARUNA','NOT_APPLICABLE'),('MERCURY','WEAK'),('VENUS','STRONG')]:
 db.execute('insert or ignore into coverage(body_id,domain,property_or_class,state,origin,reason) values(?,?,?,?,?,?)',(b,'ATMOSPHERE','DOMAIN_COVERAGE','SUPPORTED' if st not in ('NOT_APPLICABLE','UNKNOWN') else st,'NEW_CHATGPT_RESEARCH','Strength='+st))
