SS=OS_SOURCE_IDS
def OR(b,k,n,t,notes=None): return db.execute('insert into region(body_id,region_key,region_name,region_type,notes) values(?,?,?,?,?)',(b,k,n,t,notes)).lastrowid
def OP(b,r,k,t,title,src,scope='FOOTPRINT'): return db.execute('insert into spatial_product(body_id,region_id,product_key,product_type,title,source_id,coordinate_frame,scope,status) values(?,?,?,?,?,?,?,?,?)',(b,r,k,t,title,SS[src],'IAU_'+b,scope,'CANDIDATE')).lastrowid
def OO(b,r,k,method,scope,src,start=None,end=None,prod=None,notes=None): return db.execute('insert into observation(body_id,region_id,spatial_product_id,observation_key,measurement_method,scope,observation_time_start,observation_time_end,source_id,notes) values(?,?,?,?,?,?,?,?,?,?)',(b,r,prod,k,method,scope,start,end,SS[src],notes)).lastrowid
def OA(k,b,prop,ont,scope,src,kind='TEXT',text=None,num=None,unit=None,rep='UNKNOWN',region=None,obs=None,prod=None,start=None,end=None,notes=None,umin=None,umax=None):
 db.execute('''insert into scientific_assertion(assertion_key,body_id,property_code,ontology,scope,region_id,observation_id,spatial_product_id,value_kind,value_numeric,value_text,unit,uncertainty_text,value_min,value_max,epistemic_class,representativeness,valid_time_start,valid_time_end,source_id,admission_status,preferred,origin,notes) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''',(k,b,prop,ont,scope,region,obs,prod,kind,num,text,unit,None,umin,umax,'MEASURED' if ont=='REAL_EVIDENCE' else ('DERIVED' if ont=='DERIVED' else 'MODEL_INFERENCE'),rep,start,end,SS[src],'CANDIDATE',0,'NEW_CHATGPT_RESEARCH',notes))
R={}
for x in [('MIRANDA','MIR_IMG','Voyager-imaged Miranda terrain','OBSERVED_HEMISPHERE'),('MIRANDA','MIR_COR','Miranda coronae','CORONA_TERRAIN'),('ARIEL','ARI_IMG','Voyager-imaged Ariel terrain','OBSERVED_HEMISPHERE'),('UMBRIEL','UMB_IMG','Voyager-imaged Umbriel terrain','OBSERVED_HEMISPHERE'),('UMBRIEL','WUNDA','Wunda crater','IMPACT_STRUCTURE'),('TITANIA','TITN_IMG','Voyager-imaged Titania terrain','OBSERVED_HEMISPHERE'),('OBERON','OBE_IMG','Voyager-imaged Oberon terrain','OBSERVED_HEMISPHERE'),('TRITON','TRI_IMG','Voyager-imaged Triton terrain','OBSERVED_HEMISPHERE'),('TRITON','TRI_SOUTH','Triton south polar terrain','POLAR_TERRAIN'),('CHARON','CHA_ENC','New Horizons encounter hemisphere','OBSERVED_HEMISPHERE'),('CHARON','VULCAN','Vulcan Planitia','PLAIN'),('CHARON','SERENITY','Serenity Chasma system','CHASMA'),('CHARON','MORDOR','Mordor Macula','POLAR_REGION')]:
 R[(x[0],x[1])]=OR(*x)
P={}
for b,r,k,t,title,src in [('MIRANDA','MIR_IMG','MIR_VOY_MAP','IMAGERY_MOSAIC','Voyager 2 Miranda encounter imagery','URA_GEO'),('ARIEL','ARI_IMG','ARI_VOY_MAP','IMAGERY_MOSAIC','Voyager 2 Ariel encounter imagery','URA_GEO'),('UMBRIEL','UMB_IMG','UMB_VOY_MAP','IMAGERY_MOSAIC','Voyager 2 Umbriel encounter imagery','URA_GEO'),('TITANIA','TITN_IMG','TITN_VOY_MAP','IMAGERY_MOSAIC','Voyager 2 Titania encounter imagery','URA_GEO'),('OBERON','OBE_IMG','OBE_VOY_MAP','IMAGERY_MOSAIC','Voyager 2 Oberon encounter imagery','URA_GEO'),('TRITON','TRI_IMG','TRI_VOY_MAP','IMAGERY_MOSAIC','Voyager 2 Triton encounter imagery/geology','TRI_GEO'),('CHARON','CHA_ENC','CHA_NH_MAP','IMAGERY_MOSAIC','New Horizons Charon encounter imagery/geology','CHA_GEO')]:
 P[k]=OP(b,R[(b,r)],k,t,title,src)
# Uranian observations and assertions, deliberately footprint limited
for b,r,geo in [('MIRANDA','MIR_IMG','coronae, ridges, grooves, scarps and cratered terrain with strong regional resurfacing contrasts'),('ARIEL','ARI_IMG','chasmata, faulted valleys, smooth/resurfaced plains and cratered terrain'),('UMBRIEL','UMB_IMG','dark, heavily cratered terrain with limited resurfacing evidence and bright-ringed Wunda'),('TITANIA','TITN_IMG','large fault/graben/chasma systems superposed on cratered terrains'),('OBERON','OBE_IMG','heavily cratered terrain with tectonic scarps/chasmata and dark material')]:
 o=OO(b,R[(b,r)],b+'_VOYAGER_IMG','VOYAGER_2_IMAGING','FOOTPRINT','URA_GEO','1986-01','1986-01',P[b[:3]+'_VOY_MAP' if b!='TITANIA' else 'TITN_VOY_MAP'],notes='Encounter-side imaging only; unimaged terrain is not generalized')
 OA('R_'+b+'_GEO',b,'OBSERVED_GEOLOGY','REAL_EVIDENCE','FOOTPRINT','URA_GEO','DETECTION',text=geo,rep='FOOTPRINT_ONLY',region=R[(b,r)],obs=o,prod=P[b[:3]+'_VOY_MAP' if b!='TITANIA' else 'TITN_VOY_MAP'],start='1986-01',end='1986-01')
 OA('R_'+b+'_COVERAGE',b,'GEOLOGIC_COVERAGE_LIMIT','DERIVED','FOOTPRINT','URA_GEO','TEXT',text='Voyager 2 encounter geometry provides incomplete regional/hemispheric imaging; mapped morphology must not be promoted to whole-body geology',rep='FOOTPRINT_ONLY',region=R[(b,r)],obs=o)
 OA('R_'+b+'_H2O',b,'SURFACE_WATER_ICE','REAL_EVIDENCE','BODY','URA_SPEC','DETECTION',text='water-ice absorption is detected spectroscopically on the surface; detection does not establish bulk composition',rep='BODY_REPRESENTATIVE')
 if b!='MIRANDA': OA('R_'+b+'_CO2',b,'SURFACE_CO2','REAL_EVIDENCE','BODY','URA_SPEC','DETECTION',text='CO2-related spectral absorption is reported with body/hemisphere-dependent strength; detection is not global abundance',rep='BODY_REPRESENTATIVE')
# body-specific model constraints
OA('R_MIR_COR','MIRANDA','CORONAE_TECTONIC_RESURFACING','REAL_EVIDENCE','REGION','URA_GEO','DETECTION',text='Arden, Elsinore and Inverness coronae preserve intense tectonic/resurfacing morphology',rep='REGION_REPRESENTATIVE',region=R[('MIRANDA','MIR_COR')])
OA('R_MIR_HEAT','MIRANDA','PAST_HEAT_FLOW_CONSTRAINT','DERIVED','MODEL_DOMAIN','MIR_HEAT','RANGE',text='lithospheric flexure near Inverness constrains elevated past heat flow, strongly dependent on assumed ice-shell composition and porosity',rep='MODEL_DOMAIN_ONLY')
OA('R_MIR_OCEAN','MIRANDA','PAST_SUBSURFACE_OCEAN_MODEL','MODEL_INFERENCE','MODEL_DOMAIN','MIR_OCEAN','MODEL',text='geological stress modeling admits a geologically recent subsurface ocean; existence, thickness and persistence are inferred rather than observed',rep='MODEL_DOMAIN_ONLY')
OA('R_ARI_NH3','ARIEL','AMMONIATED_SPECIES_DETECTION','REAL_EVIDENCE','BODY','URA_NH3','DETECTION',text='spectra contain candidate ammonia/ammoniated-material absorptions; carrier and abundance remain uncertain',rep='BODY_REPRESENTATIVE')
OA('R_ARI_OCEAN','ARIEL','SUBSURFACE_OCEAN_MODEL','MODEL_INFERENCE','MODEL_DOMAIN','URA_INTERIOR','MODEL',text='thermal/compositional models permit a residual or past liquid layer; present ocean state is not directly observed',rep='MODEL_DOMAIN_ONLY')
OA('R_UMB_INTERIOR','UMBRIEL','INTERIOR_THERMAL_MODEL','MODEL_INFERENCE','MODEL_DOMAIN','URA_INTERIOR','MODEL',text='ice-rock interior and thermal evolution remain weakly constrained; sparse resurfacing evidence does not require Ariel-like evolution',rep='MODEL_DOMAIN_ONLY')
OA('R_TITN_OCEAN','TITANIA','SUBSURFACE_OCEAN_MODEL','MODEL_INFERENCE','MODEL_DOMAIN','URA_INTERIOR','MODEL',text='thermal evolution models admit long-lived or residual internal liquid under some compositions/heat budgets; ocean is not observed',rep='MODEL_DOMAIN_ONLY')
OA('R_OBE_OCEAN','OBERON','SUBSURFACE_OCEAN_MODEL','MODEL_INFERENCE','MODEL_DOMAIN','URA_INTERIOR','MODEL',text='thermal evolution models admit possible internal liquid under some conditions; geological evidence is sparse and present ocean state remains uncertain',rep='MODEL_DOMAIN_ONLY')
# Triton
triimg=OO('TRITON',R[('TRITON','TRI_IMG')],'TRITON_VOYAGER_IMG','VOYAGER_2_IMAGING','FOOTPRINT','TRI_GEO','1989-08-25','1989-08-25',P['TRI_VOY_MAP'],notes='Encounter hemisphere only')
trip=OO('TRITON',R[('TRITON','TRI_SOUTH')],'TRITON_VOYAGER_PLUMES','VOYAGER_2_IMAGING','REGION','TRI_GEO','1989-08-25','1989-08-25',P['TRI_VOY_MAP'],notes='Discrete active plumes and downwind deposits observed at Voyager epoch; mechanism separate')
tria=OO('TRITON',None,'TRITON_OCCULTATION_ATM','STELLAR_OCCULTATION','FOOTPRINT','TRI_ATM','1989','2017',notes='Multiple epochs constrain changing pressure/thermal structure; not timeless atmosphere')
OA('R_TRI_RETRO','TRITON','RETROGRADE_ORBIT','REAL_EVIDENCE','BODY','NEP_SPK','DETECTION',text='Triton occupies a large retrograde Neptune orbit',rep='BODY_REPRESENTATIVE')
OA('R_TRI_CAPTURE','TRITON','CAPTURED_ORIGIN','MODEL_INFERENCE','MODEL_DOMAIN','TRI_OCEAN','MODEL',text='retrograde orbit and dynamical evolution strongly motivate capture from a heliocentric source population; capture is historical inference',rep='MODEL_DOMAIN_ONLY')
OA('R_TRI_GEO','TRITON','OBSERVED_GEOLOGY','REAL_EVIDENCE','FOOTPRINT','TRI_GEO','DETECTION',text='Voyager mapped young plains, cantaloupe terrain, tectonic features, polar terrains and volatile-related landforms with low crater density',rep='FOOTPRINT_ONLY',region=R[('TRITON','TRI_IMG')],obs=triimg,prod=P['TRI_VOY_MAP'],start='1989-08-25',end='1989-08-25')
OA('R_TRI_VOL','TRITON','SURFACE_VOLATILES','REAL_EVIDENCE','BODY','TRI_SPEC','DETECTION',text='spectroscopy detects N2, CH4, CO and CO2 ices plus H2O-bearing surface components with spatial/seasonal heterogeneity',rep='BODY_REPRESENTATIVE')
OA('R_TRI_ATM','TRITON','NITROGEN_ATMOSPHERE_TEMPORAL','REAL_EVIDENCE','FOOTPRINT','TRI_ATM','DETECTION',text='Voyager and stellar occultations detect a tenuous nitrogen atmosphere with methane/thermal structure and pressure evolving across observed epochs',rep='FOOTPRINT_ONLY',obs=tria,start='1989',end='2017')
OA('R_TRI_PLUME','TRITON','ACTIVE_PLUMES_1989','REAL_EVIDENCE','REGION','TRI_GEO','DETECTION',text='Voyager directly observed active dark plumes and wind-carried deposits in south polar terrain at encounter epoch',rep='REGION_REPRESENTATIVE',region=R[('TRITON','TRI_SOUTH')],obs=trip,start='1989-08-25',end='1989-08-25')
OA('R_TRI_PLUME_MECH','TRITON','PLUME_MECHANISM_MODELS','MODEL_INFERENCE','MODEL_DOMAIN','TRI_GEO','MODEL',text='solar-driven solid-state greenhouse and endogenic mechanisms are interpretation families; 1989 activity is not generalized into eternal global plume activity',rep='MODEL_DOMAIN_ONLY')
OA('R_TRI_OCEAN','TRITON','SUBSURFACE_OCEAN_MODEL','MODEL_INFERENCE','MODEL_DOMAIN','TRI_OCEAN','MODEL',text='capture/tidal history, rock fraction and radiogenic/thermal evolution admit present subsurface-ocean models; depth, salinity and persistence remain model-dependent',rep='MODEL_DOMAIN_ONLY')
# Charon
chao=OO('CHARON',R[('CHARON','CHA_ENC')],'CHARON_NH_IMG','NEW_HORIZONS_LORRI_MVIC_LEISA','FOOTPRINT','CHA_GEO','2015-07-14','2015-07-14',P['CHA_NH_MAP'],notes='Encounter hemisphere mapped; far-side detail remains poorer')
OA('R_CHA_GEO','CHARON','OBSERVED_GEOLOGY','REAL_EVIDENCE','FOOTPRINT','CHA_GEO','DETECTION',text='New Horizons mapped cratered northern terrain, major extensional chasmata and smoother Vulcan Planitia on encounter hemisphere',rep='FOOTPRINT_ONLY',region=R[('CHARON','CHA_ENC')],obs=chao,prod=P['CHA_NH_MAP'])
OA('R_CHA_H2O','CHARON','SURFACE_WATER_ICE','REAL_EVIDENCE','BODY','CHA_COMP','DETECTION',text='water ice dominates measured Charon surface spectra',rep='BODY_REPRESENTATIVE')
OA('R_CHA_NH3','CHARON','AMMONIA_BEARING_MATERIAL','REAL_EVIDENCE','REGION','CHA_COMP','DETECTION',text='ammonia/ammonium-bearing absorptions occur regionally, including association with some fresh exposures',rep='REGION_REPRESENTATIVE',region=R[('CHARON','VULCAN')])
OA('R_CHA_MORDOR','CHARON','MORDOR_MACULA_RED_MATERIAL','REAL_EVIDENCE','REGION','CHA_POLAR','DETECTION',text='dark red northern polar material is observed at Mordor Macula',rep='REGION_REPRESENTATIVE',region=R[('CHARON','MORDOR')])
OA('R_CHA_TRANSFER','CHARON','PLUTO_VOLATILE_TRANSFER_MODEL','MODEL_INFERENCE','MODEL_DOMAIN','CHA_POLAR','MODEL',text='capture and photochemical processing of Pluto-escaping methane provides a supported model for Charon polar coloration; transport history is inferred',rep='MODEL_DOMAIN_ONLY')
OA('R_CHA_OCEAN','CHARON','ANCIENT_OCEAN_FREEZING_MODEL','MODEL_INFERENCE','MODEL_DOMAIN','CHA_GEO','MODEL',text='tectonic extension and Vulcan Planitia resurfacing are compatible with thermal evolution including ancient ocean freezing/cryovolcanism; ancient ocean history is not observed fact',rep='MODEL_DOMAIN_ONLY')
# Pluto system dynamics + sparse small moons
for b in ['STYX','NIX','KERBEROS','HYDRA']:
 OA('R_'+b+'_CIRCUMBINARY',b,'CIRCUMBINARY_ORBIT','REAL_EVIDENCE','BODY','PLU_DYN','DETECTION',text='orbit is circumbinary about the Pluto-Charon pair, not an independent Keplerian two-body orbit around Pluto',rep='BODY_REPRESENTATIVE')
 OA('R_'+b+'_FASTROT',b,'RAPID_NONSYNCHRONOUS_ROTATION','REAL_EVIDENCE','BODY','PLU_SMALL','DETECTION',text='New Horizons/HST lightcurves show rotation much faster than synchronous with large obliquity; detailed spin behavior is body-dependent',rep='BODY_REPRESENTATIVE')
 OA('R_'+b+'_SHAPE',b,'ELONGATED_SHAPE','REAL_EVIDENCE','BODY','PLU_SMALL','DETECTION',text='resolved imaging constrains an irregular highly elongated shape; small-body dimensions retain substantial uncertainty',rep='BODY_REPRESENTATIVE')
 OA('R_'+b+'_ALBEDO',b,'HIGH_ALBEDO','REAL_EVIDENCE','BODY','PLU_SMALL','DETECTION',text='high reflectance is observed and is consistent with ice-rich surfaces; albedo does not determine bulk composition',rep='BODY_REPRESENTATIVE')
 OA('R_'+b+'_INTERIOR_UNKNOWN',b,'INTERIOR_STRUCTURE','MODEL_INFERENCE','MODEL_DOMAIN','PLU_MASS','UNKNOWN',text='UNKNOWN: available mass/shape data do not justify detailed interior layering or unique bulk composition',rep='MODEL_DOMAIN_ONLY')
# Nix/Hydra better constraints; Styx/Kerberos bounds
for b in ['NIX','HYDRA']:
 OA('R_'+b+'_MASS',b,'DYNAMICAL_MASS','REAL_EVIDENCE','BODY','PLU_MASS','NUMERIC',num=2.7e16 if b=='NIX' else 3.0e16,unit='kg',rep='BODY_REPRESENTATIVE',notes='2023 dynamical solution; uncertainty retained in source')
 OA('R_'+b+'_DENS',b,'BULK_DENSITY','DERIVED','BODY','PLU_MASS','NUMERIC',num=1.0 if b=='NIX' else 1.2,unit='g/cm3',rep='BODY_REPRESENTATIVE',notes='Derived from dynamical mass plus volume; uncertainty and porosity degeneracy apply')
for b,lim in [('STYX',5e14),('KERBEROS',8e14)]:
 OA('R_'+b+'_MASS_BOUND',b,'DYNAMICAL_MASS_UPPER_BOUND','DERIVED','BODY','PLU_MASS','BOUND',text='1-sigma dynamical upper bound',unit='kg',rep='BODY_REPRESENTATIVE',umax=lim,notes='Not an exact mass or density')
# System resonance/chaos statements
OA('R_NIX_CHAOS','NIX','CHAOTIC_ROTATION','REAL_EVIDENCE','BODY','PLU_DYN','DETECTION',text='dynamical/lightcurve evidence supports chaotic rotational behavior driven by Pluto-Charon torques',rep='BODY_REPRESENTATIVE')
OA('R_HYDRA_CHAOS','HYDRA','CHAOTIC_ROTATION','REAL_EVIDENCE','BODY','PLU_DYN','DETECTION',text='dynamical/lightcurve evidence supports chaotic rotational behavior driven by Pluto-Charon torques',rep='BODY_REPRESENTATIVE')
OA('R_STYX_NIX_HYDRA_RESONANCE','STYX','THREE_BODY_RESONANCE','REAL_EVIDENCE','MODEL_DOMAIN','PLU_DYN','DETECTION',text='Styx, Nix and Hydra participate in a measured three-body resonant relation within the Pluto-Charon circumbinary system',rep='MODEL_DOMAIN_ONLY')
