#!/usr/bin/env python3
import sqlite3,pathlib,hashlib,json
R=pathlib.Path(__file__).resolve().parent; P=R/'LOOM_SOLAR_WORLD_SCIENCE_LAB_v0_1.sqlite3'
c=sqlite3.connect(P); c.execute('pragma foreign_keys=on')
tests=[]
def T(name,sql,expect=0):
 got=c.execute(sql).fetchone()[0]; tests.append((name,got,expect,got==expect))
T('foreign_key_check',"select count(*) from pragma_foreign_key_check")
T('candidate_preferred',"select count(*) from scientific_assertion where preferred=1 and admission_status<>'ADMITTED'")
T('hidden_in_science',"select count(*) from scientific_assertion where ontology in ('SCENARIO','HIDDEN_WORLD')")
T('sample_scope_without_sample',"select count(*) from scientific_assertion where scope='SAMPLE' and sample_id is null")
T('region_scope_without_region',"select count(*) from scientific_assertion where scope='REGION' and region_id is null")
T('missing_source',"select count(*) from scientific_assertion where source_id is null")
T('reserve_semantics',"select count(*) from material_evidence where abundance_semantics in ('RESERVE','RECOVERABLE_RESERVE')")
T('hidden_rows',"select count(*) from hidden_world_state")
T('world_realizations',"select count(*) from world_realization")
T('project_sites',"select count(*) from project_site")
T('deposits',"select count(*) from deposit")
T('new_research_promoted',"select count(*) from scientific_assertion where origin='NEW_CHATGPT_RESEARCH' and admission_status='ADMITTED'")
T('bad_artifact_hash',"select count(*) from source_artifact where local_path is not null and (sha256 is null or length(sha256)<>64)")
T('mercury_polar_not_body',"select count(*) from scientific_assertion where body_id='MERCURY' and property_code like 'POLAR_%' and origin='NEW_CHATGPT_RESEARCH' and scope='BODY'")
T('venus_lander_not_body',"select count(*) from scientific_assertion where body_id='VENUS' and property_code='LANDER_ROCK_COMPOSITION' and scope='BODY'")
T('venus_vertical_missing_support',"select count(*) from scientific_assertion where body_id='VENUS' and property_code in ('SULFURIC_ACID_CLOUD_VERTICAL_DOMAIN','UPPER_HAZE_VERTICAL_DOMAIN') and (vertical_coordinate_type is null or vertical_min is null or vertical_max is null or vertical_unit is null)")
T('model_inference_collapsed',"select count(*) from scientific_assertion where assertion_key in ('R_MERC_ICE','R_V13_BASALT','R_V14_BASALT','R_VEGA2_BASALT','R_VENUS_ACTIVE_MODEL','R_VENUS_ACTIVE_CHALLENGE') and ontology<>'MODEL_INFERENCE'")
T('original_six_pre_enrichment_intact',"select abs((select count(*) from scientific_assertion where body_id in ('MOON','MARS','CERES','BENNU','JUNO','VARUNA') and assertion_key not in ('R_CERES_SPC','R_CERES_GRAV70','R_CERES_HAMO','R_CERES_VIR','R_CERES_AHUNA','R_CERES_PSR','R_CERES_REGDTM','R_CERES_OCCATOR_CRYO','R_CERES_INTERIOR_HCQ','R_CERES_ERNUTET','R_CERES_EXPOSED_ICE'))-111)")
T('venus_conflict_missing',"select case when exists(select 1 from reconciliation where body_id='VENUS' and property_code='ACTIVE_VOLCANISM_INTERPRETATION' and classification='CONFLICT') then 0 else 1 end")
T('mars_moon_hierarchy',"select count(*) from body where body_id in ('PHOBOS','DEIMOS') and (parent_body_id<>'MARS' or body_class<>'NATURAL_SATELLITE')")
T('moon_origin_not_real',"select count(*) from scientific_assertion where body_id in ('PHOBOS','DEIMOS') and property_code='ORIGIN_HYPOTHESES' and ontology<>'MODEL_INFERENCE'")
T('deimos_interior_not_invented',"select count(*) from scientific_assertion where assertion_key='R_DEIMOS_INTERIOR' and value_kind<>'UNKNOWN'")
T('phobos_porosity_not_real',"select count(*) from scientific_assertion where assertion_key='R_PHOBOS_POROSITY' and ontology<>'MODEL_INFERENCE'")
T('ceres_local_not_global',"select count(*) from scientific_assertion where body_id='CERES' and property_code in ('LOCALIZED_ALIPHATIC_ORGANICS','OCCATOR_CRYOVOLCANIC_ACTIVITY_INTERPRETATION') and scope='BODY'")
T('pre_pd_eight_count_changed',"select abs((select count(*) from scientific_assertion where body_id in ('MOON','MARS','CERES','BENNU','JUNO','VARUNA','MERCURY','VENUS') and assertion_key not like 'R_CERES_SPC' and assertion_key not like 'R_CERES_GRAV70' and assertion_key not like 'R_CERES_HAMO' and assertion_key not like 'R_CERES_VIR' and assertion_key not like 'R_CERES_AHUNA' and assertion_key not like 'R_CERES_PSR' and assertion_key not like 'R_CERES_REGDTM' and assertion_key not like 'R_CERES_OCCATOR_CRYO' and assertion_key not like 'R_CERES_INTERIOR_HCQ' and assertion_key not like 'R_CERES_ERNUTET' and assertion_key not like 'R_CERES_EXPOSED_ICE')-171)")
T('vopp_not_candidate',"select count(*) from scientific_assertion where body_id in ('VESTA','JUPITER','SATURN','URANUS','NEPTUNE','PLUTO') and admission_status<>'CANDIDATE'")
T('giant_atmos_vertical_missing',"select count(*) from scientific_assertion where assertion_key in ('R_JUP_H2HE','R_JUP_CLOUD','R_SAT_ATMOS','R_URA_ATMOS','R_NEP_ATMOS','R_PLUTO_ATMOS') and (vertical_coordinate_type is null or vertical_min is null or vertical_max is null or vertical_unit is null)")
T('galileo_probe_globalized',"select count(*) from scientific_assertion where assertion_key in ('R_JUP_H2HE','R_JUP_CLOUD') and (scope<>'LOCAL_SITE' or representativeness<>'SITE_ONLY')")
T('vopp_interior_not_model',"select count(*) from scientific_assertion where assertion_key in ('R_JUP_DILUTE_CORE','R_SAT_CORE','R_URA_INTERIOR','R_NEP_INTERIOR','R_PLUTO_OCEAN','R_VESTA_DIFF') and ontology<>'MODEL_INFERENCE'")
T('ring_scope_confusion',"select count(*) from scientific_assertion where property_code='RING_SYSTEM' and body_id in ('JUPITER','SATURN','URANUS','NEPTUNE') and (scope<>'REGION' or region_id is null)")
T('pluto_time_missing',"select count(*) from scientific_assertion where assertion_key in ('R_PLUTO_ATMOS','R_PLUTO_PRESS_TIME','R_PLUTO_VOL_CYCLE') and (valid_time_start is null or valid_time_end is null)")
T('vesta_resource_invention',"select count(*) from scientific_assertion where body_id='VESTA' and property_code like '%RESOURCE%'")
T('pre_vopp_assertion_count_changed',"select abs((select count(*) from scientific_assertion where body_id in ('MOON','MARS','CERES','BENNU','JUNO','VARUNA','MERCURY','VENUS','PHOBOS','DEIMOS'))-222)")
T('fk_integrity',"select count(*) from pragma_foreign_key_check")
T('provenance_missing',"select count(*) from scientific_assertion where source_id is null or admission_status is null or origin is null")
T('eight_asteroid_not_candidate',"select count(*) from scientific_assertion where body_id in ('PSYCHE','RYUGU','ITOKAWA','EROS','LUTETIA','STEINS','MATHILDE','IDA') and admission_status<>'CANDIDATE'")
T('sample_assertion_unlinked',"select count(*) from scientific_assertion where body_id in ('RYUGU','ITOKAWA') and scope='SAMPLE' and sample_id is null")
T('sample_collection_time_missing',"select count(*) from sample where body_id in ('RYUGU','ITOKAWA') and (collection_time_start is null or collection_time_end is null)")
T('local_measurement_globalized',"select count(*) from scientific_assertion where assertion_key='R_EROS_LAND' and (scope<>'LOCAL_SITE' or representativeness<>'SITE_ONLY')")
T('porosity_as_observation',"select count(*) from scientific_assertion where assertion_key in ('R_PSY_POROSITY','R_ITO_RUBBLE','R_LUT_POR','R_MAT_POR') and ontology<>'MODEL_INFERENCE'")
T('analogue_as_direct_measurement',"select count(*) from scientific_assertion where assertion_key in ('R_PSY_METAL_MIX','R_IDA_OC','R_STEINS_ENS') and ontology<>'MODEL_INFERENCE'")
T('navigation_coverage_missing',"select 8-count(distinct body_id) from ephemeris_coverage where body_id in ('PSYCHE','RYUGU','ITOKAWA','EROS','LUTETIA','STEINS','MATHILDE','IDA')")
T('dactyl_relationship_wrong',"select count(*) from body where body_id='DACTYL' and not(body_class='NATURAL_SATELLITE' and parent_body_id='IDA')")
T('dactyl_research_creep',"select count(*) from scientific_assertion where body_id='DACTYL'")
T('pre_eight_assertion_count_changed',"select abs((select count(*) from scientific_assertion where body_id in ('MOON','MARS','CERES','BENNU','JUNO','VARUNA','MERCURY','VENUS','PHOBOS','DEIMOS','VESTA','JUPITER','SATURN','URANUS','NEPTUNE','PLUTO'))-358)")
T('eight_resource_invention',"select count(*) from scientific_assertion where body_id in ('PSYCHE','RYUGU','ITOKAWA','EROS','LUTETIA','STEINS','MATHILDE','IDA') and property_code like '%RESOURCE%'")
T('galilean_parent_wrong',"select count(*) from body where body_id in ('IO','EUROPA','GANYMEDE','CALLISTO') and parent_body_id<>'JUPITER'")
T('galilean_not_candidate',"select count(*) from scientific_assertion where body_id in ('IO','EUROPA','GANYMEDE','CALLISTO') and admission_status<>'CANDIDATE'")
T('ocean_as_real_evidence',"select count(*) from scientific_assertion where body_id in ('EUROPA','GANYMEDE','CALLISTO') and property_code='SUBSURFACE_OCEAN_MODEL' and ontology<>'MODEL_INFERENCE'")
T('interior_as_real_evidence',"select count(*) from scientific_assertion where body_id in ('IO','EUROPA','GANYMEDE','CALLISTO') and (property_code like '%INTERIOR_MODEL%' or property_code like '%ICE_LAYER_MODELS' or property_code='ICE_SHELL_MODEL_FAMILY') and ontology<>'MODEL_INFERENCE'")
T('io_transient_missing_time',"select count(*) from scientific_assertion where assertion_key='R_IO_JUNO_TIME' and (valid_time_start is null or valid_time_end is null or observation_id is null)")
T('europa_plume_globalized',"select count(*) from scientific_assertion where assertion_key in ('R_EU_PLUME','R_EU_PLUME_ND') and scope='BODY'")
T('europa_plume_time_missing',"select count(*) from scientific_assertion where assertion_key in ('R_EU_PLUME','R_EU_PLUME_ND') and (valid_time_start is null or valid_time_end is null or observation_id is null)")
T('magnetic_semantics_collapsed',"select abs((select count(*) from scientific_assertion where assertion_key in ('R_GAN_INTRINSIC','R_GAN_INDUCED'))-2)")
T('galilean_navigation_missing',"select 4-count(distinct body_id) from ephemeris_coverage where body_id in ('IO','EUROPA','GANYMEDE','CALLISTO')")
T('pre_galilean_assertion_count_changed',"select abs((select count(*) from scientific_assertion where body_id in ('MOON','MARS','CERES','BENNU','JUNO','VARUNA','MERCURY','VENUS','PHOBOS','DEIMOS','VESTA','JUPITER','SATURN','URANUS','NEPTUNE','PLUTO','PSYCHE','RYUGU','ITOKAWA','EROS','LUTETIA','STEINS','MATHILDE','IDA','DACTYL'))-504)")
T('galilean_resource_invention',"select count(*) from scientific_assertion where body_id in ('IO','EUROPA','GANYMEDE','CALLISTO') and property_code like '%RESOURCE%'")
T('regional_composition_globalized',"select count(*) from scientific_assertion where assertion_key in ('R_EU_NACL','R_EU_CO2','R_GAN_CO2','R_CAL_CO2_SURF') and scope='BODY'")
T('saturn_moons_parent_wrong',"select count(*) from body where body_id in ('MIMAS','ENCELADUS','TETHYS','DIONE','RHEA','TITAN','IAPETUS') and parent_body_id<>'SATURN'")
T('saturn_moons_not_candidate',"select count(*) from scientific_assertion where body_id in ('MIMAS','ENCELADUS','TETHYS','DIONE','RHEA','TITAN','IAPETUS') and admission_status<>'CANDIDATE'")
T('saturn_ocean_as_real',"select count(*) from scientific_assertion where body_id in ('MIMAS','ENCELADUS','DIONE','TITAN') and property_code like '%OCEAN%' and ontology<>'MODEL_INFERENCE'")
T('enceladus_plume_scope_wrong',"select count(*) from scientific_assertion where assertion_key='R_ENC_PLUME' and (scope<>'REGION' or observation_id is null or valid_time_start is null or valid_time_end is null)")
T('enceladus_plume_bulk_ocean',"select count(*) from scientific_assertion where assertion_key in ('R_ENC_SALT','R_ENC_SILICA','R_ENC_H2','R_ENC_P','R_ENC_ORG') and representativeness not in ('FOOTPRINT_ONLY','SITE_ONLY')")
T('titan_vertical_support_missing',"select count(*) from scientific_assertion where assertion_key in ('R_TIT_ATM_PROFILE','R_TIT_ATM_COMP') and (vertical_coordinate_type is null or observation_id is null)")
T('huygens_globalized',"select count(*) from scientific_assertion where assertion_key='R_TIT_HUY_SITE' and (scope<>'LOCAL_SITE' or representativeness<>'SITE_ONLY')")
T('titan_sea_resource_invention',"select count(*) from scientific_assertion where body_id='TITAN' and (property_code like '%RESOURCE%' or property_code like '%RESERVE%')")
T('iapetus_heterogeneity_lost',"select abs((select count(*) from scientific_assertion where assertion_key in ('R_IAP_DARK','R_IAP_BRIGHT') and scope='REGION')-2)")
T('mimas_ocean_not_qualified',"select count(*) from scientific_assertion where assertion_key='R_MIM_OCEAN' and ontology<>'MODEL_INFERENCE'")
T('saturn_navigation_missing',"select 7-count(distinct body_id) from ephemeris_coverage where body_id in ('MIMAS','ENCELADUS','TETHYS','DIONE','RHEA','TITAN','IAPETUS')")
T('pre_saturn_assertion_count_changed',"select abs((select count(*) from scientific_assertion where body_id in ('MOON','MARS','CERES','BENNU','JUNO','VARUNA','MERCURY','VENUS','PHOBOS','DEIMOS','VESTA','JUPITER','SATURN','URANUS','NEPTUNE','PLUTO','PSYCHE','RYUGU','ITOKAWA','EROS','LUTETIA','STEINS','MATHILDE','IDA','DACTYL','IO','EUROPA','GANYMEDE','CALLISTO'))-586)")
T('saturn_resource_invention',"select count(*) from scientific_assertion where body_id in ('MIMAS','ENCELADUS','TETHYS','DIONE','RHEA','TITAN','IAPETUS') and (property_code like '%RESOURCE%' or property_code like '%RESERVE%')")
T('outer_parent_wrong',"select count(*) from body where (body_id in ('MIRANDA','ARIEL','UMBRIEL','TITANIA','OBERON') and parent_body_id<>'URANUS') or (body_id='TRITON' and parent_body_id<>'NEPTUNE') or (body_id in ('CHARON','STYX','NIX','KERBEROS','HYDRA') and parent_body_id<>'PLUTO')")
T('outer_not_candidate',"select count(*) from scientific_assertion where body_id in ('MIRANDA','ARIEL','UMBRIEL','TITANIA','OBERON','TRITON','CHARON','STYX','NIX','KERBEROS','HYDRA') and admission_status<>'CANDIDATE'")
T('outer_ocean_as_real',"select count(*) from scientific_assertion where body_id in ('MIRANDA','ARIEL','TITANIA','OBERON','TRITON','CHARON') and property_code like '%OCEAN%' and ontology='REAL_EVIDENCE'")
T('triton_atmosphere_time_missing',"select count(*) from scientific_assertion where assertion_key='R_TRI_ATM' and (valid_time_start is null or valid_time_end is null or observation_id is null)")
T('triton_plume_globalized',"select count(*) from scientific_assertion where assertion_key='R_TRI_PLUME' and (scope<>'REGION' or valid_time_start is null or valid_time_end is null)")
T('uranus_imaging_globalized',"select count(*) from scientific_assertion where assertion_key in ('R_MIRANDA_GEO','R_ARIEL_GEO','R_UMBRIEL_GEO','R_TITANIA_GEO','R_OBERON_GEO') and (scope<>'FOOTPRINT' or representativeness<>'FOOTPRINT_ONLY')")
T('small_pluto_false_precision',"select count(*) from scientific_assertion where body_id in ('STYX','KERBEROS') and property_code in ('BULK_DENSITY','DYNAMICAL_MASS') and value_kind='NUMERIC'")
T('small_pluto_unknown_missing',"select 4-count(*) from scientific_assertion where body_id in ('STYX','NIX','KERBEROS','HYDRA') and property_code='INTERIOR_STRUCTURE' and value_kind='UNKNOWN'")
T('pluto_circumbinary_missing',"select 4-count(*) from scientific_assertion where body_id in ('STYX','NIX','KERBEROS','HYDRA') and property_code='CIRCUMBINARY_ORBIT'")
T('outer_navigation_missing',"select 11-count(distinct body_id) from ephemeris_coverage where body_id in ('MIRANDA','ARIEL','UMBRIEL','TITANIA','OBERON','TRITON','CHARON','STYX','NIX','KERBEROS','HYDRA')")
T('pre_outer_assertion_count_changed',"select abs((select count(*) from scientific_assertion where body_id not in ('MIRANDA','ARIEL','UMBRIEL','TITANIA','OBERON','TRITON','CHARON','STYX','NIX','KERBEROS','HYDRA'))-711)")
T('outer_resource_invention',"select count(*) from scientific_assertion where body_id in ('MIRANDA','ARIEL','UMBRIEL','TITANIA','OBERON','TRITON','CHARON','STYX','NIX','KERBEROS','HYDRA') and (property_code like '%RESOURCE%' or property_code like '%RESERVE%')")
# hostile transaction fixtures must fail
hostile=[]
def reject(name,sql):
 try:
  c.execute('savepoint h'); c.execute(sql); c.execute('rollback to h'); hostile.append((name,False))
 except sqlite3.DatabaseError:
  try:c.execute('rollback to h')
  except:pass
  hostile.append((name,True))
reject('candidate_cannot_be_preferred',"insert into scientific_assertion(assertion_key,body_id,property_code,ontology,scope,value_kind,value_text,epistemic_class,representativeness,source_id,admission_status,preferred,origin) values('BAD1','MOON','X','REAL_EVIDENCE','BODY','TEXT','x','MEASURED','BODY_REPRESENTATIVE',1,'CANDIDATE',1,'TEST_FIXTURE_ONLY')")
reject('sample_requires_sample_id',"insert into scientific_assertion(assertion_key,body_id,property_code,ontology,scope,value_kind,value_text,epistemic_class,representativeness,source_id,admission_status,origin) values('BAD2','BENNU','X','REAL_EVIDENCE','SAMPLE','TEXT','x','MEASURED','SAMPLE_ONLY',1,'CANDIDATE','TEST_FIXTURE_ONLY')")
reject('science_ontology_rejects_hidden',"insert into scientific_assertion(assertion_key,body_id,property_code,ontology,scope,value_kind,value_text,epistemic_class,representativeness,source_id,admission_status,origin) values('BAD3','MOON','X','HIDDEN_WORLD','BODY','TEXT','x','MODEL','UNKNOWN',1,'CANDIDATE','TEST_FIXTURE_ONLY')")
reject('material_reserve_semantics_rejected',"insert into material_evidence(body_id,material_family,evidence_class,abundance_semantics,scope,representativeness,source_id,admission_status,origin) values('MOON','water','REMOTE','RESERVE','BODY','UNKNOWN',1,'CANDIDATE','TEST_FIXTURE_ONLY')")
ok=all(x[3] for x in tests) and all(x[1] for x in hostile)
print(json.dumps({'pass':ok,'tests':tests,'hostile':hostile,'sha256':hashlib.sha256(P.read_bytes()).hexdigest(),'size':P.stat().st_size},indent=2))
raise SystemExit(0 if ok else 1)
