S=VOPP_SOURCE_IDS
def R(b,k,n,t,notes=None): return db.execute('insert into region(body_id,region_key,region_name,region_type,notes) values(?,?,?,?,?)',(b,k,n,t,notes)).lastrowid
def P(b,r,k,t,title,src,scope='BODY'): return db.execute('insert into spatial_product(body_id,region_id,product_key,product_type,title,source_id,scope,status) values(?,?,?,?,?,?,?,?)',(b,r,k,t,title,S[src],scope,'CANDIDATE')).lastrowid
def O(b,r,k,src,scope='MODEL_DOMAIN',method=None,start=None,end=None,vtype=None,vmin=None,vmax=None,vunit=None,datum=None,notes=None):
 return db.execute('''insert into observation(body_id,region_id,observation_key,measurement_method,scope,observation_time_start,observation_time_end,vertical_coordinate_type,vertical_min,vertical_max,vertical_unit,vertical_datum,source_id,notes) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)''',(b,r,k,method,scope,start,end,vtype,vmin,vmax,vunit,datum,S[src],notes)).lastrowid
def A(key,b,prop,ont,scope,src,kind='TEXT',num=None,text=None,unit=None,rep='UNKNOWN',region=None,obs=None,prod=None,vtype=None,vmin=None,vmax=None,vunit=None,datum=None,start=None,end=None,notes=None):
 db.execute('''insert into scientific_assertion(assertion_key,body_id,property_code,ontology,scope,region_id,observation_id,spatial_product_id,value_kind,value_numeric,value_text,unit,vertical_coordinate_type,vertical_min,vertical_max,vertical_unit,vertical_datum,epistemic_class,representativeness,valid_time_start,valid_time_end,source_id,admission_status,preferred,origin,notes) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''',(key,b,prop,ont,scope,region,obs,prod,kind,num,text,unit,vtype,vmin,vmax,vunit,datum,'MEASURED' if ont=='REAL_EVIDENCE' else 'MODEL_INFERENCE',rep,start,end,S[src],'CANDIDATE',0,'NEW_CHATGPT_RESEARCH',notes))
# Regions/domains
vr=R('VESTA','RHEASILVIA','Rheasilvia basin','REGION'); vv=R('VESTA','VENENEIA','Veneneia basin','REGION'); vg=R('VESTA','VESTA_GLOBAL','Vesta mapped surface','REGION')
jr=R('JUPITER','JUPITER_ATMOS','Jupiter atmosphere','ATMOSPHERIC_DOMAIN'); ji=R('JUPITER','JUPITER_INTERIOR','Jupiter interior','INTERIOR_DOMAIN'); jring=R('JUPITER','JUPITER_RINGS','Jupiter ring system','ASSOCIATED_STRUCTURE')
sr=R('SATURN','SATURN_ATMOS','Saturn atmosphere','ATMOSPHERIC_DOMAIN'); si=R('SATURN','SATURN_INTERIOR','Saturn interior','INTERIOR_DOMAIN'); sring=R('SATURN','SATURN_RINGS','Saturn ring system','ASSOCIATED_STRUCTURE')
ur=R('URANUS','URANUS_ATMOS','Uranus atmosphere','ATMOSPHERIC_DOMAIN'); ui=R('URANUS','URANUS_INTERIOR','Uranus interior','INTERIOR_DOMAIN'); uring=R('URANUS','URANUS_RINGS','Uranus ring system','ASSOCIATED_STRUCTURE')
nr=R('NEPTUNE','NEPTUNE_ATMOS','Neptune atmosphere','ATMOSPHERIC_DOMAIN'); ni=R('NEPTUNE','NEPTUNE_INTERIOR','Neptune interior','INTERIOR_DOMAIN'); nring=R('NEPTUNE','NEPTUNE_RINGS','Neptune ring system','ASSOCIATED_STRUCTURE')
sp=R('PLUTO','SPUTNIK','Sputnik Planitia','REGION'); pg=R('PLUTO','PLUTO_ENCOUNTER','New Horizons encounter hemisphere','REGION'); pa=R('PLUTO','PLUTO_ATMOS','Pluto atmosphere','ATMOSPHERIC_DOMAIN'); pi=R('PLUTO','PLUTO_INTERIOR','Pluto interior','INTERIOR_DOMAIN')
# Spatial products
vmap=P('VESTA',vg,'VESTA_DAWN_GLOBAL','MULTI_INSTRUMENT_MAP','Dawn FC/VIR/GRaND global and regional Vesta conditioning products','VESTA_DAWN_PDS','REGION')
pgeo=P('PLUTO',pg,'PLUTO_NH_GEOLOGY','GEOLOGIC_MAP','New Horizons Pluto encounter-hemisphere geology/cartography','PLUTO_NH_GEO','REGION')
pcomp=P('PLUTO',pg,'PLUTO_NH_COMPOSITION','COMPOSITION_MAP','New Horizons LEISA/MVIC regional surface composition maps','PLUTO_NH_COMP','REGION')
# Vesta
A('R_VESTA_GEO','VESTA','GLOBAL_GEOLOGIC_COMPLEXITY','REAL_EVIDENCE','REGION','VESTA_GEOLOGY',text='Dawn mapped Rheasilvia, older Veneneia, equatorial/northern troughs and heterogeneous impact terrains',rep='REGION_REPRESENTATIVE',region=vg,prod=vmap)
A('R_VESTA_RHEA','VESTA','RHEASILVIA_BASIN','REAL_EVIDENCE','REGION','VESTA_GEOLOGY','DETECTION',text='giant south-polar impact basin with central uplift and deep excavation',rep='REGION_REPRESENTATIVE',region=vr)
A('R_VESTA_DIFF','VESTA','DIFFERENTIATED_INTERIOR','MODEL_INFERENCE','MODEL_DOMAIN','VESTA_GEOLOGY','MODEL',text='Dawn gravity plus HED petrology support differentiated crust/mantle/core; core radius constrained roughly 110-130 km',rep='MODEL_DOMAIN_ONLY')
A('R_VESTA_HED','VESTA','HED_PARENT_BODY_LINK','MODEL_INFERENCE','MODEL_DOMAIN','VESTA_OVERVIEW','MODEL',text='Dawn mineralogy/geochemistry strongly supports Vesta as parent body of HED meteorites',rep='MODEL_DOMAIN_ONLY',notes='meteorite linkage constrains lithologies but is not cubic-metre global omniscience')
A('R_VESTA_PYX','VESTA','PYROXENE_LITHOLOGIC_HETEROGENEITY','REAL_EVIDENCE','REGION','VESTA_OVERVIEW','DETECTION',text='VIR maps HED-like pyroxene lithologies with regional eucritic/diogenitic variation',rep='REGION_REPRESENTATIVE',region=vg)
A('R_VESTA_H','VESTA','HYDROGEN_DARK_MATERIAL_ASSOCIATION','REAL_EVIDENCE','REGION','VESTA_GEOLOGY',text='GRaND hydrogen distribution correlates with dark/exogenic carbonaceous material and surface age',rep='REGION_REPRESENTATIVE',region=vg,notes='not a global water inventory or resource stock')
# Jupiter
jprobe=O('JUPITER',jr,'JUPITER_GALILEO_PROBE','JUPITER_GALILEO','LOCAL_SITE','in-situ probe descent','1995-12-07','1995-12-07','PRESSURE_LEVEL',0.1,22,'bar','atmospheric pressure', 'single probe trajectory; not global')
A('R_JUP_H2HE','JUPITER','ATMOSPHERIC_H2_HE','REAL_EVIDENCE','LOCAL_SITE','JUPITER_GALILEO',text='Galileo probe directly measured hydrogen-helium dominated atmosphere plus trace species along one descent path',rep='SITE_ONLY',region=jr,obs=jprobe,vtype='PRESSURE_LEVEL',vmin=.1,vmax=22,vunit='bar',datum='atmospheric pressure',start='1995-12-07',end='1995-12-07')
A('R_JUP_CLOUD','JUPITER','VERTICAL_ATMOSPHERIC_STRUCTURE','REAL_EVIDENCE','LOCAL_SITE','JUPITER_GALILEO',text='probe pressure-temperature/composition profile constrains vertical structure along entry site',rep='SITE_ONLY',region=jr,obs=jprobe,vtype='PRESSURE_LEVEL',vmin=.1,vmax=22,vunit='bar',datum='atmospheric pressure',start='1995-12-07',end='1995-12-07')
A('R_JUP_DEEP_WINDS','JUPITER','DEEP_DIFFERENTIAL_ROTATION','MODEL_INFERENCE','MODEL_DOMAIN','JUPITER_JUNO_GRAV','MODEL',text='odd gravity harmonics imply zonal winds extend thousands of kilometres below cloud level',rep='MODEL_DOMAIN_ONLY',region=ji)
A('R_JUP_DILUTE_CORE','JUPITER','DILUTE_CORE_MODEL','MODEL_INFERENCE','MODEL_DOMAIN','JUPITER_JUNO_CORE','MODEL',text='Juno gravity-compatible interior families include extended/dilute heavy-element core rather than a uniquely bounded compact core',rep='MODEL_DOMAIN_ONLY',region=ji)
A('R_JUP_MAG','JUPITER','MAGNETIC_FIELD_STRUCTURE','REAL_EVIDENCE','MODEL_DOMAIN','JUPITER_JUNO_MAG',text='Juno magnetic observations reveal strong spatially complex internal field',rep='MODEL_DOMAIN_ONLY')
A('R_JUP_RINGS','JUPITER','RING_SYSTEM','REAL_EVIDENCE','REGION','PDS_RINGS','DETECTION',text='faint associated ring system retained as separate physical structure, not atmosphere/interior',rep='REGION_REPRESENTATIVE',region=jring)
# Saturn
A('R_SAT_GRAV','SATURN','GRAVITY_AND_DEEP_ROTATION_CONSTRAINT','REAL_EVIDENCE','MODEL_DOMAIN','SATURN_CASSINI_GRAV',text='Cassini Grand Finale gravity harmonics constrain deep differential rotation and interior models',rep='MODEL_DOMAIN_ONLY',region=si)
A('R_SAT_RING_MASS','SATURN','RING_MASS_GRAVITY_CONSTRAINT','REAL_EVIDENCE','REGION','SATURN_CASSINI_GRAV',text='Cassini gravity separates a finite ring-system mass constraint from Saturn body mass',rep='REGION_REPRESENTATIVE',region=sring)
A('R_SAT_CORE','SATURN','DIFFUSE_CORE_MODEL','MODEL_INFERENCE','MODEL_DOMAIN','SATURN_CORE','MODEL',text='ring seismology supports a stably stratified diffuse/fuzzy core extending a substantial fraction of Saturn radius',rep='MODEL_DOMAIN_ONLY',region=si)
satobs=O('SATURN',sr,'SATURN_CIRS_PROFILE','SATURN_CIRS','MODEL_DOMAIN','Cassini infrared remote sounding','2004-07-01','2017-09-15','PRESSURE_LEVEL',.001,10,'bar','atmospheric pressure','mission-era vertically and temporally resolved atmosphere')
A('R_SAT_ATMOS','SATURN','ATMOSPHERIC_VERTICAL_STRUCTURE','REAL_EVIDENCE','MODEL_DOMAIN','SATURN_CIRS',text='Cassini infrared sounding constrains pressure-dependent temperature/composition and temporal/latitudinal variability',rep='MODEL_DOMAIN_ONLY',region=sr,obs=satobs,vtype='PRESSURE_LEVEL',vmin=.001,vmax=10,vunit='bar',datum='atmospheric pressure',start='2004-07-01',end='2017-09-15')
A('R_SAT_RINGS','SATURN','RING_SYSTEM','REAL_EVIDENCE','REGION','PDS_RINGS','DETECTION',text='radially structured particle ring system is an associated structure distinct from atmosphere and interior',rep='REGION_REPRESENTATIVE',region=sring)
# Uranus
uobs=O('URANUS',ur,'URANUS_VOYAGER_PROFILE','URANUS_VOYAGER','MODEL_DOMAIN','Voyager 2 radio/IR/remote sensing','1986-01-24','1986-01-24','PRESSURE_LEVEL',.1,10,'bar','atmospheric pressure','encounter-epoch constraint')
A('R_URA_ATMOS','URANUS','ATMOSPHERIC_VERTICAL_STRUCTURE','REAL_EVIDENCE','MODEL_DOMAIN','URANUS_VOYAGER',text='H2/He atmosphere with methane and vertically structured clouds/hazes constrained at Voyager encounter epoch',rep='MODEL_DOMAIN_ONLY',region=ur,obs=uobs,vtype='PRESSURE_LEVEL',vmin=.1,vmax=10,vunit='bar',datum='atmospheric pressure',start='1986-01-24',end='1986-01-24')
A('R_URA_INTERIOR','URANUS','INTERIOR_MODEL_FAMILIES','MODEL_INFERENCE','MODEL_DOMAIN','URANUS_INTERIOR','MODEL',text='multiple rock/heavy-element/fluid composition-gradient and thermal-evolution models remain compatible with sparse gravity constraints',rep='MODEL_DOMAIN_ONLY',region=ui)
A('R_URA_HEAT','URANUS','LOW_INTERNAL_HEAT','REAL_EVIDENCE','BODY','URANUS_INTERIOR',text='unusually low emitted internal heat is an empirical boundary condition on thermal-evolution models',rep='BODY_REPRESENTATIVE')
A('R_URA_MAG','URANUS','MAGNETIC_FIELD_GEOMETRY','REAL_EVIDENCE','MODEL_DOMAIN','URANUS_VOYAGER',text='strongly tilted and offset non-dipolar magnetic geometry measured by Voyager 2',rep='MODEL_DOMAIN_ONLY')
A('R_URA_RINGS','URANUS','RING_SYSTEM','REAL_EVIDENCE','REGION','PDS_RINGS','DETECTION',text='narrow ring system represented separately from planetary envelope',rep='REGION_REPRESENTATIVE',region=uring)
# Neptune
nobs=O('NEPTUNE',nr,'NEPTUNE_VOYAGER_PROFILE','NEPTUNE_VOYAGER','MODEL_DOMAIN','Voyager 2 remote sensing/radio','1989-08-25','1989-08-25','PRESSURE_LEVEL',.1,10,'bar','atmospheric pressure','encounter-epoch constraint')
A('R_NEP_ATMOS','NEPTUNE','ATMOSPHERIC_VERTICAL_STRUCTURE','REAL_EVIDENCE','MODEL_DOMAIN','NEPTUNE_VOYAGER',text='H2/He atmosphere with methane, clouds and vigorous winds/storms constrained at Voyager encounter epoch',rep='MODEL_DOMAIN_ONLY',region=nr,obs=nobs,vtype='PRESSURE_LEVEL',vmin=.1,vmax=10,vunit='bar',datum='atmospheric pressure',start='1989-08-25',end='1989-08-25')
A('R_NEP_HEAT','NEPTUNE','INTERNAL_HEAT_FLUX','REAL_EVIDENCE','BODY','NEPTUNE_INTERIOR',text='substantial intrinsic heat emission constrains thermal evolution independently from Uranus',rep='BODY_REPRESENTATIVE')
A('R_NEP_INTERIOR','NEPTUNE','INTERIOR_MODEL_FAMILIES','MODEL_INFERENCE','MODEL_DOMAIN','NEPTUNE_INTERIOR','MODEL',text='rock/heavy-element/fluid-envelope distributions remain model-dependent under limited gravity harmonics',rep='MODEL_DOMAIN_ONLY',region=ni)
A('R_NEP_MAG','NEPTUNE','MAGNETIC_FIELD_GEOMETRY','REAL_EVIDENCE','MODEL_DOMAIN','NEPTUNE_VOYAGER',text='tilted, offset and multipolar magnetic field measured by Voyager 2',rep='MODEL_DOMAIN_ONLY')
A('R_NEP_RINGS','NEPTUNE','RING_SYSTEM','REAL_EVIDENCE','REGION','PDS_RINGS','DETECTION',text='faint ring system with arc structure represented separately from envelope',rep='REGION_REPRESENTATIVE',region=nring)
# Pluto
A('R_PLUTO_GEO','PLUTO','REGIONAL_GEOLOGY','REAL_EVIDENCE','REGION','PLUTO_NH_GEO','SPATIAL_PRODUCT',text='New Horizons mapped diverse terrains including Sputnik Planitia, mountains, tectonics, cratered units and candidate cryovolcanic constructs',rep='REGION_REPRESENTATIVE',region=pg,prod=pgeo,start='2015-07-14',end='2015-07-14')
A('R_PLUTO_SP','PLUTO','SPUTNIK_N2_GLACIER','REAL_EVIDENCE','REGION','PLUTO_NH_COMP','DETECTION',text='Sputnik Planitia hosts a large nitrogen-rich volatile-ice glacier with CO and CH4 components',rep='REGION_REPRESENTATIVE',region=sp,prod=pcomp,start='2015-07-14',end='2015-07-14')
A('R_PLUTO_COMP','PLUTO','SURFACE_VOLATILE_HETEROGENEITY','REAL_EVIDENCE','REGION','PLUTO_NH_COMP',text='spatially resolved N2, CH4, CO and H2O ice distributions are heterogeneous across encounter hemisphere',rep='REGION_REPRESENTATIVE',region=pg,prod=pcomp,start='2015-07-14',end='2015-07-14')
patm=O('PLUTO',pa,'PLUTO_NH_OCCULTATION','PLUTO_ATMOS_PROFILE','MODEL_DOMAIN','New Horizons solar occultation','2015-07-14','2015-07-14','ALTITUDE',0,1600,'km','Pluto reference radius','encounter atmospheric profile')
A('R_PLUTO_ATMOS','PLUTO','ATMOSPHERIC_PROFILE','REAL_EVIDENCE','MODEL_DOMAIN','PLUTO_ATMOS_PROFILE',text='N2-dominated extended atmosphere with CH4 and photochemical products/haze; vertically resolved New Horizons profile',rep='MODEL_DOMAIN_ONLY',region=pa,obs=patm,vtype='ALTITUDE',vmin=0,vmax=1600,vunit='km',datum='Pluto reference radius',start='2015-07-14',end='2015-07-14')
A('R_PLUTO_PRESS_TIME','PLUTO','ATMOSPHERIC_PRESSURE_EVOLUTION','REAL_EVIDENCE','MODEL_DOMAIN','PLUTO_PRESSURE_TIME',text='stellar occultations show epoch-dependent pressure evolution from 1988 through 2016; not an eternal scalar pressure',rep='MODEL_DOMAIN_ONLY',region=pa,start='1988-01-01',end='2016-12-31')
A('R_PLUTO_VOL_CYCLE','PLUTO','VOLATILE_TRANSPORT_MODEL','MODEL_INFERENCE','MODEL_DOMAIN','PLUTO_VOLATILE_MODEL','MODEL',text='seasonal/orbital transport models couple N2/CH4/CO frost migration, topography and atmospheric pressure',rep='MODEL_DOMAIN_ONLY',start='1988-01-01',end='2016-12-31')
A('R_PLUTO_OCEAN','PLUTO','SUBSURFACE_OCEAN_MODEL','MODEL_INFERENCE','MODEL_DOMAIN','PLUTO_OCEAN','MODEL',text='Sputnik Planitia reorientation/mass-anomaly arguments are compatible with an extant or past subsurface ocean; not direct detection',rep='MODEL_DOMAIN_ONLY',region=pi)
# coverage records for new bodies
dims=['NAVIGATION_DYNAMICS','PHYSICAL','GEOLOGICAL','ATMOSPHERE','COMPOSITION','VOLATILES','ENVIRONMENTAL','SPATIAL','INTERIOR','MAGNETIC','RINGS_ASSOCIATED','MECHANICAL_GEOTECHNICAL','SAMPLE_IN_SITU','RESOURCE_RELEVANCE']
grades={
'VESTA':['STRONG','STRONG','STRONG','NOT_APPLICABLE','STRONG','MODERATE','MODERATE','STRONG','MODERATE','WEAK','NOT_APPLICABLE','WEAK','MODERATE','WEAK'],
'JUPITER':['STRONG','STRONG','NOT_APPLICABLE','STRONG','STRONG','MODERATE','STRONG','STRONG','MODERATE','STRONG','MODERATE','NOT_APPLICABLE','MODERATE','NOT_APPLICABLE'],
'SATURN':['STRONG','STRONG','NOT_APPLICABLE','STRONG','MODERATE','WEAK','STRONG','STRONG','MODERATE','STRONG','STRONG','NOT_APPLICABLE','MODERATE','NOT_APPLICABLE'],
'URANUS':['STRONG','STRONG','NOT_APPLICABLE','MODERATE','MODERATE','WEAK','MODERATE','MODERATE','WEAK','MODERATE','MODERATE','NOT_APPLICABLE','WEAK','NOT_APPLICABLE'],
'NEPTUNE':['STRONG','STRONG','NOT_APPLICABLE','MODERATE','MODERATE','WEAK','MODERATE','MODERATE','WEAK','MODERATE','MODERATE','NOT_APPLICABLE','WEAK','NOT_APPLICABLE'],
'PLUTO':['STRONG','STRONG','STRONG','STRONG','STRONG','STRONG','MODERATE','STRONG','WEAK','UNKNOWN','NOT_APPLICABLE','WEAK','MODERATE','WEAK']}
for b,gs in grades.items():
 for dom,g in zip(dims,gs): db.execute('insert or ignore into coverage(body_id,domain,property_or_class,state,origin,reason) values(?,?,?,?,?,?)',(b,dom,'DOMAIN_COVERAGE','SUPPORTED' if g not in ('UNKNOWN','NOT_APPLICABLE') else g,'NEW_CHATGPT_RESEARCH','Strength='+g))
