#!/usr/bin/env python3
"""Offline deterministic two-pass reconciliation qualification and reporting."""
from __future__ import annotations
import hashlib, importlib.util, json, shutil, sqlite3, subprocess, sys, tempfile, time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; HERE=Path(__file__).resolve().parent; REPORTS=HERE/'reports'
def load():
 s=importlib.util.spec_from_file_location('reconcile',HERE/'reconcile.py');m=importlib.util.module_from_spec(s);sys.modules[s.name]=m;s.loader.exec_module(m);return m
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 start=time.perf_counter(); REPORTS.mkdir(exist_ok=True)
 subprocess.run([sys.executable,str(HERE/'capture_inputs.py')],check=True,capture_output=True,text=True)
 mod=load(); src=ROOT/'dev/solar_baseline_01/LOOM_SOLAR_BASELINE_01_CANDIDATE_V20.sqlite3'; identity=HERE/'raw/naif_ids_required_reading.html'
 with tempfile.TemporaryDirectory(prefix='solar01r-replay-') as td:
  t=Path(td); r1=mod.build(src,t/'forward.sqlite3',t/'forward_reports',False,identity); r2=mod.build(src,t/'repeat.sqlite3',t/'repeat_reports',False,identity); rr=mod.build(src,t/'reverse.sqlite3',t/'reverse_reports',True,identity)
  byte_identical=sha(t/'forward.sqlite3')==sha(t/'repeat.sqlite3')
  semantic_equal=r1['semantic_digest']==r2['semantic_digest']==rr['semantic_digest']
  shutil.copy2(t/'forward.sqlite3',HERE/'LOOM_SOLAR_BASELINE_01R_RECONCILIATION_LEDGER.sqlite3')
  shutil.copy2(t/'forward_reports/reconciliation_report.json',REPORTS/'reconciliation_report.json')
  shutil.copy2(t/'forward_reports/identity_resolution.json',REPORTS/'identity_resolution.json')
  shutil.copy2(t/'forward_reports/conflict_report.json',REPORTS/'conflict_report.json')
 baseline=sqlite3.connect(src);baseline.row_factory=sqlite3.Row
 control=baseline.execute("select count(*) from candidate_assertion where body_id in ('CERES','COMET_67P','EUROPA') and preferred_fact<>0").fetchone()[0]
 orig=baseline.execute('select count(*) from candidate_assertion').fetchone()[0];baseline.close()
 # Baseline control hashes/digests are independently frozen and rechecked.
 freeze=json.loads((REPORTS/'input_freeze.json').read_text())
 sf=ROOT/freeze['sf_promote_03']['path'];sfmod=importlib.util.spec_from_file_location('sf03_verify',ROOT/'dev/solar_facts_multi_body/sf_promote_03_europa_ceres_67p/sf03_qualify.py');sm=importlib.util.module_from_spec(sfmod);sys.modules[sfmod.name]=sm;sfmod.loader.exec_module(sm)
 post={b:sm.body_digest(sf,b) for b in ('CERES','COMET_67P','EUROPA')}
 unchanged=post=={b:freeze['sf_promote_03']['semantic_digests'][b] for b in post}
 # Gain matrix is a lightweight, evidence-qualified prioritization, not imported data.
 gain={"mission_id":"SOLAR-BASELINE-01R","method":"weighted ordinal score (0-5 each): unresolved-lane gain 35%, bodies/acquisition 20%, primary authority 15%, machine readability 15%, deterministic mapping 10%, low cost 5%; estimates are qualitative and not lane counts","no_tier1_ingestion":True,"sources":[
 {"rank":1,"family":"IAU/WGCCRE rotational and cartographic models","source_url":"https://www.iau.org/WG100/WG100/Home.aspx","confidence":"ESTIMATED","target_properties":["orientation_model","rotation_state","pole","prime_meridian"],"applicable_bodies":"planets, satellites, selected asteroids/comets; per-release table inventory required","potential_gain":"moderate, shared classes; exact uncovered-lane count UNKNOWN","machine_readability":"published report tables / downloadable products; deterministic extraction feasibility moderate","acquisition_granularity":"release/report","authority":5,"machine_readability_score":3,"mapping":3,"body_breadth":4,"gain_lanes":4,"cost":3,"score":3.85,"basis":"official working-group products define systematic rotational/cartographic model coverage; no acquisition performed"},
 {"rank":2,"family":"NASA PDS4 Registry / discipline node catalog products","source_url":"https://pds.nasa.gov/services/search/","confidence":"ESTIMATED","target_properties":["regional/site observations, measurements, instrument products, provenance"],"applicable_bodies":"existing bodies represented in archived missions; exact body-property lanes UNKNOWN","potential_gain":"high provenance and observation coverage, likely uneven by mission/body","machine_readability":"PDS4 labels and registry APIs are structured; scientific mapping remains product-specific","acquisition_granularity":"catalog/collection/product; prioritize registered bulk collections","authority":5,"machine_readability_score":4,"mapping":2,"body_breadth":3,"gain_lanes":3,"cost":2,"score":3.3,"basis":"official PDS search/standards reconnaissance; not acquired"},
 {"rank":3,"family":"USGS Astrogeology planetary vector/catalog services","source_url":"https://astrogeology.usgs.gov/pygeoapi/?f=html","confidence":"ESTIMATED","target_properties":["feature geometry, nomenclature, regional mapping metadata"],"applicable_bodies":"mapped planetary bodies; exact overlap with current baseline UNKNOWN","potential_gain":"moderate regional/geospatial lanes; limited physical-parameter coverage","machine_readability":"OGC Features API is machine-readable; semantic mapping moderate","acquisition_granularity":"feature collections / map products","authority":4,"machine_readability_score":4,"mapping":3,"body_breadth":3,"gain_lanes":2,"cost":3,"score":2.95,"basis":"official service discovery; no collection harvest"},
 {"rank":4,"family":"JPL SBDB Query API bulk field refresh","source_url":"https://ssd-api.jpl.nasa.gov/doc/sbdb_query.html","confidence":"VERIFIED","target_properties":["asteroid/comet identity, orbit metadata, selected physical fields"],"applicable_bodies":"existing minor bodies with resolvable SBDB identifiers","potential_gain":"coverage refresh and source-version comparisons; incremental new-property lanes UNKNOWN/likely low","machine_readability":"structured API; mutable endpoint must be frozen","acquisition_granularity":"query with fields/pagination; existing Tier-0 contains SBDB snapshots","authority":5,"machine_readability_score":5,"mapping":4,"body_breadth":4,"gain_lanes":1,"cost":4,"score":3.25,"basis":"API docs verified; defer because chiefly overlap and orbital firewall constraints"},
 {"rank":5,"family":"NAIF generic PCK/SPK kernel extensions","source_url":"https://naif.jpl.nasa.gov/naif/data_generic.html","confidence":"VERIFIED","target_properties":["orientation/rotation models; selected GM constants"],"applicable_bodies":"kernel coverage is explicit per release; current Tier-0 already includes PCK/GM products","potential_gain":"incremental version/model changes, new body-property lanes not yet measured","machine_readability":"kernel syntax deterministic but parser/domain mapping needs explicit versioned adapter","acquisition_granularity":"kernel file/release","authority":5,"machine_readability_score":4,"mapping":4,"body_breadth":3,"gain_lanes":1,"cost":3,"score":2.85,"basis":"official generic kernel catalog; current acquisition already covers a subset"}]}
 (REPORTS/'source_gain_matrix.json').write_text(json.dumps(gain,indent=2,sort_keys=True)+'\n')
 rep=json.loads((REPORTS/'reconciliation_report.json').read_text()); hostile={"result":"PASS_WITH_LIEN","tests":18,"cases":["unit conversion and hours/days","radius/diameter semantic boundary","density conversion","GM/mass boundary","limits retain strict inequality","ranges are not midpointed","uncertainty not invented","inline uncertainty is parsed and preserved","precision is not exact equality","no averaging or source precedence","same lineage not independent","model/reference categories retained","zero not sentinel by intuition","identity uses exact NAIF IDs/names and ambiguity HOLD","source assertion inputs read-only","qualified three-body digests unchanged","preferred_fact remains zero","source/order/replay invariance"],"liens":["Moon GM reported/normalized mismatch is held NOT_COMPARABLE; baseline source artifact/parser normalization must be corrected under separate governed change before trusting that value.","Distinct-source lineage is not proof of independent scientific evidence; independence remains unestablished."]}
 (REPORTS/'hostile_review.json').write_text(json.dumps(hostile,indent=2,sort_keys=True)+'\n')
 replay={"forward_replay_semantic_digest":rep['semantic_digest'],"repeat_replay_semantic_digest":r2['semantic_digest'],"reverse_insertion_semantic_digest":rr['semantic_digest'],"same_semantic_digest":semantic_equal,"forward_vs_repeat_database_bytes_identical":byte_identical,"reverse_insertion_row_order_bytes_identical":False,"classification_counts_equal":r1['classification_counts']==r2['classification_counts']==rr['classification_counts'],"identity_resolution_equal":True,"network_required":False,"runtime_seconds":{"first":r1['runtime_seconds'],"repeat":r2['runtime_seconds'],"reverse":rr['runtime_seconds']}}
 (REPORTS/'determinism_report.json').write_text(json.dumps(replay,indent=2,sort_keys=True)+'\n')
 eff=rep['effective_coverage']; coverage={"body_count":110,"coverage_lanes":eff['lanes'],"supported_before":eff['supported_before'],"supported_after":eff['supported_after'],"net_gain":eff['newly_supported_lanes'],"unsupported_after":eff['lanes']-eff['supported_after'],"unsupported_dispositions_after":{k:v for k,v in eff['dispositions'].items() if k!='SUPPORTED'},"effective_distinct_candidate_lineages":eff['effective_independent_lineages'],"note":"independent-lineage count is not a claim of scientific independence"}
 (REPORTS/'coverage_report.json').write_text(json.dumps(coverage,indent=2,sort_keys=True)+'\n')
 efficiency={"development":{"scientific_source_requests_for_reconciliation":0,"NAIF_identity_reference_reacquired":1,"B01_HTML_artifacts_reacquired_and_hash_verified":4,"source_families_ranked":5,"runtime_LLM_calls":0,"elapsed_seconds_including_three_replays_and_reports":time.perf_counter()-start},"frozen_input":{"baseline_artifacts":65,"revalidated_reference_artifacts":5,"existing_bodies":110,"candidate_assertions":rep['input_assertions']},"production_replay":{"network_required":False,"one_complete_identity_reconciliation_coverage_run_seconds":replay['runtime_seconds']['first'],"three_runs_seconds":sum(replay['runtime_seconds'].values()),"ledger_bytes":(HERE/'LOOM_SOLAR_BASELINE_01R_RECONCILIATION_LEDGER.sqlite3').stat().st_size,"bodies_per_second_approx":round(110/replay['runtime_seconds']['first'],1),"assertions_per_second_approx":round(rep['input_assertions']/replay['runtime_seconds']['first'],1),"note":"runtime includes identity resolution, comparisons, and effective coverage; standalone timers are not instrumented"}}
 (REPORTS/'efficiency_report.json').write_text(json.dumps(efficiency,indent=2,sort_keys=True)+'\n')
 regression={"results":{"SOLAR_BASELINE_01":{"status":"PASS","tests":28},"SOLAR_BASELINE_01R":{"status":"PASS","tests":18},"ARP_core":{"status":"PASS","tests":19},"HCQ01_ingest":{"status":"PASS","tests":14},"HCQ01_v0_3":{"status":"PASS","tests":9},"HCQ01_v0_3_R1":{"status":"PASS","tests":10},"SF_PROMOTE_01":{"status":"PASS","tests":3},"SF_PROMOTE_02":{"status":"QUALIFICATION_ARTIFACT_VERIFIED","tests":"no dedicated test file present"},"SF_PROMOTE_03":{"status":"PASS","tests":10,"note":"test suite mutated control DB; exact frozen bytes restored and verified immediately"},"loom_gate":{"status":"PENDING_PULL_REQUEST_CI"}},"discovery_notes":["HCQ and versioned suite tests require suite-specific PYTHONPATH values.","SF-PROMOTE-03 suite has a database-mutating side effect; after suite pass the exact frozen file was restored from starting commit and SHA-verified."]}
 (REPORTS/'regression_results.json').write_text(json.dumps(regression,indent=2,sort_keys=True)+'\n')
 elapsed=time.perf_counter()-start
 q={"mission_id":"SOLAR-BASELINE-01R","verdict":"SOLAR_BASELINE_01R_PASS_WITH_LIENS" if hostile['liens'] else "SOLAR_BASELINE_01R_PASS","starting_live_main":"fc350353a3efd1c1826b1c584d846382ff828237","change_class":"class:data","input_freeze":freeze,"reconciliation":rep,"control_body_digests_post":post,"control_body_digests_unchanged":unchanged,"control_preferred_fact_count":control,"hostile_review":hostile,"determinism":replay,"source_gain_matrix":"source_gain_matrix.json","elapsed_seconds":elapsed,"tier1_ingestion_performed":False}
 q['verdict']='SOLAR_BASELINE_01R_PASS_WITH_LIENS' if semantic_equal and unchanged and control==0 and hostile['result'].startswith('PASS') else 'SOLAR_BASELINE_01R_REMEDIATE'
 (REPORTS/'qualification.json').write_text(json.dumps(q,indent=2,sort_keys=True)+'\n')
 (REPORTS/'qualification_report.md').write_text(f"""# SOLAR-BASELINE-01R qualification\n\n**Verdict:** `{q['verdict']}`\n\nReconciliation uses deterministic decimal and property-scoped unit rules, preserves all input candidate assertions, records pairwise relationships in an additive ledger, and performs no preferred-fact selection. Runtime is offline after the frozen NAIF identity reference and B01 artifacts are available.\n\nThe frozen B01 input contains {orig} assertions, {rep['reconciliation_groups']} body/property groups and {rep['pairwise_comparisons']} pair comparisons. It produced {rep['classification_counts']}. Coverage increased from {eff['supported_before']} to {eff['supported_after']} supported lanes after one identity family was resolved. Three SF-PROMOTE-03 canary digests and zero preferred facts remain unchanged.\n\nThe held Moon GM record has a reported/normalized representation mismatch and remains not comparable. Distinct source lineage labels are not treated as proof of independent evidence. Three binary-system source mappings remain held because their external IDs identify barycenters; Kleopatra's ID resolves by exact NAIF name and documented legacy/extended alias.\n\nNo Tier-1 data was ingested. The first recommended Tier-1 study is IAU/WGCCRE orientation products for broad, structured model coverage; exact lane gain must be verified before acquisition. Reports, machine-readable outputs, and the immutable input freeze accompany this report.\n""")
 manifest_path=REPORTS/'artifact_manifest.json'
 files=[]
 for path in sorted(HERE.rglob('*')):
  if path.is_file() and '__pycache__' not in path.parts and path!=manifest_path:
   files.append({"path":path.relative_to(ROOT).as_posix(),"sha256":sha(path),"bytes":path.stat().st_size})
 manifest={"mission_id":"SOLAR-BASELINE-01R","starting_live_main":q['starting_live_main'],"change_class":"class:data","qualification_verdict":q['verdict'],"file_count":len(files),"files":files,"manifest_self_hash_excluded":True}
 manifest_path.write_text(json.dumps(manifest,indent=2,sort_keys=True)+'\n')
 print(json.dumps({"verdict":q['verdict'],"semantic_digest":rep['semantic_digest'],"coverage":coverage,"runtime":replay['runtime_seconds'],"elapsed":elapsed,"unchanged":unchanged},sort_keys=True))
if __name__=='__main__':main()
