"""Architecture trade driven by the physical scale gap exposed in E1 #212-#215."""
import json
LIMIT_JET_W=12781129528125.0
ALLOC_KG=160000.0
PRESENT_DFD_UPPER_W_KG=1500.0

def build_trade():
 ideal=LIMIT_JET_W/ALLOC_KG
 return {"schema":"LOOM.Wayfarer.TorchSourceArchitectureBreakthroughTrade","schema_version":"0.1","status":"PASS",
 "authority":{"claim":"E1_TORCH_SOURCE_ARCHITECTURE_BREAKTHROUGH_REQUIREMENTS_TRADE_ONLY","campaign_state_mutation":"ZERO","llm_calculation_authority":"ZERO","canon_changed":False,"source_architecture_certified":False,"fuel_cycle_certified":False,"performance_cards_changed":False},
 "minimum_ideal_LIMIT_specific_power_MW_kg_if_160t_all_source":ideal/1e6,
 "scale_gap_vs_present_DFD_upper":ideal/PRESENT_DFD_UPPER_W_KG,
 "interpretation":"IDEAL_FLOOR_ONLY_BECAUSE_160T_IS_TOTAL_CANDIDATE_PROPULSION_ALLOCATION_AND_DIRECTED_FRACTION_CANNOT_EXCEED_ONE",
 "preferred_research_direction":{"id":"LOW_NEUTRON_FRC_DIRECT_FUSION","status":"RESEARCH_DIRECTION_ONLY_NOT_COMPONENT_SELECTION","reason":"TOPOLOGICALLY_MATCHES_DIRECT_CHARGED_PRODUCT_HANDLING_REMASS_AUGMENTATION_AND_MAGNETIC_NOZZLE_BUT_SCALE_CLOSURE_IS_UNEARNED"},
 "families":[
 {"id":"LOW_NEUTRON_FRC_DIRECT_FUSION","disposition":"KEEP_RESEARCHING","critical_holds":["GAIN","SPECIFIC_POWER","PARTITION","NOZZLE_DETACHMENT","LIFETIME"]},
 {"id":"PULSED_MAGNETIZED_TARGET_FUSION","disposition":"ALTERNATE_ARCHITECTURE_CHANGE_REVIEW","critical_holds":["PULSE_RATE","LINER_OR_TARGET_MASS_FLOW","FATIGUE","THERMAL_CYCLING","NOZZLE_COUPLING"]},
 {"id":"GENERIC_ADVANCED_FUSION_SOURCE_WITH_REMASS_HEAT_EXCHANGER","disposition":"KEEP_AS_2226_TECHNOLOGY_NEUTRAL_FALLBACK","critical_holds":["HEAT_TRANSFER_AT_TW_SCALE","MASS","MATERIAL_LIMITS","EXHAUST_COUPLING"]},
 {"id":"ANEUTRONIC_OR_ALTERNATE_FUEL_DIRECT_FUSION","disposition":"RESEARCH_ONLY","critical_holds":["REACTIVITY","BREMSSTRAHLUNG","GAIN","FUEL_AVAILABILITY"]},
 {"id":"REQUIREMENTS_REDUCTION_OR_MODE_REDESIGN","disposition":"MANDATORY_FALLBACK_IF_SOURCE_CANNOT_CLOSE","critical_holds":["MISSION_IMPACT","ACCELERATION","EXHAUST_VELOCITY","REMASS"]}],
 "breakthrough_requirements":["SOURCE_SYSTEM_SPECIFIC_POWER_ORDERS_ABOVE_PRESENT_DFD","HIGH_DIRECTED_ENERGY_FRACTION_WITH_PHYSICAL_PARTITION","NET_GAIN_AND_RECIRCULATING_POWER_CLOSURE","LOW_ENOUGH_VEHICLE_DEPOSITION_FOR_SHIELD_THERMAL_CLOSURE","MAGNETIC_NOZZLE_DETACHMENT_AND_INTERCEPTION_CLOSURE","SERVICE_LIFE_AT_REQUIRED_MODE_DUTY"],
 "decision_rule":"DO_NOT_PROTECT_THE_CURRENT_PERFORMANCE_CARDS_BY_INVENTING_2226_SOURCE_PHYSICS; IF_MASS_ENERGY_OR_LIFETIME_CANNOT_CLOSE_REDUCE_REQUIREMENTS_OR_CHANGE_ARCHITECTURE",
 "qualified_next_step":"TORCH_REQUIREMENTS_VS_SOURCE_MASS_AND_EFFICIENCY_TRADE_SPACE"}
if __name__=="__main__": print(json.dumps(build_trade(),indent=2,sort_keys=True))
