(function(){
  let manifest=null,chunks=new Map(),epoch=null;
  async function json(url){const r=await fetch(url,{cache:'no-cache'});if(!r.ok)throw Error(`temporal fetch ${r.status} ${url}`);return r.json()}
  async function load(){const ptr=await json('/temporal/current.json');const manifestUri=ptr.manifest_uri||(`builds/${ptr.build_id}/manifest.json`);if(!manifestUri)throw Error('temporal pointer missing manifest locator');const m=await json('/temporal/'+manifestUri);manifest=m;epoch=m.start_et;return m}
  function descriptor(t){return (manifest?.function_pages||manifest?.chunks||[]).find(c=>t>=c.start_et&&t<=c.end_et)||null}
  async function chunk(t){const d=descriptor(t);if(!d)throw Error('epoch outside temporal publication');if(!chunks.has(d.sha256))chunks.set(d.sha256,await json('/temporal/'+d.uri));return chunks.get(d.sha256)}
  function hermite(a,b,t){const h=b.epoch_et-a.epoch_et,u=(t-a.epoch_et)/h,u2=u*u,u3=u2*u,h00=2*u3-3*u2+1,h10=u3-2*u2+u,h01=-2*u3+3*u2,h11=u3-u2;return a.position_km.map((p,i)=>h00*p+h10*h*a.velocity_km_s[i]+h01*b.position_km[i]+h11*h*b.velocity_km_s[i])}
  function chebEval(c,x){let b1=0,b2=0;for(let j=c.length-1;j>=1;j--){const b0=2*x*b1-b2+c[j];b2=b1;b1=b0}return c[0]+x*b1-b2}
  function segmentRelative(s,t){if(t<s.start_et||t>s.end_et)return null;if(s.representation==='CHEBYSHEV_STATE_SEGMENT'){const x=(2*t-s.start_et-s.end_et)/(s.end_et-s.start_et);return s.coefficients.map(c=>chebEval(c,x))}const aSamples=s.samples||[];if(!aSamples.length)return null;let lo=0,hi=aSamples.length-1;while(lo+1<hi){const m=(lo+hi)>>1;if(aSamples[m].epoch_et<=t)lo=m;else hi=m}const a=aSamples[lo],b=aSamples[hi];if(a.epoch_et===t)return a.resolution==='RESOLVED'?a.position_km:null;if(b.epoch_et===t)return b.resolution==='RESOLVED'?b.position_km:null;if(a.resolution!=='RESOLVED'||b.resolution!=='RESOLVED')return null;if((a.source_ref!==b.source_ref)||(a.center_source_ref!==b.center_source_ref)||(a.authority_class!==b.authority_class))return null;return hermite(a,b,t)}
  function relative(o,t){if(o.representation==='PIECEWISE_STATE_FUNCTION'){const seg=o.segments?.find(x=>t>=x.start_et&&t<=x.end_et);return seg?segmentRelative(seg,t):null}if(o.representation==='CHEBYSHEV_STATE_SEGMENT')return segmentRelative(o,t);const samples=o.samples;if(!samples?.length)return null;return segmentRelative({...o,start_et:samples[0].epoch_et,end_et:samples[samples.length-1].epoch_et,representation:'HERMITE_STATE_SEGMENT'},t)}
  async function evaluate(t){const c=await chunk(t),by=Object.fromEntries(c.objects.map(o=>[o.body_id,o])),memo={SUN:[0,0,0]};function world(id,stack=new Set()){if(memo[id])return memo[id];const o=by[id];if(!o||o.representation==='UNRESOLVED_STATE_FUNCTION'||stack.has(id))return null;const rel=relative(o,t);if(!rel)return null;stack.add(id);let parent;if(o.center_id==='SUN')parent=[0,0,0];else if(by[o.center_id])parent=world(o.center_id,stack);else parent=window.LoomRenderer.featurePosition(o.center_id);stack.delete(id);if(!parent)return null;return memo[id]=rel.map((v,i)=>v+parent[i])}for(const id of Object.keys(by))world(id);epoch=t;return memo}

  async function referenceCurves(t,points=96){const c=await chunk(t),by=Object.fromEntries(c.objects.map(o=>[o.body_id,o])),out={};for(const o of c.objects){if(o.representation==='UNRESOLVED_STATE_FUNCTION'||o.center_id==='SUN')continue;const span=Math.min(c.end_et-c.start_et,Math.max(6*3600,Math.min(32*86400,(o.end_et-o.start_et)||86400))),a=Math.max(c.start_et,t-span/2),b=Math.min(c.end_et,t+span/2),pts=[];for(let i=0;i<=points;i++){const u=a+(b-a)*i/points,r=relative(o,u);if(r)pts.push([u,...r])}if(pts.length>1)out[o.body_id]=pts}return out}
  window.LoomTemporal={load,evaluate,referenceCurves,get manifest(){return manifest},get epoch(){return epoch}};
})();

(function(){
  let running=false,direction=1,rateDays=100,last=0,busy=false;
  function label(et){const m=window.LoomTemporal.manifest;if(!m)return 'TEMPORAL LOADING';const days=(et-m.start_et)/86400;return `TDB +${days.toFixed(2)} d`}
  async function apply(et){const m=window.LoomTemporal.manifest;if(!m||busy)return;busy=true;try{et=Math.max(m.start_et,Math.min(m.end_et,et));const world=await window.LoomTemporal.evaluate(et);window.LoomRenderer.setFeaturePositions(world);const curves=await window.LoomTemporal.referenceCurves(et);window.LoomRenderer.setTemporalCurves(curves);const s=document.getElementById('timeScrub');s.value=String(1000*(et-m.start_et)/(m.end_et-m.start_et));document.getElementById('timeEpoch').textContent=label(et);window.__solarTemporalState={epoch_et:et,running,direction,rate_days_per_second:rateDays,resolved:Object.keys(world).length};}finally{busy=false}}
  async function tick(now){if(!last)last=now;if(running&&window.LoomTemporal.manifest&&!busy){const dt=(now-last)/1000,et=window.LoomTemporal.epoch+direction*rateDays*86400*dt,m=window.LoomTemporal.manifest;if(et<m.start_et||et>m.end_et){running=false;document.getElementById('timePlay').textContent='PLAY'}else await apply(et)}last=now;requestAnimationFrame(tick)}
  async function init(){try{document.getElementById('timeEpoch').textContent='TEMPORAL LOAD';const m=await window.LoomTemporal.load();document.getElementById('timeEpoch').textContent='TEMPORAL APPLY';const play=document.getElementById('timePlay'),rev=document.getElementById('timeReverse'),rate=document.getElementById('timeRate'),scrub=document.getElementById('timeScrub');play.onclick=()=>{running=!running;play.textContent=running?'PAUSE':'PLAY'};rev.onclick=()=>{direction*=-1;rev.textContent=direction<0?'FWD':'REV'};rate.onchange=()=>rateDays=Number(rate.value);scrub.oninput=()=>apply(m.start_et+(m.end_et-m.start_et)*Number(scrub.value)/1000);await apply(m.start_et);requestAnimationFrame(tick);window.__solarTemporalReady=true}catch(e){const msg=String(e);document.getElementById('timeEpoch').textContent='ERR '+msg.slice(0,42);window.__solarTemporalError=msg;console.error('LOOM temporal init',e)}}
  addEventListener('load',()=>{const wait=()=>window.__solarBasemapReady?init():setTimeout(wait,25);wait()});window.LoomTemporalClock={apply};
})();
