-- LOOM Solar Factual Enrichment v0.2 SQLite HCQ semantic analogue
-- HCQ-01 Ceres; non-production.
PRAGMA foreign_keys=ON;
CREATE TABLE meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE body(body_id TEXT PRIMARY KEY,canonical_name TEXT NOT NULL UNIQUE,body_class TEXT NOT NULL,parent_body_id TEXT REFERENCES body(body_id),status TEXT NOT NULL CHECK(status IN ('ACTIVE','RETIRED','CANDIDATE')));
CREATE TABLE property_definition(property_code TEXT PRIMARY KEY,property_group TEXT NOT NULL,canonical_name TEXT NOT NULL,description TEXT NOT NULL,canonical_unit TEXT,expected_value_kind TEXT NOT NULL,derivable INTEGER NOT NULL DEFAULT 0 CHECK(derivable IN(0,1)),notes TEXT);
CREATE TABLE source(source_id INTEGER PRIMARY KEY,source_type TEXT NOT NULL CHECK(source_type IN('MISSION_PRODUCT','DATA_PRODUCT','PEER_REVIEWED','OFFICIAL_REFERENCE','REFERENCE_COMPILATION','HISTORICAL_PRIMARY','OTHER')),provider TEXT,title TEXT NOT NULL,authors TEXT,journal TEXT,doi TEXT,url TEXT,publication_date TEXT,product_name TEXT,product_version TEXT,persistent_identifier TEXT,retrieved_at TEXT NOT NULL,citation_text TEXT,notes TEXT);
CREATE UNIQUE INDEX uq_source_doi ON source(doi) WHERE doi IS NOT NULL;
CREATE TABLE body_region(region_id INTEGER PRIMARY KEY,body_id TEXT NOT NULL REFERENCES body(body_id),parent_region_id INTEGER REFERENCES body_region(region_id),region_type TEXT NOT NULL,canonical_name TEXT,latitude_min_deg REAL,latitude_max_deg REAL,longitude_min_deg REAL,longitude_max_deg REAL,reference_frame TEXT,description TEXT,confidence_class TEXT NOT NULL DEFAULT 'UNKNOWN' CHECK(confidence_class IN ('VERY_HIGH','HIGH','MODERATE','LOW','CONTESTED','UNKNOWN')),source_id INTEGER REFERENCES source(source_id),notes TEXT,CHECK(latitude_min_deg IS NULL OR latitude_min_deg BETWEEN -90 AND 90),CHECK(latitude_max_deg IS NULL OR latitude_max_deg BETWEEN -90 AND 90),CHECK(latitude_max_deg IS NULL OR latitude_min_deg IS NULL OR latitude_max_deg>=latitude_min_deg));
CREATE TABLE observation(observation_id INTEGER PRIMARY KEY,body_id TEXT NOT NULL REFERENCES body(body_id),region_id INTEGER REFERENCES body_region(region_id),mission TEXT,spacecraft TEXT,instrument TEXT,observation_product_id TEXT,observation_time_start TEXT,observation_time_end TEXT,observation_method TEXT,spatial_context TEXT,source_id INTEGER REFERENCES source(source_id),notes TEXT,CHECK(observation_time_end IS NULL OR observation_time_start IS NULL OR observation_time_end>=observation_time_start));
CREATE TABLE fact(fact_id INTEGER PRIMARY KEY,body_id TEXT NOT NULL REFERENCES body(body_id),region_id INTEGER REFERENCES body_region(region_id),property_code TEXT NOT NULL REFERENCES property_definition(property_code),value_semantics TEXT NOT NULL CHECK(length(trim(value_semantics))>0),value_numeric REAL,value_min REAL,value_max REAL,value_boolean INTEGER,value_text TEXT,uncertainty_plus REAL,uncertainty_minus REAL,canonical_unit TEXT,reported_value_text TEXT,reported_unit TEXT,evidence_class TEXT NOT NULL CHECK(evidence_class IN ('DIRECT_SAMPLE','IN_SITU_DIRECT','IN_SITU_REMOTE','EARTH_REMOTE','DYNAMICAL_INFERENCE','ANALOG_INFERENCE','PHYSICAL_MODEL','THEORETICAL_EXPECTATION','DERIVED')),measurement_method TEXT,spatial_context TEXT,temporal_context TEXT,confidence_class TEXT NOT NULL DEFAULT 'UNKNOWN' CHECK(confidence_class IN ('VERY_HIGH','HIGH','MODERATE','LOW','CONTESTED','UNKNOWN')),fact_status TEXT NOT NULL DEFAULT 'CANDIDATE' CHECK(fact_status IN ('CANDIDATE','CURRENT','RETIRED')),knowledge_valid_from TEXT,knowledge_valid_until TEXT,supersedes_fact_id INTEGER REFERENCES fact(fact_id),created_at TEXT NOT NULL,notes TEXT,CHECK(value_max IS NULL OR value_min IS NULL OR value_max>=value_min),CHECK(uncertainty_plus IS NULL OR uncertainty_plus>=0),CHECK(uncertainty_minus IS NULL OR uncertainty_minus>=0),CHECK(knowledge_valid_until IS NULL OR knowledge_valid_from IS NULL OR knowledge_valid_until>=knowledge_valid_from));
CREATE TABLE fact_observation(fact_id INTEGER NOT NULL REFERENCES fact(fact_id) ON DELETE CASCADE,observation_id INTEGER NOT NULL REFERENCES observation(observation_id),relationship TEXT NOT NULL DEFAULT 'SUPPORTS',PRIMARY KEY(fact_id,observation_id));
CREATE TABLE source_assertion(fact_id INTEGER NOT NULL REFERENCES fact(fact_id) ON DELETE CASCADE,source_id INTEGER NOT NULL REFERENCES source(source_id),assertion_role TEXT NOT NULL CHECK(assertion_role IN ('PRIMARY','SUPPORTING','CONTRADICTING','SUPERSEDING')),source_locator TEXT,notes TEXT,PRIMARY KEY(fact_id,source_id,assertion_role));
CREATE TABLE material_evidence(material_evidence_id INTEGER PRIMARY KEY,body_id TEXT NOT NULL REFERENCES body(body_id),region_id INTEGER REFERENCES body_region(region_id),material_family TEXT NOT NULL,material_species TEXT,physical_form TEXT,host_material TEXT,location_context TEXT,evidence_class TEXT NOT NULL CHECK(evidence_class IN ('DIRECT_SAMPLE','IN_SITU_DIRECT','IN_SITU_REMOTE','EARTH_REMOTE','DYNAMICAL_INFERENCE','ANALOG_INFERENCE','PHYSICAL_MODEL','THEORETICAL_EXPECTATION','DERIVED')),abundance_semantics TEXT NOT NULL DEFAULT 'UNKNOWN',abundance_value REAL,abundance_min REAL,abundance_max REAL,abundance_unit TEXT,reported_abundance TEXT,depth_min REAL,depth_max REAL,depth_unit TEXT,thickness_min REAL,thickness_max REAL,thickness_unit TEXT,areal_extent REAL,areal_extent_unit TEXT,estimated_volume REAL,estimated_volume_unit TEXT,spatial_heterogeneity TEXT,measurement_resolution TEXT,measurement_method TEXT,confidence_class TEXT NOT NULL DEFAULT 'UNKNOWN' CHECK(confidence_class IN ('VERY_HIGH','HIGH','MODERATE','LOW','CONTESTED','UNKNOWN')),fact_status TEXT NOT NULL DEFAULT 'CANDIDATE' CHECK(fact_status IN ('CANDIDATE','CURRENT','RETIRED')),observation_id INTEGER REFERENCES observation(observation_id),source_id INTEGER REFERENCES source(source_id),notes TEXT,CHECK(abundance_max IS NULL OR abundance_min IS NULL OR abundance_max>=abundance_min),CHECK(depth_max IS NULL OR depth_min IS NULL OR depth_max>=depth_min),CHECK(thickness_max IS NULL OR thickness_min IS NULL OR thickness_max>=thickness_min));
CREATE TABLE activity_fact(activity_id INTEGER PRIMARY KEY,body_id TEXT NOT NULL REFERENCES body(body_id),region_id INTEGER REFERENCES body_region(region_id),activity_type TEXT NOT NULL,description TEXT NOT NULL,observed_from TEXT,observed_until TEXT,evidence_class TEXT NOT NULL CHECK(evidence_class IN ('DIRECT_SAMPLE','IN_SITU_DIRECT','IN_SITU_REMOTE','EARTH_REMOTE','DYNAMICAL_INFERENCE','ANALOG_INFERENCE','PHYSICAL_MODEL','THEORETICAL_EXPECTATION','DERIVED')),confidence_class TEXT NOT NULL DEFAULT 'UNKNOWN' CHECK(confidence_class IN ('VERY_HIGH','HIGH','MODERATE','LOW','CONTESTED','UNKNOWN')),observation_id INTEGER REFERENCES observation(observation_id),source_id INTEGER REFERENCES source(source_id),notes TEXT,CHECK(observed_until IS NULL OR observed_from IS NULL OR observed_until>=observed_from));
CREATE TABLE body_model_product(model_product_id INTEGER PRIMARY KEY,body_id TEXT NOT NULL REFERENCES body(body_id),region_id INTEGER REFERENCES body_region(region_id),model_type TEXT NOT NULL,model_name TEXT NOT NULL,model_version TEXT,reference_frame TEXT,resolution_description TEXT,source_id INTEGER REFERENCES source(source_id),persistent_identifier TEXT,product_url TEXT,sha256 TEXT,byte_count INTEGER,notes TEXT,CHECK(byte_count IS NULL OR byte_count>=0));
CREATE TABLE region_model_product(region_id INTEGER NOT NULL REFERENCES body_region(region_id) ON DELETE CASCADE,model_product_id INTEGER NOT NULL REFERENCES body_model_product(model_product_id),relationship TEXT NOT NULL,PRIMARY KEY(region_id,model_product_id,relationship));
CREATE TABLE gravity_model(gravity_model_id INTEGER PRIMARY KEY,body_id TEXT NOT NULL REFERENCES body(body_id),model_name TEXT NOT NULL,model_version TEXT,gravitational_parameter REAL,gm_unit TEXT NOT NULL DEFAULT 'km^3/s^2',reference_radius REAL,reference_radius_unit TEXT NOT NULL DEFAULT 'km',maximum_degree INTEGER,maximum_order INTEGER,normalization TEXT,coefficient_convention TEXT,reference_frame TEXT,reference_epoch TEXT,source_id INTEGER REFERENCES source(source_id),persistent_identifier TEXT,product_url TEXT,sha256 TEXT,byte_count INTEGER,validity_notes TEXT,notes TEXT,CHECK(gravitational_parameter IS NULL OR gravitational_parameter>0),CHECK(reference_radius IS NULL OR reference_radius>0),CHECK(maximum_degree IS NULL OR maximum_degree>=0),CHECK(maximum_order IS NULL OR maximum_order>=0),CHECK(byte_count IS NULL OR byte_count>=0));
CREATE TABLE orientation_model(orientation_model_id INTEGER PRIMARY KEY,body_id TEXT NOT NULL REFERENCES body(body_id),model_name TEXT NOT NULL,model_version TEXT,model_authority TEXT,reference_frame TEXT,reference_epoch TEXT,pole_ra_deg REAL,pole_dec_deg REAL,pole_ra_rate REAL,pole_dec_rate REAL,prime_meridian_deg REAL,prime_meridian_rate REAL,rotation_period_seconds REAL,rotation_state TEXT,libration_model TEXT,source_id INTEGER REFERENCES source(source_id),persistent_identifier TEXT,product_url TEXT,sha256 TEXT,validity_notes TEXT,notes TEXT,CHECK(rotation_period_seconds IS NULL OR rotation_period_seconds>0),CHECK(pole_dec_deg IS NULL OR pole_dec_deg BETWEEN -90 AND 90));
CREATE TABLE derived_quantity(derived_id INTEGER PRIMARY KEY,body_id TEXT NOT NULL REFERENCES body(body_id),region_id INTEGER REFERENCES body_region(region_id),property_code TEXT NOT NULL REFERENCES property_definition(property_code),value_numeric REAL NOT NULL,unit TEXT NOT NULL,uncertainty_plus REAL,uncertainty_minus REAL,derivation_method TEXT NOT NULL,derivation_version TEXT NOT NULL,reference_epoch TEXT,computed_at TEXT NOT NULL,notes TEXT);
CREATE TABLE derived_input(derived_id INTEGER NOT NULL REFERENCES derived_quantity(derived_id) ON DELETE CASCADE,fact_id INTEGER NOT NULL REFERENCES fact(fact_id),input_role TEXT NOT NULL,PRIMARY KEY(derived_id,fact_id,input_role));
CREATE TABLE preferred_fact(body_id TEXT NOT NULL REFERENCES body(body_id),region_id INTEGER REFERENCES body_region(region_id),property_code TEXT NOT NULL REFERENCES property_definition(property_code),fact_id INTEGER NOT NULL REFERENCES fact(fact_id),selection_reason TEXT NOT NULL,selected_at TEXT NOT NULL);
CREATE UNIQUE INDEX uq_preferred_fact_global ON preferred_fact(body_id,property_code) WHERE region_id IS NULL;
CREATE UNIQUE INDEX uq_preferred_fact_region ON preferred_fact(body_id,region_id,property_code) WHERE region_id IS NOT NULL;
CREATE INDEX idx_fact_body_property ON fact(body_id,property_code);
CREATE INDEX idx_fact_region_property ON fact(region_id,property_code);
CREATE INDEX idx_material_body_family ON material_evidence(body_id,material_family);
CREATE INDEX idx_material_region_family ON material_evidence(region_id,material_family);

-- Cross-table semantic integrity is stronger than ordinary foreign keys: a
-- regional row must belong to the same body as the row that references it.
CREATE TRIGGER trg_observation_region_body BEFORE INSERT ON observation
WHEN NEW.region_id IS NOT NULL AND EXISTS (SELECT 1 FROM body_region r WHERE r.region_id=NEW.region_id AND r.body_id<>NEW.body_id)
BEGIN SELECT RAISE(ABORT,'observation region belongs to another body'); END;
CREATE TRIGGER trg_fact_region_body BEFORE INSERT ON fact
WHEN NEW.region_id IS NOT NULL AND EXISTS (SELECT 1 FROM body_region r WHERE r.region_id=NEW.region_id AND r.body_id<>NEW.body_id)
BEGIN SELECT RAISE(ABORT,'fact region belongs to another body'); END;
CREATE TRIGGER trg_material_region_body BEFORE INSERT ON material_evidence
WHEN NEW.region_id IS NOT NULL AND EXISTS (SELECT 1 FROM body_region r WHERE r.region_id=NEW.region_id AND r.body_id<>NEW.body_id)
BEGIN SELECT RAISE(ABORT,'material region belongs to another body'); END;
CREATE TRIGGER trg_activity_region_body BEFORE INSERT ON activity_fact
WHEN NEW.region_id IS NOT NULL AND EXISTS (SELECT 1 FROM body_region r WHERE r.region_id=NEW.region_id AND r.body_id<>NEW.body_id)
BEGIN SELECT RAISE(ABORT,'activity region belongs to another body'); END;
CREATE TRIGGER trg_model_region_body BEFORE INSERT ON body_model_product
WHEN NEW.region_id IS NOT NULL AND EXISTS (SELECT 1 FROM body_region r WHERE r.region_id=NEW.region_id AND r.body_id<>NEW.body_id)
BEGIN SELECT RAISE(ABORT,'model region belongs to another body'); END;
CREATE TRIGGER trg_region_model_body BEFORE INSERT ON region_model_product
WHEN EXISTS (SELECT 1 FROM body_region r JOIN body_model_product m ON m.model_product_id=NEW.model_product_id WHERE r.region_id=NEW.region_id AND r.body_id<>m.body_id)
BEGIN SELECT RAISE(ABORT,'region/model belong to different bodies'); END;
CREATE TRIGGER trg_fact_observation_body BEFORE INSERT ON fact_observation
WHEN EXISTS (SELECT 1 FROM fact f JOIN observation o ON o.observation_id=NEW.observation_id WHERE f.fact_id=NEW.fact_id AND f.body_id<>o.body_id)
BEGIN SELECT RAISE(ABORT,'fact/observation belong to different bodies'); END;
